openmv/openmv

usr/pydfu.py

In PyUSB 1.0.0.b1, the usb.util.get_string function takes a lenght argument.
In PyUSB 1.0.0.b2, it no longer takes a length argument.
Since python2 seems to come with PyUSB 1.0.0.b1 and python3 seems to come
with 1.0.0.b2, this change allows the same source to work with either
version of PyUSB.

Fix pydfu.py to work with Beta 1 and Beta 2 versions of PyUSB

---

src/omv/soft_i2c.c
src/omv/soft_i2c.h

The soft_i2c code now does not glitch on startup, scans the bus to get all devices unstuck if they are, and generates a very pretty and precise waveform. The data line does not change unless between clocks now. Also, I fixed a bug in the previous code where the data line was not released to receive an ACK back from the I2C device. The software would read the value of the data line instead if the last data bit transmitted was a 1.
All this work was put in because I couldn't get the MLX sensor working on a bad board. Might as well not have the effort go to waste.

Made Soft I2C Pretty

---

src/omv/xalloc.c
src/omv/xalloc.h

Now the functions detect if you are trying to alloc 0 bytes and don't fail if you do that. Additionally, I added some comments on behavior. (I studied what the gc functions did extensively
to know the behavior of this stuff). All changes have been tested with
code that does memory allocs (Face Detection/Tracking).

Made XALLOC better.

---

src/Makefile
src/omv/Makefile
src/omv/fb_stack.c
src/omv/fb_stack.h
src/omv/ff_wrapper.c
src/omv/ff_wrapper.h

The alloc functions allow you to use the framebuffer as a storage space.
It's very simple but effective. You can alloc which puts some memory on a
stack... and then when you're done you can free which pops the stack.
Pops (frees) must be done in reverse order of pushes (allocs).
In general, functions should call the init code before using the stack.
It could be in a bad state.
Also, I added some wrappers for file system functions to make that stuff
easier. This will be used in the future.

Added some helper stuff.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c

The negate function gives you the ability to negate an image before
running difference on it. The difference function will subtract two images
from each other and return the abs() of the result.
I believe it would have been optimal to work on the RGB565 image in the
LAB color space. However, since we don't have an inverse LAB lut this is
not possible. If we could replace LAB with YUV then that would free up
space to have an inverse YUV table (YUV->RGB).

Add frame differencing functions.

---

src/Makefile
src/omv/Makefile
src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/ppm.c

Added BMP file format reading and writing support code and modified the
ppm code to match. Upper level glue code has been left intact to be
altered in future commits.
Tested save() and ppm writing functionality still works. More
comprehensive tests coming soon.
... Kinda concerned that standard image file formats might not cut it for
the speed we'd like to have when using image files in function calls. I
think only grayscale is going to be fast. All other formats require a
lot of prep work.
I think I may modify some of this low level stuff in the future to
autodetect if an entire grayscale image can be read in or written out
in one go to speed that stuff up.

Add BMP and P2/3/5/6 file format support.

---

src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/jpeg.c
src/omv/img/ppm.c
src/omv/py/py_image.c
src/omv/usbdbg.c

There's not a lot of actual functionality changes from the last commit.
However, switching the basic wrapper library to just long_jump on
failure and moving all the state info to structs required changes to all
the base functions in the last commit. The rest of the changes are to
link in the new functionality and to get the code to compile (usbdbg.c
edits). GitHub's diff makes the changes look 2X longer.
Next I'll work on a function which abstracts the problem of opening an
image up and executing a line by line function op on it. I already
worked the code out for that. But, it's not in this commit to keep
things streamlined.

Add BMP/PNM/JPEG image file loading and saving.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/mdefs.h
src/omv/py/py_image.c
src/omv/usbdbg.c
usr/tests/test_save.py

It now figures out the file type from the file extension. If no file
extension is given it just saves the file as BMP if its not a JPEG image
or JPEG if it's a JPEG image. If you specify an extension and the file is
not of that type then it will give you an error.
The new test_save.py should run until you reach the JPEG image part
where it quits due to lack of JPEG support natively on OV7725 boards.
Maybe JPEG mode should be supported by just compressing pictures?

Fixed save image.

---

src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/ppm.c

All the work previously has been more or less leading up to supporting
this function. The line op function will open a file and execute a
function pointer on each line of the file opened to modify the frame
buffer.

Add line op function.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
usr/tests/test_erode_and_dilate.py

The old code did not actually implement the erode and dilate kernels
correctly. However, it might have been a little faster because it avoided
the boundary problem.
In the future we can optimize all the kernel code to have different loops
for doing the edges of image versus the center. But, for now, this is
good enough. QVGA color tracking with kernels will be slow, but, the
speed can be improved with QQVGA resolution. Using a 3x3 kernel is
plenty fast. Larger ones are slower.
I also added the ability for you to set the threshold for erode and
dilate. This lets you make the kernel a little bit smarter so that it
won't erode or dilate a pixel unless the threshold is met. Meaning,
you'll be able to use erode to erode an image down to 1 pixel wide
lines.

Dilate and errode working.

---

src/omv/py/py_image.c

If the rect was not intersecting these functions would have returned bad
values.

Fix uninitialized error.

---

src/omv/fb_alloc.c
src/omv/fb_alloc.h

Now you can just grab all the free ram in the frame buffer in one go.
This fixes problems figuring out how many lines to alloc. Will update line
op code with this new info later.

Add fb_alloc_all.

---

src/Makefile
src/omv/Makefile
src/omv/fb_alloc.c
src/omv/img/imlib.h
src/omv/img/mjpeg.c
src/omv/py/py_mjpeg.c
usr/examples/mjpeg.py

The built-in mjpeg module allows you to record videos seamlessly. It
will automatically compress the frame buffer using the extra space in the
main ram. So... you don't have to pass it jpeg images. Gets 7 FPS at
320x240 RGB565 while connected to the computer too (it has to compress the
frame twice in this situation). So, it should get around 15 FPS offline.
Anyway, the module work like Gif.

Added a new mjpeg module for Mjpeg support.

---

src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/img/bmp.c
src/omv/img/gif.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/jpeg.c
src/omv/img/mjpeg.c
src/omv/img/ppm.c

All file write functions now use fb_alloc to go much faster. Writes are
re-directed to the extra frame buffer RAM and are grouped until they can
be written in a massive multi-block write to the SD card. We get the
best SD card write speed by doing things this way.
Ideally we'd want to buffer the whole file... but, this is about as good
as we're going to get for now.
Going to fix reading functions to use the same buffer next.

Updated code to use fb_alloc.

---

src/omv/fb_alloc.c
src/omv/fb_alloc.h
src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/jpeg.c
src/omv/img/ppm.c
src/omv/py/py_gif.c

File reading is runing ultra fast now. We're getting that SD card speed
the STM32 promised now. The file buffer commands have been updated to
alloc as much available memory to read as much of a file in as possible
now to speed up things. This works really great.
Note however, while the file buffer is active you have to use the file
buffer versions of tell and size. Spent a few hours on tracking down an
error related to not using the buffered versions.

Add file read speed.

---

usr/examples/ble.py

This a python module driver for the BLE module. It puts the module into
a mode that's good for machine interfacing and handles parsing commands
for you. Additionally, it lets you get access to the low level serial
port.
Users who want to use this driver will need to read and understand the
TruConnect API for what commands they can execute. This driver simply
makes executing commands easy. The user simply needs to call the
"command()" function with the strings listed on the TruConnect API and
they will get the response from the command back as a byte object.
Once the user has executed the necessary commands to setup the BLE
connection they can then do:
ble.command("str")
To put the BLE module into streaming mode and then they can just
directly access the serial port via: …

Add BLE Driver

---

src/omv/ov2640.c
src/omv/ov2640_regs.h
src/omv/ov7725.c
src/omv/ov7725_regs.h
src/omv/ov9650.c
src/omv/ov9650_regs.h
src/omv/py/py_sensor.c
src/omv/sensor.c
src/omv/sensor.h

Added setters for these camera settings. AWB is necessary for color
tracking to work correctly. AGC still runs, which causes lighting
shifts. It may need to be disabled too. Not sure... if I want to do that
or not however, because without it lightning won't get normalized to
remain at a certain level. So, turning AGC off may cause issues in other
ways.

Add AWB/HMirror/VFlip

---

src/Makefile
src/omv/Makefile
src/omv/img/imlib.h
src/omv/img/midpoint.c
src/omv/py/py_image.c

Has a bias value that allows you to control if its really a midpoint,
min, max filter, or something inbetween. Run at 160x120 or lower. 320x240
is slow (seems to be the case for all convoltions at that res).

Add Midpoint filter.

---

src/omv/py/py_sensor.c
src/omv/py/qstrdefsomv.h

So I'm just adding a function to do it cleanly and efficiently. Call
skip_frames() after changing any camera settings to let it settle.
10 frames by default works fine. Tested it.

We seem to be doing this alot in the code.

---

src/omv/py/py_image.c
src/omv/sensor.c

Note that I removed the compressing overlapped code for the main frame buffer. So, on the M4 you can't compress large images in place using the frame buffer anymore. That said, the code was bugged from other things being changed so who cares. On the M7 fb_alloc will have plenty of RAM to compress anything.

Fix compress and compressed.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/09-Feature-Detection/qrcodes_with_lens_corr.py

Speed up the algorithm by fixing the abs() issue. Do not use that
function in any of your code. It by itself cut the speed of the code
in half. I don't know what's in that function but I'm guessing it does
ABS of a float using ints or something.
I made the zoom parameter functional now too so you can use lens_corr to
zoom in on the image. Argument parsing is handled too. Finally, I
updated the only script where this is used.
Note that I'm able to get more than 10 FPS at 160x120 on the M4 and 15
FPS at 160x120 on the M7. Previous this was at about 5 FPS and 7.5 FPS
respectively.
Note: I noticed how you only allocated half the image in your old code. That was a good idea. However, after doing the RAM calculations the effort doesn't make it so that the M4 can operate on images as large as …

Speed up lens_corr.

---

udev/50-openmv.rules

These changes cause modemmanager to ignore the serial port
created when plugging in the OpenMV board.
Without these changes, the modemmanager open /dev/ttyACM0 and
sends AT commnads. This delays being able to access the REPL
using a temrinal emulator and also cause a syntax error
since the AT commands aren't valid python.

Fix udev rules

---

src/omv/fb_alloc.c
src/omv/fb_alloc.h
src/omv/py/py_image.c
src/omv/py/py_sensor.c

I also tested the firmware for about an hour to make sure there was no
stack leak.
Note that I prefer for fb_free() to still be called versus
fb_free_till_mark() doing that for you in the code.
For functions without this fix they will just free the entire fb_alloc
stack when an exception happens. For functions with this fix they will
only free up to and including the mark. Since there are no places in the
firmware where you could start building a second fb_alloc stack when one
is already in place this point is moot currently. But, if we do
something like that in the future the problem will have already been
solved.
Any new code or re-worked code should use the mark function.

Fixed fb_alloc() with mark for recently re-worked code.

---

src/omv/img/apriltag.c

This file includes all of the relevant header/source files from the
april tag library merged into one big file. Additionally, it also
includes heap/quicksort code. I've done the work of going through
the april tag library line by line and fixing it to use fb_alloc,
floats, and our fast math functions.
Anyway, I'm sending this massive file by itself first since it's so
big. Note that we might in the future want to pull things out of this
file for our own use later if we need linear algebra support.
The next PR will include files to link everything in and enable the feature.

AprilTags Main

---

src/omv/img/apriltag.c
usr/examples/16-Codes/find_apriltags_w_lens_zoom.py

Everything works. Running out of memory is fixed and the rotation value
is valid now. For 320x240 operation on the STM32H7 we're going to need
on the order of 1 MB in the entire frame buffer. The code is designed to
handle us getting this amount of memory without any new changes for
320x240 support.

April Tag Release Fixes

---

src/omv/img/apriltag.c

Memory allocation will grow organically now when more RAM is available.
... Note for the H7 we'll have to revisit the constant I'm using here to reserve space. It can be as low as 6 on the F7 and the algorithm will still work.  However, this means the hash table has less space. Raising the constant gives the hash table more space but takes away from the memory pool. On the F7 a value of 8 for the constant works great... but, if you scale the resolution up to 320x240 on the H7 you run into RAM issues  which favor using a constant value of 6. We'll need to wait and see how much RAM is on the high end H7 devices.

Fix UMM_Refactor Issues.

---

src/omv/img/imlib.h
src/omv/py/py_image.c

In response to PR https://github.com/openmv/openmv/pull/221.
You can now read and write slices of data to and image at a time.
All changes were tested.

Improved subscr and get_buffer

---

src/omv/py/py_image.c

Forgot to add size of start and end markers.

Fix error with compress_for_ide()

---

src/Makefile
src/omv/Makefile
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/py/py_gif.c
src/omv/py/py_image.c
src/omv/py/py_mjpeg.c
src/omv/sensor.c
src/omv/usbdbg.c

Moved structs along with image copying code from sensor into
framebuffer.c so that we can use the new copy_fb_to_jpeg_fb() function
in the image library for methods with "copy_to_fb" so that they update
the IDE preview when called. In particular, I need for for my new ImageWriter/Reader classes.
Will send them once this PR is accepted.
Also, I noticed that the MAIN_FB_SIZE() value is not calculated
correctly in all cases. Will fix later. Trying to keep this commit clean
for just the refactoring.
All changes have been tested. Too.

Refactor framebuffer

---

src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/06-Video-Recording/image_reader.py
usr/examples/06-Video-Recording/image_writer.py

These two new classes allow you to record image data for later viewing
at the same speed the image data was recorded. Unlike GIF/MJPEG the
image data is stored on the file system completely uncompressed in
native frame buffer format making super fast reading and writing
possible. Recording VGA Grayscale at ~13 FPS is possible along with
playing it back. (That's about 30 Mb/s folks).
...
The motivation for writing these scripts is so that you can record video
of something like a line following track, take that video home, and work
on computer vision algorithms for that data.
These classes should make it a lot easier to use the camera at home now.

Add Image Writer/Reader

---

src/omv/fb_alloc.c
src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c

No functional changes except fixing a bug with MAIN_FB_SIZE().
Need to add a flush function for the frame buffer so you don't have to call sensor.snapshot(). That's coming next.
Yes, hog works now to... however, the script needs to be fixed since the camera init is done in the wrong order.

Cleanup framebuffer code

---

src/omv/img/hough.c

This prevents the magnitude from growing repeatedly every merge.

Improve find lines merging.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

Both algorithms were tested on the OpenMV Cam using images loaded from a
file and work correctly. However, shot noise from the sensor.snapshot()
makes the output value somewhat worthless except in a situation unless
you've controlled for it. Anyway, the illuminvar method works best when the
image is constrained to a very particular view point looking at a flat
scene without shadow and then a shadow enters.
(Not adding demo's for these methods since the output looks bad
unless you've put some work into constraining the scene... need to add
HDR code and other stuff to the sensor module to get better images).

Add chrominace and illuminace invariant image generators.

---

src/omv/sensor.c
src/omv/sensor.h

This fix allows "copy_to_fb" with a different resolution than the
current frame buffer to work. It also allows the frame buffer to be
resized, etc. In particular, the pooling methods I added for optical
flow work again... you'll also be able to scale the frame buffer too.
**Make sure to rebuild after taking this. Freaking build system needs rebuild all the time...**

Restore MAIN_FB() size on snapshot()

---

src/omv/ov2640.c
src/omv/ov7725.c
src/omv/ov9650.c
usr/examples/21-Sensor-Control/sensor_auto_gain_control.py

Note... I noticed when I was double checking this stuff that for the exposure there's this extra line thing which can be used to increase the exposure value... not sure why it's needed but it exists. Registers 2D and 2E basically can be used to increase the exposure like the normal 16-bit exposure reg. Anyway, I don't have plan to include these ever in the exposure calcs. We should always make those registers 0 in our systems.

Fix bugs with sensor auto gain control.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/stats.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/20-Frame-Differencing/in_memory_shadow_removal.py
usr/examples/20-Frame-Differencing/on_disk_shadow_removal.py

Add in support for shadow removal from the current image using a shadow
free background image. Test results show the algorithm works similar to
max() while still keeping dark objects around. The preformance impact of
the algorithm is not too high. An in memory example can achieve 30 FPS.

Frame Differencing with Shadow Removal

---

src/Makefile
src/omv/Makefile
src/omv/ini.c
src/omv/ini.h
src/omv/main.c

OpenMV IDE includes an ini file generator which will let you set board
settings easily from the IDE. Currently, the IDE has support for setting
the WiFi shield up along with adding a REPL Uart.
Anyway, this commit adds support for the OpenMV Cam to parse an ini file
on startup to configure things before starting main.py. WiFi support is
not yet implmented. However, we now have the ability to turn the UART
and put the REPL terminal on it on startup given a setting in the ini
file.
(Why not use boot.py like normal MP? While that is more flxible it's
much harder for the IDE to easily write out settings for you which is
what most users will want to do versus coding this up).
...
The movitation for adding REPL UART support in particular is so that the
OpenMV Cam can be used as a slave …

Add REPL Uart Ini File Setting Support

---

src/Makefile
src/omv/Makefile
src/omv/main.c
src/omv/wifi_dbg.c
src/omv/wifi_dbg.h

All the notes about how to implement wifi programming are in the code.
Steps:
1. Get wifi_apply_settings() working first and make sure you can turn
the wifi shield on in the right mode. Then add the necessary hooks into
the network code to make it such that previous user wifi code still
works. Also, make sure to handle start and shutdown gracefully.
Basically, get all the lifecycle code working first before moving to the
next step so notning gets in a weird state and bugs creep in...
2. Get the beacon method working. Once this works OpenMV IDE should see
the camera when you hit the connect button.
3. Do the code to turn off the regular usbdbg interface and swtich to
having the data come from wifi_dbg. This isn't a lot of code... but,
will be tricky since you no longer will have USB frames …

Add wifi_dbg stub.

---

src/Makefile
src/omv/Makefile
src/omv/img/binary.c
src/omv/img/edge.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/shadow_removal.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/04-Image-Filters/color_binary_filter.py
usr/examples/04-Image-Filters/color_light_removal.py
usr/examples/04-Image-Filters/grayscale_binary_filter.py
usr/examples/04-Image-Filters/grayscale_light_removal.py

Binary() can now zero things so you can remove bright lights. All the
line ops (and/or/xor/etc) accept masks. Erode and dilate now accept
masks. And finally, you can now pass arguments versus keywords for folks
who don't read the documentation. Also, the binary image type is now
supported for these methods.
I'm putting in all this work because I saw the need for it when I was
doing shadow removal. It will come in handy very soon when impmementing
a state-of-the-art shadow removal method.
Note: Some effort needs to be put into optimizing the py_image.c code
soon. This is on the todo list before the next release. Need to make the helper
methods smarter and add more of them.

Overhaul Binary Functions

---

src/sthal/f7/src/stm32f7xx_hal_spi.c

See stm32f7 erratasheet, chapter 2.11.2.
This is a proposition that worked for us, with clk speed of 10MHz.
Maybe it wont be sufficient with a higher clk speed...

SPI timeout in slave mode, due to internal chip error

---

src/omv/main.c

* Otherwise config is read once and then reset.

Parse config on soft resets.

---

scripts/examples/03-Drawing/keypoints_drawing.py
scripts/examples/04-Image-Filters/gamma_correction.py
scripts/examples/04-Image-Filters/negative.py
scripts/examples/04-Image-Filters/vflip_hmirror_transpose.py
src/omv/img/binary.c
src/omv/img/draw.c
src/omv/img/fmath.c
src/omv/img/fmath.h
src/omv/img/imlib.h
src/omv/img/mathop.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

This PR contains various fixes to the drawing, binary, and math op methods. I discovered many of the fixes while implementing the user requested ellipse method and gamma/contrast/brightness correction. Here's the fix list:
* Added a gamma/contrast/brightness correction method which can fix the image extremely fast (uses a LUT to apply the correction).
* Add transpose support to replace allowing you now to rotate the frame buffer by 90/180/270 degrees.
* Added another image blend mode to div.
* Allow non-integer scaling on draw_string.
* Add alpha blending to draw_image (making it useful for thermal image overlays now).
* Restored the ability of draw_keypoints to take a list of 3-value tuples to draw in.
* Fixed a major bug in binary that caused it to ignore all thresholds passed in except …

Various drawing, binary, and mathop fixes

---

src/omv/mt9v034.c

* Fix exception if the order of functions call is swapped (set_framesize before set_pixformat)
* The order of functions shouldn't matter, if necessary this check should be done in snapshot.
* This fixes issue #444

Fix MT set_framesize.

---

src/omv/sensor.c

It's higher than 35... On the H7 it no longer looks so bad on startup.  Tested the M7 and M4 too.

Make default jpeg res not so terrible.

---

src/omv/img/apriltag.c

These bounds checks were incorrect if sourceX/Y rounds up. In this situation, the unrounded source will be smaller than the limit by a factional amount (C will elevate the int bounds to a float for comparison), but the post-rounded version will equal the limit.
E.g.,
sourceX = 10.5
img->w = 11 (i.e., valid indices are [0-10])
sourceX2 = 11, which is invalid memory

Avoid invalid mem access by validating post-rounded indices

---

ml/haarcascade/cascade_convert.py

* Using open "w" instead of "wb" causes the script to fail on Windows.

Fix cascade converter script Windows bug.

---

src/omv/lepton.c

The FLIR Lepton 3.5 sometimes doesn't startup. Our previous code just waited forever. The new code now will timeout but also will try to recover the FLIR Lepton 3.5 if possible if the video doesn't start in a timely manner.

Add timeout and crash receovery code.

---

src/omv/fb_alloc.c
src/omv/py/py_fir.c
src/omv/py/py_image.c
src/omv/py/py_lcd.c
src/omv/py/py_sensor.c
src/omv/py/py_tv.c

This fix creates a flag that prevents fb_alloc_free_till_mark() from
doing anything unless there was a previous fb_alloc_mark(). Once
fb_alloc_free_till_mark() is called it will no longer do anything until
there's another fb_alloc_mark().
This means that if an exception is triggered while in code that
previously did fb_alloc_mark() the stack will be cleaned up.
If the fb_alloc_mark() method is not called then the stack will not be
cleaned up and that memory fb_alloc()'ed will remain until a soft reset.
All OpenMV Cam library code is designed to fb_alloc_mark() before using
the fb stack and then fb_alloc_free_till_mark() when complete. However,
in the case of py_sensor_alloc_extra_fb() it doesn't mark first such
that the RAM it allocates stays across exceptions and is only free'd via …

Fix exceptions from freeing fb_alloc_mark

---

src/omv/nn/nn.c
src/omv/nn/nn.h

* Fixes issue #491
* Since enums are now short, make sure NN layer types are 4 bytes.

Fix NN enum sizes.

---

scripts/examples/18-MAVLink/mavlink_opticalflow.py

This PR makes a few small but important changes to the example script for sending optical flow message (via mavlink) to mavlink enabled flight controllers like those running [ArduPilot](http://ardupilot.org/).
The fixes are:
- fix to the direction (one axis was reversed) and scaling (the values were 3 to 5 times too small) of the flow sensor values being sent
- always send packets regardless of whether the sensor has seen much movement.  This is important because the flight controller side performs best with regular updates.  One reason is that without messages it can't determine if the sensor has failed or not (i.e. does no message mean the sensor has failed or that it can't see anyway?).  Also the Extended Kalman Filter does best with regular samples.
- added a green flashing LED which …

Fixup MAVLink optical flow script after testing with ArduPilot

---

src/omv/py/py_winc.c

* MP code doesn't check for NULL ioctl.

WINC: Set ioctl function.

---

src/cmsis/src/st/system_stm32fxxx.c
src/omv/boards/OPENMV4/omv_boardconfig.h

* According to ST, the H7 can actually run at 480MHz.

Set H7 frequency to 480MHz.

---

src/omv/img/imlib.h

COLOR_YUV_TO_RGB565 was broken due to the missing parens.

Fixed missing parens

---

src/Makefile

when compiling a frozen module, include `frozen_mpy.o` object to prevent error 
```
undefined reference to 'mp_frozen_mpy_names'
undefined reference to 'mp_frozen_mpy_names'
undefined reference to 'mp_frozen_mpy_content'
undefined reference to 'mp_qstr_frozen_const_pool'
```
reference issues #456

include frozen_mpy.o when compiling a frozen module.

---

tools/pyopenmv_multi.py

Instead of a single global '__serial', this version has a list of them. Another list has just the port name. The two lists are parallel in that the index of one corresponds to the index of the other. So, any serial can be accessed by  searching for the port name.
I have been using this version for combining multiple cameras for OpenCV processing. Perhaps others will find it useful.

pyopenmv extended to support multiple cameras

---

src/omv/sensor.c

* In JPEG mode the cacheable framebuffer memory is used directly by the DMA, instead of the line buffer.
Cache maintenance must be performed before the CPU accesses the framebuffer memory.

Fix cache maintenance issue in JPEG mode.

---

src/omv/boards/OPENMV4R/omv_boardconfig.h
src/omv/stm32fxxx.ld.S

* Allow FFS, JPEG and VOSPI buffers to be moved to any dedicated region with an offset.

Add memory offsets for FFS, JPEG and VOSPI buffers.

---

src/omv/img/apriltag.c
src/omv/img/dmtx.c
src/omv/img/lsd.c

* The root cause for this issue is "define double float". printf functions promote
float to double, which is #define'd as float causing the implicit conversion error.
* Replaced all double with float, and DBL_MIN and FLT_MIN etc... and added explicit
cast to double in printf functions.

Fix printf issue in apriltags, dmtx and lsd.

---

src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4R/imlib_config.h
src/omv/img/apriltag.c

Not neccessarily needed and takes 2-4x more processing power. If FPS is
not a concern enable it.

Disable 8-way connectivity

---

scripts/examples/14-WiFi-Shield/mjpeg_streamer.py
src/omv/py/py_winc.c
src/winc1500/include/winc.h
src/winc1500/src/winc.c

* Setting timeout to 0 (from MicroPython) makes the socket blocking instead of non-blocking.
* Sockets were closed on recv/recvfrom timeout.

WINC1500: Fix timeout bugs.

---

src/omv/img/bmp.c

Tested and works. All BMP file types should work now. Found by Tobias.

Fix bmp file reading for all formats

---

src/omv/fb_alloc.c

Found this bug because the tensorflow code does fb_alloc all and then frees it and then allocs again. Should not have missed this before.

Move flag setting inside the curly braces.

---

src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4R/imlib_config.h

* Disable YUV tables for H7 cameras to temporarily save FLASH.
* Since H7 cameras have and use the HW JPEG encoder the side effects are minimal.

Disable YUV table for OMV4 and OMV4R.

---

scripts/examples/14-WiFi-Shield/http_client.py
scripts/examples/14-WiFi-Shield/http_client_ssl.py
src/Makefile
src/winc1500/include/winc.h
src/winc1500/src/winc.c

Fix recv() bug introduced after WINC1500 host driver/firmware updates.
Enable modussl via mbedtls.
Update HTTP client example.
Add HTTPS client example.
Fixes #348

Wifi updates

---

src/omv/py/py_tf.c
src/omv/py/qstrdefsomv.h

With the segment method you can execute the CNN on an image and get the list of images back (per channel) that represent the CNN output mask.
This is cool because for DIY robocars we can make a really light-weight CNN that segments the image between line and no-line and gives back an image you can then call get_regression() on.

Add support for image segmentation.

---

scripts/examples/02-Board-Control/can.py

CAN_DEFAULT_PRESCALER is 32. Tested with PCAN Dongle

Default CAN baudrate is 125 kbps

---

src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4R/omv_boardconfig.h
src/omv/main.c
src/omv/wifidbg.c

* OMV3 is running out of memory because of tf global variables.

Disable WiFi debug for older boards (especially OMV3).

---

src/omv/img/jpeg.c

For grayscale and RGB565 JPEG encoding (used to get camera output), the original code  was not optimal. The grayscale code was sped up slightly, but the change isn't very visible because the communication and receiving end of the pipeline are more of a limiting factor.
The RGB565 code was sped up enough to see a change in the max frame rate. On my test rig, the QVGA RGB565 frame rate (as visible in the IDE running the hello world sample) went from 15.6 FPS to 20.4 FPS with this change. Additional speed can be achieved with some SIMD optimization (I'll do on my next pass).

Optimized JPEG MCU capture

---

src/omv/img/filter.c
src/omv/img/imlib.c
src/omv/img/jpeg.c
src/winc1500/src/winc.c

This set of changes speeds up the histeq (equalization by histogram) of RGB565 images and the JPEG compression of binary (1-bpp) images.

histeq and JPEG binary speedup

---

src/omv/usbdbg.c
tools/pyopenmv.py
tools/pyopenmv_multi.py

* All commands now send a 6-bytes header followed by the payload in a separate packet.

Update debugging protocol to be more consistent.

---

src/omv/img/lsd.c

The last round of optimizations disabled a conditional statement which was necessary.

Fixed find_line_segments() regression

---

src/omv/sensor.c

* Add OMV_XCLK_OSC to use when an external osc is used.

Allow sensor clock to not be defined.

---

src/omv/py/py_sensor.c

Stops auto rotation when +-10 degrees from 90 (face down) and 270 (face up). This has to be done because the roll is unstable when at these pitches.

Disable rotation when pitch is wrong

---

src/omv/py/py_tf.c

Discovered this during a demo. It doesn't break the normal mode but causes the normal mode to leak fb memory and breaks the load_to_fb version.

Fix bug with TF load_to_fb

---

src/omv/img/imlib.c

I removed the pixel macros from the lens correction loop because they're slower than direct pointer access. The "put" macros calculate the destination address every pixel, while pointer access uses the current row pointer.

Lens correction speedup

---

src/omv/img/filter.c

This change speeds up the mean filter for all bit depths. Large filter sizes don't affect performance as much due to the change I made to the algorithm.

Speed up of mean filter

---

src/omv/ov5640.c
src/omv/sensor.c

The OV5640 sensor produces up to a 2560x1944 image. At the highest res, the dma line copy code wasn't keeping up with the output of the sensor. I optimized this by improving the memory throughput. The Cortex-M7 has a 32-bit memory bus, so the fastest movement of memory is by reading and writing 32-bits at a time on aligned addresses. The memcpy() function already has code which detects if the source and destination addresses are 32-bit aligned, so most of the work was passed to memcpy().

optimized sensor copy to allow ful res capture

---

src/omv/py/py_image.c

Do .bytearray() to get an object pointing to the image bytes which
allows you to manipulate the RAW data of an image.
This feature allows you to transfer images over a wire and load them back into memory again. Once cast to a bytearray() you can slice 16KB byte chunks for example from an image and transfer them one at a time. Additionally, you can also assign slices of data to an image. You can use alloc_extra_fb() to create a space to store an extra image.
...
That said, I'm just using this for easily transferring large jpeg images.

Add raw data RD/WR access to the image object.

---

src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/py/py_image.c

1/ image.draw_image fails to apply alpha correctly on anything other than grayscale images, this fixes that.
2/ it also adds a new parameter to image.draw_image, color_palette. The palette is used when the other image is a grayscale image such as thermographic when you want an e.g. rainbow palette to be applied. This saves allocating extra memory for a separate buffer for the color thermograph then using a function such as image.blend to blend to the camera. If you pass a color_palette and the other image is not grayscale an exception is raised.

Fix DrawImage with alpha and add color palettes for grayscale

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/jpeg.c

This change speeds up color JPEG encoding (as measured in the IDE) between 10 and 15% over the previous version. VGA color max frame rate is now around 15 FPS in good lighting with a simple scene (30+ FPS without the IDE).

sped up jpeg encoder by adding a direct bayer-to-ycbcr path

---

scripts/examples/03-Drawing/image_drawing_advanced.py
src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/py/py_image.c

Changed draw image to use row operations improving performance by a factor of at least 4.
Changed draw image to use SMUAD for alpha blending instead of normal c code.
Changed draw image to allow negative scales to reverse images.
This might require a bit of effort to approve.
I also wanted to change the mask lookup to use row pointers too, but there is no requirement for masks to be the same size as the other image, it's just a suggestion in the docs.
I've tested this with a python script that will be attached.

draw_image performance and negative scaling.

---

src/omv/py/py_winc.c
src/winc1500/src/winc.c

Polling for the async response was ruinning WiFi and UDP performance.
This fix removes that polling while not breaking anything. It has been
stress tested while streaming over an hour of wifi video data using the
new RPC scripts.

Improve WiFi performance by 20X

---

src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/py/py_omv.c
src/omv/py/qstrdefsomv.h

Allow user control to disable the frame buffer. Necessary for high manual
jpeg image streaming.

Add disable_fb.

---

src/winc1500/src/winc.c

Tested and works.
Yes, you can execute close during the callback. It works fine.

Close sockets that have errors.

---

src/omv/img/imlib.c
src/omv/img/jpeg.c

The 3.6.2 firmware included a bug in the VGA JPEG capture which was due to a left edge boundary check. It only affected JPEG capture (visible in the IDE and saving to file) and not normal image use. This corrects the problem and does not affect the speed.

Fix for left edge Bayer to ycbcr bug

---

udev/50-openmv.rules

OpenMV IDE installs udev for folks currently. This isn't needed anymore.

Remove udev

---

src/lepton/src/LEPTON_I2C_Service.c
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/cambus.c
src/omv/cambus.h
src/omv/hm01b0.c
src/omv/lepton.c
src/omv/mt9v034.c
src/omv/ov2640.c
src/omv/ov5640.c
src/omv/ov7690.c
src/omv/ov7725.c
src/omv/ov9650.c
src/omv/sensor.c
src/omv/sensor.h

Tested with the following cams/sensors:
* OPENMV3/OV7725
* OPENMV4 OV2640, OV5640, OV7725, MT9V034 and all FLIR sensors.
* OPENMV4P/OV5640

Make cambus functions accept I2C handle.

---

scripts/examples/03-Drawing/image_drawing_advanced.py
src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/py/py_helper.c
src/omv/py/py_helper.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

There's an extra parameter on draw_image called hint.
It can take the values:
image.BILINEAR_INTERPOLATION which smooths images
image.IMAGE_CENTER which makes x,y coordinates relative to the center of the image.
e.g. hint=image.BILINEAR_INTERPOLATION | image.IMAGE_CENTER 
There's an extra parameter on draw_image called alpha_pallete
This works the same as color palette except it creates an alpha value based on the grayscale image.
This is very useful for combining thermal images to sensor when you want some areas to be clear with smoothed edges.

draw_image bi-linear interpolation, alpha palettes, and center_image

---

src/omv/cambus.c
src/omv/cambus.h
src/omv/stm32fxxx_hal_msp.c

* Add general call support to cambus.
* Enable IRQs in cambus read/write_bytes
* Increase FIR I2C GPIO speed.
* Enable I2C FMP on cams that support it.

FIR I2C Improvements

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

Most cheap lenses are not aligned to their sensors, this creates issues when overlaying two images as they don't quite align correctly.  We can fix this using a rotation_corr with a translate, or creating a new image and drawing it with offset, but this is slow.
I've added x_corr and y_corr to imlib_lens_corr.
The values represent a percentage/100 (0->1) x/y offset to apply before performing the lens correction.
As of example my H7's camera offset is over 5%.

Add correction to imlib lens corr + optimise

---

src/omv/img/jpeg.c

For the hardware JPEG encoder, it wants YUV input and is happy with Y values of 0x00 and 0xff to be min and max. The software JPEG encoder wants YCbCr input which wants min/max values of Y to be 0x80 and 0x7F. I fixed the output for that.

fixed software JPEG encode of 1-bpp images

---

src/omv/py/py_tf.c

Thought this was more complex than actually.
Floating point is just 0->1. So, scaling is just 0-255. It's not more complex with -1:+1 which has issues for mapping to 8-bits.

Fixed Floating Point Scaling in TensorFlow code

---

src/omv/ov5640.c
src/omv/sensor.c
src/sthal/f4/src/stm32f4xx_hal_dcmi.c
src/sthal/f7/src/stm32f7xx_hal_dcmi.c
src/sthal/h7/src/stm32h7xx_hal_dcmi.c

This PR maxes out the speed of the sensor driver and gives us the max FPS each sensor module is able to run at. In particular, the H7 with the OV7725 out of the box in daylight will hit 150 FPS at QVGA. Readout control on the OV5640 allows you to hit 170 FPS.
It's been tested on:
OpenMV Cam H7+ => OV7725 => GRAYSCALE/RGB565/BAYER all supported resolutions work
OpenMV Cam H7+ => MT9V034 => GRAYSCALE all supported resolutions work
OpenMV Cam H7+ => LEPTON => GRAYSCALE/RGB565 all supported resolutions work
OpenMV Cam H7+ => OV5640 => GRAYSCALE/RGB565/BAYER/JPEG all supported resolutions work
OpenMV Cam H7+ => OV2640 => GRAYSCALE/RGB565/BAYER/JPEG all supported resolutions work
OpenMV Cam H7 => OV7725 => GRAYSCALE/RGB565/BAYER all supported resolutions work
OpenMV Cam H7 => MT9V034 => …

Optimized Sensor Driver for Double FPS

---

src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/ov2640.c
src/omv/ov7725.c
src/omv/ov9650.c
src/omv/py/py_sensor.c
src/omv/sensor.c

This commit fixes most of the frame buffer overflow issues that can cause memory corruption. In particular, this commit is needed so that when you use a camera sensor on a board not designed for it you do not get memory corruption because of various buffers being too small. The error checks will now trigger to prevent issues before hand. This is what is fixed:
* Made OMV_LINE_BUF_SIZE an int so it can be used in code.
* Removed sleeps on the OV2640.
* Protect max resolution on the OV2640/OV7725.
* Renamed the sensor timeout error to something more generic now that sensor.snapshot throws more errors.
* Added mode error checks to set_pixformat/set_framesize/set_windowing.
* Made it policy for the same offsets to be used for BAYER/GRAYSCALE/RGB565 so that when switching between pixformats …

Fix buffer overflow issues

---

scripts/examples/36-Web-Servers/rtsp_video_server.py
scripts/libraries/rtsp.py

This adds a new rtsp server library class to the firmware to allow folks to stream MJPEG video from their OpenMV Cam.
In particular, you can open rtsp streams in OpenCV to easily consume OpenMV output data. Also, VLC can open the streams too.
Note that VLC doesn't like the JPEGs produced by our STM32H7 compression hardware (it might require YUV 422 - we do YUV 444 JPEGs). It has no problem with the JPEGs produced by the OV5640. Not sure why VLC isn't able to handle this however as it can decode the same JPEGs in an MJPEG video.
Further study of what JPEG images are supported so be looked into and possibly editing out default jpeg format if necessary.

Add rtsp support

---

src/omv/img/jpeg.c
src/omv/sensor.c

* Removes trailing 0 bytes from JPEG data from the internal JPEG compressor on the H7.
* Removes thousands of trailing 0 bytes from JPEG data from OV5640/2640 cameras.
The software JPEG compressor was checked and does not add extra data to the jpeg file.

Cleanup trailing data on jpeg images

---

src/omv/mt9v034.c

mt9v034 has a lot of unimplemented functions that just return 0. Some can't be implemented (get_rgb_gain), maybe they are placeholders to be implemented (or if the color sensor is supported), if so they should return -1 not 0;

Cleanup mt9v034 driver.

---

src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h

Fixed buffer size on the 2/3 and reduced the frame buffer to 20M on Plus.
OMV_RAW_BUF_SIZE doesn't prevent fb alloc from running into it's area currently. With the coming double buffer commit fb alloc will not easily walk into the frame buffer area anymore and will respect the buffer size except for cases where it known it can (i.e. in single buffer mode - in double buffer mode it will not re-use frame buffer memory).

Fixed buffer size on the 2/3 and reduced the frame buffer to 20M on Plus.

---

src/omv/framebuffer.c
src/omv/framebuffer.h

Add functions to access the main framebuffer pointer and set w, h and bpp. I didn't make the function accept an image to decouple it from imlib.

Add accessor functions to framebuffer.

---

src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/py/py_fir.c
src/omv/py/py_gif.c
src/omv/py/py_image.c
src/omv/py/py_sensor.c

This is a redo of PR #831 using the new framebuffer some more. Now nothing in omv/py/* uses MAIN_FB anymore, hopefully all the other code will be updated to use the new functions.
Additionally this code decouples framebuffer from MicroPython code (no exceptions in framebuffer.c) mostly with the exception of mpprint, and from imlib so it makes the new functions available to all the code that don't need these dependencies.

Update fb access

---

src/omv/fb_alloc.c
src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/py/py_fir.c
src/omv/py/py_sensor.c
src/omv/usbdbg.c

Trying to remove MAIN_FB() stuff from being everywhere. Instead, it's inside of access functions.

Made code that uses the framebuffer more readable

---

src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/PORTENTA/imlib_config.h
src/sthal/f7/Makefile
src/sthal/f7/src/stm32f7xx_hal_crc.c
src/sthal/h7/Makefile
src/stm32cubeai/Makefile

* Disable built-in AI libraries if CUBE-AI is defined.
* Remove the hard-coded crc drivers from cubeai Makefile.
* Reduce the heap of all H7 targets to fix the build.
* Fixes #814

Fix CUBE-AI build

---

src/omv/fb_alloc.c
src/omv/fb_alloc.h
src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/lepton.c
src/omv/sensor.c

This commit makes sure that when trying to figure out how much space to give a frame in the frame buffer the amount already on the fb_alloc stack is respected versus being overrun.
As an optimization, the amount of bytes allocated for the frame buffer is capped to not be too big.

Frame buffer respects fb alloc now

---

src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/main.c
src/omv/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

* Set estack to the end of the stack region, instead of the end of the whole memory.
* Use sstack and estack variables to set stack top and calculate the stack size in main.
* Allow stack memory to be configured in board files.

Allow stack to be placed in a separate memory.

---

src/Makefile

* In addition to the CFLAGS passed to control modules mpconfigport.h, the
Makefile needs its own arguments to enable/disable built-in modules.
* Fix the way arguments are passed to MicroPython's Makefile, so that it's
possible to enable/disable compiling code from the top level OpenMV board Makefile.

Fix Makefile arguments passed to MicroPython.

---

src/omv/sensor.c

this added line of code is required because code in stm32f7xx_hal_tim.c uses this field and it is not initialized so it can break intended behaviour

added initialization for required field

---

README.md
tools/rpc/README.md
tools/rpc/rpc.py
tools/rpc/rpc_popular_features_as_the_controller_device_example.py

* Switch to table based CRC16 in the RPC library.
* Add CAN support.
* Add UART Support.
* Update documentation.

Add UART and CAN support to desktop interface library

---

src/omv/cambus.c
src/omv/main.c
src/omv/py/py_sensor.c
src/omv/sensor.c
src/omv/sensor.h
src/omv/usbdbg.c

* The firmware will keep running with no image sensor attached.
* The self-tests will still fail to detect production issues.
* If no sensor is detected, usbdbg will return 0xFF for get sensor ID.
* Probably need to disable self-tests for Portenta.

Support boards without image sensors.

---

src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/main.c

Note, there's no check for the PORTENTA or OPENMVPURETHERMAL. These don't hit our factory, so, they don't need the check.

Specify address per board of swd frame buffer test address

---

src/omv/cambus.c

* Fixes occasional failure when sensor I2C is shared with micropython.

Deinit I2C bus before re-initializing.

---

src/omv/main.c

* LWIP and CYW43 init functions should be called only once at startup.

Fix WiFi initialization functions in main.

---

src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMVPURETHERMAL/imlib_config.h
src/omv/img/apriltag.c
src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/py/py_image.c

In an effort to make sure new code is as fast as possible I am not taking any shortcuts anymore and wasting processor time...
As such, I've added a new mode to draw_row for drawing on a canvas with a black background. If the black_background flag is set draw row switches to faster versions of it's drawing methods that have alpha blending support which will assume the background pixels are black by default.
This saves having to do a memset per frame buffer update before drawing an image on the frame buffer. Additionally, for the LCD interface it's possible to tell the display driver which areas were actually drawn causing anything outside that area to be black. This means you can draw on a 1080p canvas without having to suffer the cost of a memset on 4MB of pixels per frame draw.
Second, …

Modify draw row for LCD screen use

---

src/omv/fb_alloc.c
src/omv/fb_alloc.h
src/omv/img/blob.c
src/omv/py/py_sensor.c
src/omv/py/py_tf.c

I noticed a bug with load_to_fb=True for tesnorflow where exceptions not in our code path caused the allocated buffers to be popped. This commit fixes that issue. The previous marks semaphore was not strong enough to handle how I'd like to allocate buffers in different situations. This new method is superior.
Other ways this is helpful... imagine if you want to allocate 3 buffers for triple buffering the LCD output. Each is a huge fb_alloc(). One may fail in the alloc loop. If a failure happens you want all previous ones freed. Sure, our code does that now. After all succeed you want to lock them all to prevent them from being popped by any exceptions. This code makes that happen now.
But, in particular, TensorFlow has a rather complex multi-alloc and then pop usage case before it wants …

Fix fballoc for complex allocations

---

src/omv/boards/PORTENTA/omv_boardconfig.h

LCD controller needs more space for static vars.

Reduce heap to fit more static driver vars

---

src/omv/img/draw.c
src/omv/img/imlib.h

Allows code to figure out the area being draw on or not. Useful for optimizing lcd display output.

Add draw_image extent calculator

---

src/omv/main.c

* Make test more useful if cache is enabled.
* Make test call __fatal_error with more verbose messages.

Update SDRAM test.

---

src/omv/main.c

* Make SDRAM test cache-aware.
* Add flag to control SDRAM test.
* Re-enable test for all boards.

SDRAM test updates.

---

scripts/examples/03-Drawing/copy2fb.py
src/omv/py/py_image.c

* With this fix the frame buffer will be updated instantly after loading or creating
new images with the copy_to_fb flag set to true.
* There's no need to flush the framebuffer after loading or creating images anymore,
however the sensor (or image) flush() still needs to be called after drawing to see the updates.

Update JPEG frame buffer after loading/creating images.

---

src/omv/py/py_tf.c
src/omv/py/py_tf.h

* Allow reusing models loaded with py_tf.
* Allow calling libtf_invoke without implementing the log buffer code.

Export part of py_tf API to the rest of the modules.

---

src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMVPURETHERMAL/imlib_config.h
src/omv/boards/PORTENTA/imlib_config.h
src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/main.c
src/omv/stm32fxxx_hal_msp.c

Enables DMA2D for GRAYSCALE drawing on RGB565 images.
Enables DMA2D for RGB565 alpha blending on RGB565 images.
Adds hooks for using DMA2D in future drawing operations.
For BICUBIC GRAYSCALE draw on RGB565 it's about 20% faster than the processor for small images. The speed gain will grow as it offloads the processor from the alpha blending work.

Enable DMA2D for draw row

---

src/uvc/src/usbd_conf.c

* Note ep0_mps is not used anywhere, but we keep it for now.

Fix ep0_mps on the M4.

---

src/Makefile

* Fixes link error in newer HALs.

Link libgcc to bootloader and UVC.

---

src/omv/imlib/jpeg.c
src/omv/modules/py_clock.c
src/omv/modules/py_image.c
src/omv/modules/py_sensor.c
src/omv/sensors/hm01b0.c
src/omv/sensors/lepton.c
src/omv/sensors/mt9v034.c
src/omv/sensors/ov2640.c
src/omv/sensors/ov5640.c
src/omv/sensors/ov7690.c
src/omv/sensors/ov7725.c
src/omv/sensors/ov9650.c
src/uvc/src/main.c

* Allow building sensor drivers with different ports.

Use MP HAL delay/ticks instead of systick.

---

src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMVPT/imlib_config.h
src/omv/boards/PORTENTA/imlib_config.h
src/omv/common/ff_wrapper.c
src/omv/imlib/bmp.c
src/omv/imlib/fft.c
src/omv/imlib/gif.c
src/omv/imlib/haar.c
src/omv/imlib/imlib.c
src/omv/imlib/jpeg.c
src/omv/imlib/mjpeg.c
src/omv/imlib/orb.c
src/omv/imlib/ppm.c
src/omv/modules/py_gif.c
src/omv/modules/py_image.c
src/omv/modules/py_mjpeg.c
src/omv/modules/py_tf.c
src/omv/ports/stm32/main.c
src/omv/ports/stm32/usbdbg.c

* Images, models and descriptors I/O can be disabled with imlib flag.
* Image creation in memory still works if image I/O is disabled.
* TF and Haar can still load built-in models/cascades if image I/O is disabled.

Allow building the image library and modules without a filesystem.

---

scripts/examples/OpenMV/12-Thermopile-Shield/AMG8833_camera.py
scripts/examples/OpenMV/12-Thermopile-Shield/MLX90621_camera.py
scripts/examples/OpenMV/12-Thermopile-Shield/MLX90640_camera.py
src/omv/imlib/fmath.c
src/omv/imlib/fmath.h
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/modules/py_fir.c

* Adds hmirror, vflip, and transpose to read_ir.
* Improves memory allocation of read_ir such that it's not trashing the heap anymore.
* Peak memory usage reduced.
* Refactored code to improve things.
* Made snapshot() support all the same args as read_ir/draw_ir with the ability to set custom output resolutions.
This PR significantly improves the performance of the FIR module by using tight'ish loops for all operations and it avoids copying IR arrays into the heap to MP land and then back into C land again.
All sensors are tested and working.

Modernize the FIR module to support optimized smooth scaling.

---

src/drivers/lepton/include/LEPTON_I2C_Service.h
src/drivers/lepton/src/LEPTON_I2C_Service.c
src/omv/sensors/lepton.c

For support of this module per user requests.
https://learn.sparkfun.com/tutorials/flir-lepton-hookup-guide/all
Tested and works with the FLIR Lepton.

Enable the lepton bus to be used on external pins

---

src/hal/stm32/f4/include/stm32f4xx_hal_conf.h
src/hal/stm32/f7/include/stm32f7xx_hal_conf.h
src/hal/stm32/h7/include/stm32h7xx_hal_conf.h
src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/stm32fxxx_hal_msp.c

* Enabled USE_HAL_SPI_REGISTER_CALLBACKS for the F4/F7/H7.
* Switch to using callbacks with the LCD module.
* Remove stm32xx code for the callback.

Use SPI Callbacks

---

src/omv/Makefile
src/omv/boards/NANO33/imlib_config.h
src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMVPT/imlib_config.h
src/omv/boards/PORTENTA/imlib_config.h
src/omv/modules/py_image.c
src/omv/modules/py_imageio.c
src/omv/modules/py_imageio.h
src/omv/modules/qstrdefsomv.h
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/stm32/omv_portconfig.mk

* This new module replaces the old ImageWriter and ImageReader and adds support for memory stream I/O.
* The API is more or less the same, with some minor changes.
Usage with file I/O:
```
stream = image.ImageIO("/stream.bin", "w") # Specify stream mode r or w
stream.read/write(image)   # checks for stream mode
stream.close()
```
Usage with memory I/O:
```
stream = image.ImageIO((width, height, bpp), n_frames) # Must specify the number of frames to pre-alloc.
stream.write(image)
stream.seek(0)
img = stream.read()
stream.close() # does nothing for now.
```

Add new ImageIO Type.

---

src/drivers/lepton/include/LEPTON_I2C_Protocol.h
src/drivers/lepton/include/LEPTON_I2C_Service.h
src/drivers/lepton/include/LEPTON_SDK.h
src/drivers/lepton/include/LEPTON_Types.h
src/drivers/lepton/src/LEPTON_I2C_Protocol.c
src/drivers/lepton/src/LEPTON_I2C_Service.c
src/drivers/lepton/src/LEPTON_SDK.c
src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/sensors/lepton.c

Tested on an OpenMV Cam H7 with both a Lepton on the camera bus and another on the external pins. Both work at the same time.
The previous code could not support both at the same time. This code can do that and saves a var.

Make lepton driver take cambus_t

---

src/omv/sensors/ov5640.c
src/omv/sensors/ov5640_regs.h

I realized why setting long exposure settings was only sort-of working, and had weird timings, and also failed frequently.
The PCLK calculations were simply not taking into account the changes I wrote into all the PLL registers via the hack you've suggested.
I added some additional register retrievals and calculated PCLK properly and now it's working soooo much better

ov5640 pclk calculation now uses current register values

---

src/omv/ports/stm32/modules/py_fir_lepton.c

Can't do 32-bit transfers to the SPI bus with the M4/M7. The SPI bus for them has only a 16-bit read/write register. So, this switches to 16-bit mode for DMA for them. I have confirmed the FLIR Lepton 1 works on the M4 and M7. The FLIR Lepton 3 didn't work on the M4 because of RAM issues. The Lepton 3 works on the M7.
Regarding the transfer length changing. On the H7 I have the SPI FIFO enabled in 2 data element mode which seems to halve the DMA transaction size. While this doesn't make that much sense on why that happens... I can confirm trying sizes *2 and /2 both don't work and cause issues. This is why the DMA length is unchanged. Only the transfer sizes.
Finally, M4/M7 have a higher target SPI clock speed to ensure they hit a clock divider that can read the image out fast enough …

Fix lepton driver on m4 and m7

---

scripts/libraries/lora.py

This enables compatibility with the MKRWAN firmware 1.2.1

Use 2 stop bits for LoRa UART

---

scripts/examples/Arduino/Portenta H7/39-LoRa/lora-example.py

Leaving it with the default timeout provides a more stable setup.

Remove join timeout from example

---

src/omv/modules/py_imageio.c

New files created don't have rgb565 byte reversal. Can read old files with this issue.

Update ImageIO version

---

src/omv/ports/stm32/modules/py_tv.c

If the user wants rgb channel extraction prefer grayscale.

Fix rgb_channel_extraction grayscale selection for TV

---

src/omv/ports/stm32/main.c

* Make sure to collect open lwip sockets otherwise it runs out of memory.
* This should be okay to add in general but will only enable for LWIP for now.

Call gc_sweep_all on soft-reset.

---

src/omv/ports/stm32/stm32fxxx.ld.S

* The stack pointer needs to be aligned to 8 bytes to conform with EABI, most of the boards are configured
to use ITCM for stack, which starts at 0 and are Not affected by the linker script alignment. This patch
fixes the issue with boards that use SRAM for stack which can get misaligned.

Fix linker script stack alignment for boards with SRAM stack.

---

src/omv/imlib/imlib.h
src/omv/imlib/jpeg.c
src/omv/ports/stm32/sensor.c

Puts bpp in a register versus a Read/Write/Modify per byte.

Speed up clearing trailing jpeg data

---

src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/imlib/jpeg.c
src/omv/ports/stm32/stm32fxxx_hal_msp.c

Speeds up JPEG in a minor way by keeping the core on between compresses.

Keep JPEG core on during script execution

---

src/omv/imlib/jpeg.c
src/omv/imlib/mjpeg.c
src/omv/modules/py_image.c

Moves fb_alloc_all() into jpeg compress so it has a chance to alloc memory itself before all RAM is used up for the output buffer.

Move fb_alloc_all into jpeg_compress

---

src/omv/ports/stm32/modules/py_lcd.c

Since the DMA system is talking in halfwords and not bytes this is 16/2=8.

Subtle max limit improvement for SPI LCD DMA.

---

src/omv/ports/stm32/modules/py_lcd.c

Some monitors don't care. Some do. This complies with the VESA CVT-RB Version 2 Standard.

Fix LCD output polarity

---

src/omv/boards/BORMIO/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h

This PR moves all the DMA buffers for H7 based OpenMV Cam's to SRAM3. This must be done to get the camera DMA off the D2-to-D1 AHB bus which can get busy and bottlenecked when another DMA stream is reading data from SDRAM/AXI_RAM over the D2-to-D1 AHB bus.
From this diagram above you can see that if any DMA master in the D2 domain wants to access SDRAM/AXI_RAM there's only one bus to the D1 domain to do so. This means that if the camera DMA needs to write to D1 domain and another DMA master is reading/writing SDRAM/AXI_RAM then the camera DMA has to wait. Note that there's no QoS for the AHB matrix in domain D2. So, there's no priority fix you can do here if multiple DMA masters need to use the same resource.
Because of the shallow depth of the camera DMA fifos you can't really delay that …

Move DMA buffers around to fix bus contention and save RAM

---

src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/ports/stm32/axiqos.h
src/omv/ports/stm32/stm32fxxx_hal_msp.c

This PR lets you set the AXI priority on the H7 per read/write channel.
For the OpenMV Pure Thermal and Portenta which have the ability to drive external displays this PR gives the LTDC the maximum priority ensuring that the display stays stable even when other masters are using it.
MDMA is give the next highest priority for future continuous camera image data capture reading from DMA2's line buffer and write back to the main frame buffer.
...
Note, while this PR helps with giving the LTDC controller better SDRAM bandwidth when other masters are using the bus it does not prevent other masters from switching SDRAM banks between LTDC access which lowers the SDRAM performance. So, you still can't actually display image data from the camera and have the processor manipulate it at 1080p@60Hz …

Add AXI QOS to make LCD output stable

---

src/omv/boards/BORMIO/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/ports/stm32/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

Moves the FIR Lepton DMA buffer from fb_alloc to the DMA buffer area.
...
On the STM32H7 this moves the DMA buffer into region D2 getting bus traffic off of the D2->D1 AHB bus.
...
We should change the DMA buffer defines to the necessary byte size. It will save RAM. Right now they are bigger than needed.

Use DMA buffer for FIR Lepton

---

src/omv/ports/stm32/modules/py_lcd.c

Missing zero was causing everything to use VCO wide.

Fix missing 0

---

src/omv/ports/stm32/sensor.c

If you kill a script in the middle of an I2C access to the camera you get a cambus lockup and have to reset the board.

Make cambus reinit standard for all boards

---

src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/ports/stm32/modules/py_lcd.c

TIM_ETRPRESCALER_DIV1 is not a valid prescaler value. It happens to be 0 which is what we want but it's not the right define.
Also, filled in other fields with defaults.

Filled out PWM TIMER init for FLIR/LCD

---

src/hal/cmsis/include/cmsis_gcc.h
src/omv/imlib/jpeg.c

This PR updates the JPEG code to use the new and tested get MCU front end developed for the H7 hardware JPEG compressor. The code is now shared between both software and hardware JPEG.
To ensure speed... I have ifdefs that switch things around in the output generated depending on if we are in software versus hardware mode.
I have tested this code on the H7/H7P/M7/M4.
I tested the hardware code for BINARY/GRAYSCALE/RGB565/BAYER.
I tested the software code for BINRARY/GRAYSCALE/RGB565/BAYER with 1x1, 2x1, and 2x2 sampling for each.
To support the NANO33 (Cortex-M3) I also added in intrinsics for non-m4/m7 processors. The code was tested and continued to work when using these. 
Additionally, I spent time trying to optimize the DCT methods in the software JPEG code. However, this did not …

Move software jpeg encoder front end to new SIMD MCU code

---

src/omv/ports/stm32/stm32fxxx_hal_msp.c

This makes sure the dedicated ADC channels that go to pads are not connected to their respective GPIO pin.

Make sure dedicated analog pads are isolated

---

scripts/examples/Arduino/Nano-33-BLE-Sense/00-Board/blinky.py

This PR changes the Nano 33 BLE blink example so that it creates the LED objects only once.

Create LED objects only once

---

src/omv/alloc/fb_alloc.c
src/omv/common/sensor.h
src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/modules/py_helper.c
src/omv/modules/py_sensor.c
src/omv/ports/nrf/main.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/main.c
src/omv/ports/stm32/sensor.c
src/omv/sensors/lepton.c
src/uvc/src/main.c

Adds support for allocating multiple frame buffers in the sensor driver to increase performance. To avoid changing all our scripts the firmware automatically chooses the highest performance buffering size given set_framesize() that fits in RAM that uses less than 1/2 of the framebuffer+fb_alloc space.
Users may increase or decrease the automatically allocated buffer count to suit their application. But, for most users they should automatically see a massive performance boost. 
Finally, if a user wants to record video they can do sensor.set_framebuffers(sensor.VIDEO_FIFO + N) where N is the number of extra frame buffers to allocate.
On the H7 Plus you can set this to 100 with QVGA easily and if you add a pyb.delay(100) to the main script you get cool slow mo effects.
Note: To avoid stale …

Double buffer mode working for all imaging modes

---

src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/ports/stm32/stm32fxxx_hal_msp.c

* SPI bus needs pull ups to soften edges.
* Need to force rst and pwdn low on startup to ensure that lepton is off in order to not disturb sensor_init() (OV5640 and lepton share an I2C bus).

Make FLIR Lepton init reliably on Pure Thermal

---

.travis.yml
src/drivers/winc1500/include/common/include/nm_common.h
src/drivers/winc1500/src/winc.c
src/omv/modules/py_clock.h
src/omv/ports/stm32/main.c
src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/sensors/lepton.c

This series of fixes allows the firmware to be built using gcc10, rather than gcc7 as used in your CI process.
I'm investigating using gcc10, as this is what CircuitPython uses (it appears that micropython uses 9-2019-q4-0ubuntu1 at the moment).
I have **NOT** tested this on hardware, and one change does modify behavior.
Please let me know if you'd prefer this be broken into multiple PRs, as it touches multiple parts of the project.

Fix build errors encountered with GNU Arm Embedded Toolchain 10-2020-q4-major

---

src/omv/common/mutex.c
src/omv/common/mutex.h
src/omv/common/usbdbg.c
src/omv/imlib/framebuffer.c

This fixes the frame buffer stutters with the new framebuffer speedup code by making readout locking more fair.
I examined priority locking and all sorts of other methods... and found myself writing race conditions. This method below is simple, effective, does the job, and doesn't have race conditions.
It works fine for fixing the issue of the IDE polling the frame buffer and nothing more. Note that IDE poll rate is 200 Hz. Faster than a screen refresh. So, this should always result in a smooth result on screen.

Make frame buffer readout locking more fair

---

src/omv/common/sensor.h
src/omv/modules/py_sensor.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c

This completes non-blocking snapshot support. The user has two methods to determine if a new frame is available.
1. They can poll the frame_available() method until it is True.
2. They can use set_frame_callback() to do something when a new frame is ready. Like schedule via micropython.schedule() a function that calls snapshot() to grab the frame and process it while keeping the main loop working on something else.
The user may choose whichever one is better for their application.

Add frame complete callback support

---

src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c

When testing cropping performance I realized that too many functions invalidate the frame buffer but don't send it to the PC first before that happens. This fixes these functions so you can call them in a loop with snapshot and still get display output.

Flush jpeg buffer when image is invalidated

---

src/omv/common/usbdbg.c
src/omv/common/usbdbg.h
src/omv/ports/nrf/main.c
src/omv/ports/stm32/main.c

Gives the IDE time to drain the jpeg frame buffer and text buffer after script stop.

Fix usbdbg flushing before script end

---

src/omv/ports/stm32/main.c

This should be fixed if you disable all servos for a custom board.

Disable servo when not used

---

src/omv/alloc/unaligned_memcpy.c
src/omv/common/mutex.c
src/omv/imlib/fmath.c

* CPU macro was not actually defined, which made the test pass on all MCUs.

Use pre-defined GCC macro to test for the architecture.

---

src/omv/modules/py_fir.c

* Allow AMG to work if CAMBUS_XFER_SUSPEND is not supported.

AMG init fix.

---

src/omv/common/sensor.h
src/omv/modules/py_sensor.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c

Adds the ability for the user to turn off automatic flushing of the frame buffer when it overflows. This allows the user to use the frame buffer as a long term storage fifo.

Add disable full flush logic

---

src/omv/common/sensor.h
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c
src/omv/sensors/hm01b0.c

You just need to do set_framerate(fps) and the camera will run at a frame rate that's below or equal to the number passed. If you pass 0 then the camera goes back to the maximum fps. The code does a fairly good job of going exactly at the fps you want.
Only an implementation is available for the STM32. The code is smart and doesn't do work after it decides to drop a frame. Processor time/MDMA time is not wasted moving an image that will be tossed. Power is still wasted however transferring the image from the DCMI hardware through DMA2 to SRAM. But, this should be minimal.
Finally, this code works in conjunction with lowering the sensor frame rate. So, for each sensor you can run it slower too and you will get the correct result. Tested this on the Portenta.

Add working frame rate control for all sensors to STM32

---

src/Makefile
src/drivers/pixart/Makefile
src/drivers/pixart/include/pixspi.h
src/drivers/pixart/src/pixspi.c
src/omv/Makefile
src/omv/boards/NANO33/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/common/sensor.h
src/omv/ports/stm32/omv_portconfig.mk
src/omv/ports/stm32/sensor.c
src/omv/sensors/paj6100.c
src/omv/sensors/paj6100.h
src/omv/sensors/paj6100_reg.h

1. Add a sensor implementation for PAJ6100.
2. Add a PixArt driver to manage SPI operations.
3. Improve sensor.c to fully support wide chip ID.

Support PixArt image sensor PAJ6100

---

src/omv/common/sensor.h
src/omv/ports/stm32/sensor.c

It's been an issue that we don't know the real xclk freq on boards. This allows you to get that so that the exposure time calculations in camera sensor driver code are actually correct.

Add method to get actual xclk freq

---

src/omv/ports/stm32/cambus.c

* This seems to only affect the H7.
* After a failed scan the bus can get stuck. Re-initializing the bus fixes it, but it seems disabling and re-enabling the bus is all that's needed.

Fix cambus getting stuck sometimes after failed scan.

---

src/omv/ports/rp2/cambus.c

* For sensor-less boards, lower the scan address space.

RP2: Optimize bus scanning.

---

.gitmodules
src/Makefile
src/omv/Makefile
src/omv/imlib/imlib.h
src/omv/modules/examplemodule.c
src/omv/modules/micropython.mk
src/omv/modules/py_fir.c
src/omv/modules/py_gif.c
src/omv/modules/py_image.c
src/omv/modules/py_mjpeg.c
src/omv/modules/py_omv.c
src/omv/modules/py_sensor.c
src/omv/modules/py_tf.c
src/omv/ports/nrf/modules/py_audio.c
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/modules/py_audio.c
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/rp2/omv_portconfig.mk
src/omv/ports/stm32/modules/py_audio.c
src/omv/ports/stm32/modules/py_buzzer.c
src/omv/ports/stm32/modules/py_cpufreq.c
src/omv/ports/stm32/modules/py_imu.c
src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_micro_speech.c
src/omv/ports/stm32/modules/py_tv.c
src/omv/ports/stm32/omv_portconfig.mk
src/stm32cubeai/cube.mk
src/stm32cubeai/py_st_nn.c

* Switch to using USER_C_MODULES to add OpenMV Python modules.
* It's no longer necessary to edit mpconfigport.h files to add a modules, or provide qstrs.
* To add a new module just place in omv/modules/example.c and rebuild, it will be picked up and included in the firmware.
* Similarly, port-specific modules can be add to  omv/ports/<port>/modules/example.c
* See example module: omv/modules/examplemodule.c
* NOTE: Took some extra time to fix stm32cubeai module, and test on stm32, nrf and rp2.

User c modules

---

src/omv/imlib/jpeg.c

The software JPEG encoder now has more efficient code to write the variable length codes to the output file.

speed up software JPEG encoding by about 10% with improved bit handling

---

src/omv/imlib/bayer.c
src/omv/imlib/draw.c
src/omv/imlib/gif.c
src/omv/imlib/imlib.h
src/omv/imlib/jpeg.c
src/omv/modules/py_image.c
src/omv/ports/stm32/modules/py_tv.c

* Adds support to debayer all possible bayer patterns (with SIMD support).
* Bayer pattern output by cameras can now be specified. Defaults to BGGR.
* Sets the MT9M114 bayer pattern default to match the camera sensor output.
* Crop will automatically adjust the bayer pattern as it moves.
Notes:
It's now possible to cleanup some of the older image sensor set_framesize code which adjusts the bayer pattern readout pixel start to align to bggr. This is no longer needed. These fixes can be done in another PR.
In the future if we want to support sensors with clear bayer patterns this can be done easily by just extending the possible bayer pattern enums.

Add full debayering support

---

src/omv/modules/py_tf.c

GCC doesn't feature a warning for this... maybe we should just change all loops to like this blog?
https://nachtimwald.com/2019/06/02/unsigned-count-down/
Anyway, this is not the issue that's crashing TensorFlow in the later release. I found this issue already.

Unsigned var in count down loop fixed

---

src/omv/ports/nrf/main.c
src/omv/ports/rp2/main.c
src/omv/ports/stm32/main.c

* Run frozen _boot.py if it exists (for early boot stuff).
* Allow freezing main.py and boot.py boot scripts.
* Give frozen boot scripts priority over filesystem boot scripts.
* Add frozen early boot script for OpenMV-PT.

Execute frozen boot scripts first before filesystem.

---

src/omv/ports/stm32/modules/py_fir_lepton.c

Processor crashes without this. It tries to call the python object as if it were a C method.
And expiry is set in the insert call. No need to set it.

Fix flag spec on timer

---

src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/common/sensor_utils.c
src/omv/sensors/ov5640.c
src/omv/sensors/ov5640.h

Sets the PCLK to 70 MHz and gets it working.

Add support for the OV5640 to the Arduino Portenta

---

src/omv/common/ini.c

Fixes warning preventing compile on GCC 9.2.1

Fix strncpy issue with new GCC

---

src/omv/imlib/imlib.c

It should not be negative when the imlib_rgb565_to_l function input is zero, e.g. y=0.137931f, fast_floorf(116 * 0.137931f) = 15.999996,  15.999996 - 16 < 0.

imlib: Fix imlib_rgb565_to_l output.

---

src/omv/imlib/draw.c
src/omv/imlib/imlib.h
src/omv/imlib/jpegd.c

* Fix MemManage fault on decoding odd images.
* Support decoding YCBCR to Grayscale.
* Support decoding Grayscale to RGB565.
* Minor formatting fixes.
* Use a single decompress function for all formats.
* Fixes #1550

imlib: Update JPEG decoder and fix memory issues.

---

src/omv/imlib/draw.c
src/omv/imlib/jpegd.c

* Add initial hardware JPEG decoder support.
* Detect and fail on progressive JPEGs for both SW/HW decoders.
* No support for decoding/conversion to a different colorspace.
* Decoder is disabled by default pending further testing.
Some numbers:
| Image Size | Format | Software |  Hardware | Diff % |
| ---------- | ------ | -------- | --------  | ------ |
| 640x480    | GRAY   | 11  ms   |  14  ms   |  +27%  |
| 320x240    | GRAY   | 4   ms   |  3   ms   |  -25%  |
| 320x240    | GRAY   | 4   ms   |  4   ms   |    0%  |
| 800x600    | GRAY   | 11  ms   |  21  ms   |  +90%  |
| 1280x960   | GRAY   | 67  ms   |  57  ms   |  -14%  |
| 320x240    | RGB565 | 12  ms   |  9   ms   |  -25%  |
| 698x500    | RGB565 | 47  ms   |  19  ms   |  -59%  |
| 692x500    | RGB565 | 41  ms   |  16  ms   | …

imlib: Add hardware JPEG decoder support.

---

src/omv/boards/OPENMVPT/omv_boardconfig.h

* Due to an issue with the crystal oscillator, the LSE can't be enabled without reworking the board, otherwise it will never start.

OPENMVPT: Disable RTC LSE clock source.

---

src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/omv_boardconfig.h
src/omv/boards/NANO33/omv_boardconfig.h
src/omv/boards/NICLAV/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PICO/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/imlib/framebuffer.c
src/omv/ports/nrf/nrf52xxx.ld.S
src/omv/ports/rp2/rp2.ld.S
src/omv/ports/stm32/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

* This old macro is very easy to miss when updating OMV_FB_SIZE.
* Use a linker script variable to get the raw framebuffer size.

boards: Remove raw FB size macro.

---

src/omv/imlib/draw.c
src/omv/ports/stm32/modules/py_lcd.c

Minor fixes for the LCD output on the OpenMV PT. These fixes don't appear to help any bugs. However, the previous code was not the best.

imlib: Fix py_lcd cache alignment and handling.

---

src/omv/boards/OPENMV4/omv_boardconfig.h

* This allows R2 to support a windowed frame at full resolution.

boards/OPENMV4: Increase frame line buffer size.

---

src/omv/ports/stm32/sensor.c

* Check if EXTI line is VSYNC line before clearing the
EXTI flag, to allow extint.c to handler other IRQS.

ports/stm32: Fix VSYNC EXTI handling.

---

src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/ports/nrf/sensor.c
src/omv/ports/rp2/sensor.c
src/omv/ports/stm32/sensor.c

All frame buffers need to be invalidated before starting MDMA frame capture. The invalidation is done as late as possible so that it does not get repeatedly done over and over again in the sensor_set_*() calls.
I added the method to all MCUs so that if we find we need to do anything else in the future it can be put inside this same method.
Fixes  #1580

imlib: Fix black lines on first frame.

---

src/omv/common/usbdbg.c

* Fixes #1637 for good.
* Reset USB CDC buffers after disabling IRQs, when stopping scripts, to avoid overflows or blocking when printing IDE exception traceback, without losing the exception message.
@kwagyeman Please undo any IDE changes (unnecessary delays) related to that issue.
Also note, it's very likely that this function is useless, because USB IRQs are disabled when this is called:
```c
void usbdbg_wait_for_command(uint32_t timeout)
{
for (mp_uint_t ticks = mp_hal_ticks_ms(); ((mp_hal_ticks_ms() - ticks) < timeout) && (cmd != USBDBG_NONE); );
}
```

ports/stm32: Reset CDC buffers after disabling IRQs.

---

src/omv/common/usbdbg.c

* If USB IRQs are disabled the command will never finish.

usbdbg: Check USB IRQs when blocking on commands.

---

src/omv/ports/stm32/main.c

* usbdbg_wait_for_command could raise exception when scripts end uninterrupted.

ports/stm32: Fix unhandled exception in main.c.

---

src/omv/Makefile
src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/imlib_config.h
src/omv/boards/NANO33/imlib_config.h
src/omv/boards/NICLAV/imlib_config.h
src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMVPT/imlib_config.h
src/omv/boards/PICO/imlib_config.h
src/omv/boards/PORTENTA/imlib_config.h
src/omv/imlib/imlib.h
src/omv/imlib/stereo.c
src/omv/modules/py_image.c
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/omv_portconfig.mk

Adds support for this guys stereo camera: https://twitter.com/i/status/1533190596134703104
When called on an a double width image (and image with two camera outputs on either side) it will replace one of the images with the disparity:
`img.stereo_disparity(reversed=True, max_disparity=48, threshold=64)`
_reversed - False to compare left image to right, True to compare right image to left. If this is wrong the disparity map will be bonkers._
_max_disparity - Needs to be larger than the maximum pixel shift between images. Bad artifacts occur if too small. However, this value has a huge impact on the run-time of the algorithm._
_threshold - Making this larger short circuits testing all disparities per pixel. Making this large can cut the run-time down by a half or a third but at the cost of …

imlib: Add Support for Stereo Disparity for the Arduino Portenta.

---

src/omv/ports/stm32/stm32fxxx.ld.S

* If no special memory is defined for CYW43's firmware, add it
to the main firmware text section.

ports/stm32: Add CYW43 firmware blob to text section.

---

scripts/examples/07-Interface-Library/02-MAVLink/mavlink_apriltags_landing_target.py

This PR brings few changes to the MAVLINK apriltag landing target example after testing with [ArduPilot](http://ardupilot.org/) firmware while working on a project. The changes are:
- Remove the DISTANCE_SENSOR message stuff since it is not required and the distance can be sent within LANDING_TARGET message
- Update the sensor height and width as per the latest OV5650 sensor specifications
- The translation function doesn't seem to be right. The distance values received from the existing translation function are not near to the real values. After this fix, the distance values are quite accurate.
- Add a flashing led to indicate if the target is in sight. The LED flashes red when the camera can't see a target and green when the camera can see it.

scripts/examples: Fix MAVLINK apriltag example.

---

scripts/examples/07-Interface-Library/02-MAVLink/mavlink_apriltags_landing_target.py

I apologize for this little bug which was introduced in #1716.  I tested the script before submitting PR #1716 and it was all working fine. But then I discovered this bug while reading the code today. The script would work fine even without this fix but it is still very important to fix it.
Again, sorry for mistakenly introducing this one in that PR. Looking forward to getting it merged soon :)

scripts/examples: Fix typo in MAVLink Apriltag example.

---

src/omv/imlib/draw.c

The ROI information was not propagated through draw image for area/bilinear/bicubic scaling which caused it not to work.

imlib: Fix image scaler ROI support.

---

src/omv/ports/stm32/main.c

* Fixes #1734.
* On soft-reset all SPI instance are deinitialized, if IMU SPI bus is enabled in MicroPython it needs to be reinitialized.

ports/stm32: Re-initialize IMU after every soft-reset.

---

src/omv/ports/nrf/main.c

* Print missing soft reboot string.

ports/nrf: Minor fix for mpremote softreboot.

---

src/omv/ports/stm32/modules/py_winc.c

* Return a non-blocking error to MicroPython on socket timeouts, so the socket doesn't get closed.

drivers/WINC1500: Return a non-blocking error on socket timeout.

---

src/omv/ports/stm32/stm32fxxx_hal_msp.c

* DCMI pins were deinitialized with the DCMI.

ports/stm32: Fix DCMI pins deinit.

---

src/omv/boards/PORTENTA/omv_boardconfig.h

boards/PORTENTA: Override default MT sensor clock.

---

src/omv/ports/stm32/sensor.c

This function found freqs higher than requested before. Shouldn't have to fix the block freq on cameras per board now.

ports/stm32: Clock finds frequency under requested.

---

src/omv/boards/NICLAV/omv_boardconfig.h
src/omv/sensors/gc2145.c

Adds readout control to the NICLA so you can get a higher FPS: https://youtu.be/R5YjhI1aA5s
You can overclock the sensor in BAYER mode and double the FPS by setting the PLL at 0xF8 to 0x8B.
Also, fixes the image being upside down by default.

boards/NICLAV: Add readout control to driver and fix image orientation.

---

src/omv/ports/stm32/modules/py_winc.c

* Just in case user code calls functions on closed socket.

drivers/winc1500: Set NIC to NULL on closing sockets.

---

scripts/examples/08-RPC-Library/36-Web-Servers/rtsp_video_server_lan.py
scripts/examples/08-RPC-Library/36-Web-Servers/rtsp_video_server_wlan.py
scripts/libraries/rtsp.py

Fixes the RSTP driver for all OpenMV Cam boards using the winc (WiFi Shield). You can connect to the server multiple times and stream images without the camera crashing. Everything appears to work fine with the default UDP transport. With a TCP data transport it appears some issue happens in the shield firmware that will eventually cause the TCP socket to stop working (no errors are seen in wireshark though... the socket just stops). Anyway, on the socket being closed by the remote partner the camera will reset.
Luckily, the RTP protocol is almost always in UDP mode so the TCP support isn't important. However, It does show a bug in the firmware.
`/ffplay.exe rtsp://x.x.x.x -fflags nobuffer` - UDP transport (the default)
`/ffplay.exe -rtsp_transport tcp rtsp://x.x.x.x -fflags nobuffer` - …

scripts/libraries: Fix RSTP library for the winc.

---

src/omv/modules/py_image.c

Code accidentally updates the original object pointer when copy is passed with true.

imlib: Fix bug with copy argument updating original object.

---

src/omv/imlib/imlib.h
src/omv/imlib/mjpeg.c
src/omv/modules/py_mjpeg.c

This PR vastly improves the MJPEG code. It upgrades the MJPEG writer to have some of the same features as ImageIO. In particular, it adds sync() support to the object so that you can flush the image stream without having to the close the file. This PR does not however add support for appending/reading/seeking on MJPEG files. This will need to be added in a future PR as this requires much more effort to implement and was not a feature request by the customer.
Additionally, the add_frame() function was improved by integrating draw image support. So, now the function will automatically scale the image to the video size and you can apply all the draw_image color transformations as you like to the image on write.
Finally, life cycle management functions similar to ImageIO were added so you can …

imlib/mjpeg: Vastly improve MJPEG code.

---

src/omv/imlib/isp.c
src/omv/modules/py_image.c

Code is now as fast as possible for RGB565 and Grayscale. Didn't bother optimizing binary. Grayscale loops are re-used for BAYER/YUV image formats. Testing shows using this function has 0 frame rate impact at low resolutions.

imlib: Update gamma_corr to support bayer and yuv images.

---

src/lib/libtf/libtf.h
src/omv/modules/py_tf.c

Hi @iabdalkader, as discussed, I created a PR to extend the feature requested in https://github.com/openmv/openmv/issues/1751 and https://github.com/openmv/openmv/issues/1739 for 2D inputs
Updated binding for tf_regression to support the functionality of regression models for two-dimensional input and one-dimensional output for the function libtf_regression updated in libtf.cc(PR [here](https://github.com/openmv/tensorflow-lib/pull/13))
This PR aims to build on a previous [PR](https://github.com/openmv/openmv/pull/1762). Tagging it for reference.
Presently, it supports only int8, uint8, and float32 tflite models.
The following are details about how to use the model:
I have used two models to run:
1. Float32 Model with dynamic range quantization(or no quantization) 
The TFLite model can …

lib/libtf: Update libtf regression to support 2D input.

---

scripts/libraries/urequests.py

Your implementation of _urequests_ does not keep a reference to any resources in the `Response` object. So adding a `close()` function to the `Response` object (like the implementation in _micropython-lib_ has) is not possible. However, an unconditional call to `close()` on the socket object solved the problem for me.
fixes #1895

fix: added missing close() of socket object.

---

src/omv/common/tinyusb_debug.c

Mac sends 384 in high speed mode at max over USB-CDC. Never more.

mimxrt: Handle short packets for debug mode in TinyUSB.

---

src/omv/alloc/fb_alloc.c
src/omv/common/omv_common.h

Alloc alignment is needed for fixed DMA buffers. So, make this alignment macro appear in only one place.

drivers: Move alloc alignment macros to the common header.

---

src/omv/sensors/mt9v0xx.c

Reported to be incorrect per customer usage.
Please wait to merge this. Sending files to customer to reverify this commit is right. Will comment when they confirm.

sensors/mt9v0xx: Fix exposure calculation.

---

src/omv/ports/mimxrt/sensor.c

It chooses the highest clock freq for what is requested. If it can't find one it defaults to 3Mhz.

ports/imxrt/sensor: Fix sensor_set_xclk freq to accept any frequency.

---

src/omv/ports/stm32/modules/py_display.c

Not sure why I didn't do this originally. I think it's because I didn't realize `HAL_LTDC_Reload(&display.hltdc, LTDC_RELOAD_VERTICAL_BLANKING);` enables an interrupt.

ports/stm32: Improve LCD display update interrupt code.

---

src/omv/modules/py_image.c

Fixes https://github.com/openmv/openmv/issues/1884.
The system now throws an error versus returning a corrupted image.

imlib: Fix in-place scaling bug.

---

.github/workflows/changelog.json
src/omv/modules/py_sensor.c

Will not raise an exception if a sensor control is not implemented, this will allow sharing more scripts between different sensors.

modules/py_sensor: Print warning on missing sensor controls.

---

src/omv/sensors/mt9v0xx.c

Sometimes there's an easy button in life.
This dramatically improves the global shutter sensor image quality.

sensors/mt9v0xx: Enable row noise correction.

---

src/omv/modules/py_spi_display.c

Arguments were parsed/used in the wrong order.

modules/spi_display: Fix display args.

---

src/Makefile
src/omv/alloc/fb_alloc.c
src/omv/ports/mimxrt/omv_mpconfigport.h
src/omv/ports/nrf/omv_mpconfigport.h
src/omv/ports/rp2/omv_mpconfigport.h
src/omv/ports/stm32/omv_mpconfigport.h

- This can be set from a custom mpconfigport.h file to call fb_alloc_free or any other needed cleanup before an exception.
- The omvdummy stuff is no longer needed since a default empty hook is defined.

micropython: Add MICROPY_NLR_JUMP_HOOK.

---

src/drivers/winc1500/src/winc.c
src/omv/ports/stm32/modules/py_winc.c

The `WEP` security mode has been deprecated since firmware 19.7.6 the only two supported modes now are open and WPA.
Fixes #1849

drivers/winc: Fix AP mode.

---

src/omv/modules/py_tv.c

Fixes image corruption when using non-triple buffered mode on the TV and when you specify a sub rect to output from the full display resolution. Found when testing: https://github.com/openmv/openmv/pull/1992

modules/tv: Fix image corruption when specifying image rect.

---

src/omv/ports/mimxrt/main.c

Fixes: https://forums.openmv.io/t/menu-save-open-script-in-openmv-cam-as-main-py-disabled/8967/2

ports/mimxrt: Add .openmv_disk file.

---

src/omv/modules/py_display.c
src/omv/modules/py_fir.c
src/omv/modules/py_helper.c
src/omv/modules/py_helper.h
src/omv/modules/py_tof.c
src/omv/modules/py_tv.c

Having scale turn into a size if you pass an int is too dangerous. Just realized this after going through examples. This makes the behavior scaling and nothing else.

modules: Make int/floating image scaling behavior the same.

---

scripts/examples/01-Camera/06-Time-of-Flight/tof_camera.py
scripts/examples/50-Arduino-Boards/Nano-33-BLE-Sense/53-Thermal/thermal_camera.py
scripts/examples/50-Arduino-Boards/Nano-RP2040/53-Thermal/thermal_camera.py
scripts/examples/50-OpenMV-Boards/54-Thermopile-Shield/thermal_camera.py
scripts/examples/50-OpenMV-Boards/54-Thermopile-Shield/thermal_overlay.py
scripts/examples/50-OpenMV-Boards/54-Thermopile-Shield/thermal_overlay_lcd.py

Having to pass floats for the scale here to avoid issues made me realize we have to drop the size feature on scale being an int. See: https://github.com/openmv/openmv/pull/2028

scripts/examples: Update thermal scripts for new refectored API.

---

src/Makefile
src/omv/ports/rp2/omv_portconfig.cmake

ports/All: Add support for passing variables to manifest files.

---

src/omv/modules/py_tf.c

Non-square image support has not been working for a long time. This forum post pointed out the issue: https://forums.openmv.io/t/edge-impulse-result-wrong-on-openmv-h7-plus/8968/3.
Code is now updated to use the new draw image scaling and centering logic. This applies for classification and segmentation/detect.
Then segmentation has been updated to locate the final result in the right location given all the scaling and cropping going on when your image aspect ratio does not match the CNN aspect ratio.

modules/py_tf: Fix non-square image support.

---

src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h

Enable OV5640 for GIGA R1 with auto focus on and using portenta clock settings

boards/ARDUINO_GIGA: Enable OV5640.

---

scripts/examples/01-Camera/01-Video-Recording/mjpeg.py
scripts/examples/01-Camera/01-Video-Recording/mjpeg_on_face_detection.py
scripts/examples/01-Camera/01-Video-Recording/mjpeg_on_movement.py
src/omv/imlib/imlib.h
src/omv/imlib/mjpeg.c
src/omv/modules/py_mjpeg.c

FPS is calculated internally now using microsecond resolution.
I noticed the video frame rate matches the camera FPS more consistently now.
Fixes: https://github.com/openmv/openmv/issues/2014

modules/py_mjpeg: Calculate MJPEG FPS internally.

---

scripts/examples/50-Arduino-Boards/Giga-H7/51-Display/display.py

The image is rotated after drawing the touch points, now that we're using the new draw flags, so the touch X axis needs to be reversed.

scripts/examples: Fix GIGA display script.

---

src/omv/boards/OPENMV_RT1060/imlib_config.h

Fixes: https://forums.openmv.io/t/apriltag-resolution-for-the-rt1062/9001

boards/OPENMV_RT1060: Enable high res apriltags.

---

src/omv/ports/mimxrt/sensor.c

Not sure why this works when the IDE is attached but crashes the system without the IDE.
I guess the code to update the frame buffer was saving us. But, that doesn't run anymore when the IDE is not attached.

ports/mimxrt: Service TinyUSB while waiting for sensor frames.

---

src/omv/ports/stm32/omv_spi.c
src/omv/ports/stm32/stm32fxxx_hal_msp.c

Fixes: https://github.com/openmv/openmv/issues/2042
And: https://github.com/openmv/openmv/issues/1926

ports: Don't deinit the SSEL pin on stm32 and mimxrt.

---

src/omv/boards/OPENMV_RT1060/omv_boardconfig.h

Was set for use on non-SDRAM based cameras.
Fixes: https://github.com/openmv/openmv/issues/2078

boards/OPENMV_RT1060: Update UMM Heap Size to match H7 Plus.

---

src/omv/imlib/apriltag.c

Fixes: https://github.com/openmv/openmv/issues/1854

imlib/apriltag: Fix find_rects() roi parameter.

---

src/omv/imlib/imlib.h
src/omv/imlib/isp.c
src/omv/modules/py_image.c

Move these to mp_arg_parse.
Also, I split up awb into parts so that it can be used for software white balance in the future for bayer only cameras we might use.

modules/py_image: Refactor isp ops to use mp_arg_parse.

---

src/omv/imlib/stats.c

Fixes: https://github.com/openmv/openmv/issues/1794

imlib/stats: Fix get_threshold A/B values.

---

scripts/examples/02-Image-Processing/01-Image-Filters/color_correction.py
src/omv/imlib/isp.c
src/omv/modules/py_image.c

I've noticed that we were missing hue/saturation shifting from our algorithm list for a while. However, on thinking about how to implement it, I realized that the current ccm() method is well-suited.
Realizing we have ulab onboard which provides a linear algebra pacakge onboard I wrote up the process below using the ccm() method to apply color shifts like you can do in photoshop. Converting to HSV/YUV to do the color shift and then back would be slower than what's going on below.
Then I updated the ccm() method to accept arrays from ulab more easily.
This shows off a pretty sweet collaboration between OpenMV's code and ulab. It also provides an example for the ccm() function.
...
Note, the purpose of the ccm() function is so that you can apply color correction if you've figured out the …

modules/py_image: Upgrade ccm to work well with ulab.

---

src/drivers/pixart/src/pixspi.c

Noticed this bug in the pixart driver code. Nothing would trigger it but thought to fix it.

drivers/pixart: Fix buffer overflow case.

---

src/omv/common/tinyusb_debug.c
src/omv/ports/mimxrt/omv_portconfig.mk
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake

Prior to this update, each port had to be patched to call TinyUSB debugging function. Now these wrappers will call the port's functions if debugging is not enabled.

misc: Use LD wrap for redirecting serial data to TinyUSB debug code.

---

scripts/examples/01-Camera/07-Sensor-Control/autofocus.py
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMV_RT1060/omv_boardconfig.h

Fixes: https://github.com/openmv/openmv/issues/2081
Now that JPEG is merged we should have space for the firmware since the software decoder is gone for the H7 line.

boards: Enable OV5640 Autofocus firmware and add example.

---

src/omv/Makefile
src/omv/common/pendsv.c
src/omv/ports/mimxrt/omv_portconfig.mk
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/omv_portconfig.mk

All ports use common PendSV code now, with port-specific PendSV entries defined in pendsv.h files.

ports/all: Refactor PendSV code.

---

src/omv/modules/py_image.c

Found by customer passing only one argument at time versus all like in the example.

modules/py_image: Fix bug with gamma arguments.

---

src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/ports/mimxrt/sensor.c

This PR adds all missing features to the IMX sensor driver.
set_windowing() now works.
set_framerate() now works.
Capturing 2592x1944 now works.
vsync callback now works.
frame callback now works.
I fixed the frame buffer memory allocations to use all 32 MB of SDRAM.
sensor.JPEG now works. 
Notably, thanks to the USB HS with sensor.JPEG mode you can stream JPEGs from the camera to the PC at the maximum FPS. E.g. you can move 1270x720 to the PC at 28 FPS and 1920x1080 at 10 FPS.
Fixes 1 in: https://github.com/openmv/openmv/issues/2079
I will work on getting the eMDA offload working after this PR is reviewed and merged.

port/mimxrt: Improve Sensor Driver.

---

src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/ports/mimxrt/sensor.c
src/omv/ports/rp2/sensor.c
src/omv/ports/stm32/sensor.c

This patch removes the duplicated `sensor_abort()` logic in the stm32 and mimxrt ports. This is done by adding a `flush_fifo` argument, which controls the flush operation, and a `in_irq` argument , which indicates whether `sensor_abort()` is called from within an IRQ context or not.

ports/all: Allow sensor_abort() to be called from different contexts.

---

src/omv/ports/stm32/omv_i2c.c

This saves boot time and also fixes an issue with some image sensors.

ports/stm32: Scan devices once per scan.

---

src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/ports/mimxrt/sensor.c
src/omv/ports/stm32/sensor.c

There's an opportunity for more cleanup to move the:
```
sensor.first_line = false;
sensor.drop_frame = false;
sensor.last_frame_ms = 0;
sensor.last_frame_ms_valid = false;
if (fifo_flush) {
framebuffer_flush_buffers(true);
} else if (!sensor.disable_full_flush) {
framebuffer_flush_buffers(false);
}
```
Into a function and also:
```
if (!sensor.first_line) {
sensor.first_line = true;
uint32_t tick = mp_hal_ticks_ms();
uint32_t framerate_ms = IM_DIV(1000, sensor.framerate);
// Drops frames to match the frame rate requested by the user. The frame is NOT copied to
// SRAM/SDRAM when dropping to save CPU cycles/energy that would be wasted.
// If framerate is zero then this does nothing...
if (sensor.last_frame_ms_valid && ((tick - sensor.last_frame_ms) < framerate_ms)) {
sensor.drop_frame = …
```

ports: Minor sensor cleanup.

---

src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h
src/omv/boards/ARDUINO_NICLA_VISION/omv_boardconfig.h
src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMV4_PRO/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/ports/mimxrt/sensor.c
src/omv/ports/stm32/sensor.c

Note `sensor_dma_memcpy` can be moved to `omv_dma_memcpy` in `omv_dma.h` and implemented in `omv_dma.c` in each port, if it makes sense to make it generic.

ports/all: Refactor sensor line copy.

---

src/omv/imlib/binary.c
src/omv/imlib/blob.c
src/omv/imlib/collections.c
src/omv/imlib/collections.h
src/omv/imlib/stats.c

- Remove unused linked list functions.
- Remove iterator functions and replace them with a list_for_each macro. Note the smaller iterator functions may Not have been inlined because we -fno-inline-small-functions is used.
- Replace iterator_get which used memcpy, with a cast.
- Add list_insert and list_remove functions.

imlib: Refactor collections linked list.

---

src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/common/sensor_utils.c
src/omv/ports/mimxrt/sensor.c

Broken out into a PR as requested from https://github.com/openmv/openmv/pull/2123

ports/mimxrt: Use hardware byteswap support.

---

src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/common/sensor_utils.c
src/omv/ports/mimxrt/sensor.c

Enables EDMA memcpy() on the RT1062. I wrote this first to understand better how edma works. I think I see a path to getting full offload operation. This PR improves performance by 15%. Full offload should provide much more.
Also, I found a way to offload the byte swap to the CSI hardware.

ports/mimxrt: Enable edma memcpy.

---

src/omv/ports/stm32/sensor.c

As requested. Tested against all camera modules.

ports/stm32: Fix xclk duty cycle to 50%.

---

src/omv/common/sensor_utils.c

Both sensors have the same I2C address, so can't be enabled at the same time. This patch tries to read a byte-sized address first, if GC2145 chip id is not read back, then it retries reading wide address. I tested this with RT1060 and H7 and I can detect the OV5640 fine.

misc: Support using GC2145 and OV5640 at the same time.

---

scripts/libraries/st7701.py
src/omv/modules/py_display.c
src/omv/modules/py_display.h
src/omv/modules/py_spi_display.c
src/omv/ports/stm32/modules/py_display.c

I added a stub to allow you to execute register reads and writes to the SPI display. I then implemented the SPI register write. I don't believe read will work for our driver as we didn't hookup that line.
Anyway, code is redundant from the DSI read/write. Thoughts what the API should be?
This fixes: https://github.com/openmv/openmv/issues/2066

modules/py_display: Add user SPI LCD register control.

---

src/omv/imlib/binary.c
src/omv/imlib/imlib.h
src/omv/imlib/mathop.c
src/omv/modules/py_image.c

Speeds up invert by doing a word at a time. Invert is also mathematically the same as negate and faster. So, negate() just points to invert.
I missed they were mathematically the same when I wrote this long ago.
Invert does: "~x"
Negate does (for a graycale value): "(255 - x) % 256" == "(255 + (~x + 1))  % 256" == "(256 + ~x) % 256" == "~x"
This same logic applies for RGB565.

modules/py_image: Optimize invert and negate.

---

src/omv/imlib/binary.c

Optimizes all binary ops such that they work 32-bits at a time. This provides speedups for grayscale and speedups for RGB565 images.
...
Also, I noticed that the inverted ops like NAND, NOR, and XNOR were incorrect. These ops just inverted one image and then did the AND/OR/XOR operation versus inverting the result of the operation. This is fixed in this PR.
Finally, for binary images, I made the code only operate on one bit at a time so that in the future, I can update the code to use the draw image backend. All these methods will be updated to work as lineops called from draw_row.
Broke up from: https://github.com/openmv/openmv/pull/2061

imlib: Optimize binary ops.

---

src/hal/cmsis/include/cmsis_extension.h
src/omv/imlib/binary.c
src/omv/imlib/imlib.h
src/omv/imlib/mathop.c

Optimizes add()/sub()/min()/max()/difference() using cortex-m SIMD so that they work 32-bit at a time. Grayscale operations are faster and RGB565 are faster.
negate() is deleted by PR: https://github.com/openmv/openmv/pull/2139
replace() and blend() will be removed in the future by switching to a draw_image backend. So, they were not optimized.
mul() and div() are removed by PRs: https://github.com/openmv/openmv/pull/2143 and https://github.com/openmv/openmv/pull/2140 respectively.
To save firmware space, I call the binary line op from some of these line ops when the result is the same.
Broke up from: https://github.com/openmv/openmv/pull/2061
...
Performance Numbers (on OpenMV Cam Plus):
VGA Resolution:
add:
* Binary: N/A See b_or performance
* Grayscale: 6968.43us (previous 8225.84) - …

imlib: Optimize math ops.

---

src/omv/imlib/binary.c
src/omv/imlib/imlib.h
src/omv/modules/py_image.c

Update erode/dilate/close/open/black_hat/top_hat to use mp_arg_pasrse_all().
Also, the meaning of the optional threshold value for erode has been changed to match how dilate's threshold works.

modules/py_image: Use mp_arg_pasrse_all for erode/dilate.

---

scripts/examples/08-RPC-Library/36-Web-Servers/rtsp_video_server_lan.py
scripts/examples/08-RPC-Library/36-Web-Servers/rtsp_video_server_wlan.py
scripts/libraries/rtsp.py
src/omv/imlib/framebuffer.c
src/omv/imlib/imlib.h
src/omv/imlib/jpege.c
src/omv/imlib/mjpeg.c
src/omv/modules/py_image.c
src/omv/ports/stm32/jpeg.c

This PR adds support for YUV422 compression in the hardware jpeg decoder on the STM32. YUV422 compression is slightly slower than YUV444. However, it's necessary to support as quite a lot of desktop software cannot process YUV444 JPEGs in MJPEG streams.
The second commit in this PR then changes the default compression level for YUV422 to turn on at 70 percent quality and adjusts all MJPEG streaming scripts to match that. This should fix all MJPEG streaming issues across all OpenMV Cams on most platforms.
Fixes: https://github.com/openmv/openmv/issues/2070
...
For example, the RTSP streamer to VLC doesn't work without this PR. Once you add this PR it works then like magic.

ports/stm32: Add support for YUV422 hardware JPEG compression.

---

src/omv/imlib/jpege.c

Added subsampling code I developed for https://github.com/openmv/openmv/pull/2153 to the software JPEG decoder. It improves the frame rate by a minor amount on RT1062.
YUV422
1280x720 @ 50% quality without == 177ms
1280x720 @ 50% quality with == 164ms
8% speedup
YUV420
1280x720 @ 30% quality without == 143ms
1280x720 @ 30% quality with == 136ms
5% speedup
It made more of a difference for https://github.com/openmv/openmv/pull/2153 because the MCU jpeg compression speed is faster using the hardware jpeg encoder. On that PR, the scaler version of the code drops the FPS noticeably, making YUV422 compression much slower than YUV444 compression. You get 62ms per frame at 1280x720 @ 50 quality on the H7 Plus with the vector code versus 74ms with scalar code, so 20% faster.
Anyway, if I can …

imlib/jpege: Improve jpeg YUV422/420 UV sub-sampling speed.

---

src/omv/imlib/binary.c
src/omv/imlib/imlib.h
src/omv/modules/py_image.c

* Removes a huge block of code in binary and leverages draw_image to deal with different pixel formats.
* Adds a new mask_line_op and zero_line_op (these will be used later in future PRs to reduce duplicate code).
* Updates binary() to use mp_arg_parse_all.

modules/py_image: Update binary to use mp_arg_parse_all.

---

src/omv/Makefile
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMV4_PRO/omv_boardconfig.h
src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/ports/mimxrt/omv_portconfig.mk
src/omv/ports/stm32/omv_portconfig.mk
src/omv/sensors/pag7920.c
src/omv/sensors/pag7920.h
src/omv/sensors/pag7920_reg.h

1. Add a sensor driver for PAG7920.
2. Add PAG7920-related definitions.

sensors/PAG7920: Support PixArt image sensor PAG7920.

---

src/omv/ports/stm32/sensor.c

When dropping a frame the current vbuffer state was Not reset, which caused the following frame(s) to be corrupted, probably also overwriting the next vbuffer.
This bug is what caused transposed high-resolution frames to be corrupted. If the DMA is not keeping up you should simply just see slower FPS or no frames at all but definitely never corrupted frames, since they're dropped.
Test code now never corrupts a frame:
```Python
import sensor
import time
import image
sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.VGA)
sensor.set_transpose(True)
clock = time.clock()
while True:
clock.tick()
sensor.snapshot().to_rainbow(color_palette=image.PALETTE_IRONBOW)
print(clock.fps())
```

ports/stm32: Reset vbuffer state when dropping frames.

---

src/omv/imlib/framebuffer.c

The CPU might fetch lines, speculatively, from a vbuffer after an invalidate and before the [M/E]DMA is done writing to it. In this case, when the DMA is done, the CPU will have some "outdated" lines in cache. Speculative access in CM7 is documented here https://developer.arm.com/documentation/ddi0489/f/memory-system/speculative-accesses
> Speculative cache linefills can be initiated to any Cacheable memory address, and in rare cases, regardless of whether there is any instruction that causes the cache linefill.
This change invalidates the buffer after the DMA is done and before returning it, to ensure the CPU drops any cached lines of that vbuffer.
* Fixes #2216

imlib: Invalidate vbuffers before returning them.

---

src/omv/imlib/binary.c

After looking at code in filter.c I realized the check wasn't in the right case.

imlib/binary: Fix erode mask check.

---

src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/common/sensor_utils.c

The Portenta sometimes fails to detect HM01B0 a soft-reset fixes it. I think this happens because reset is connected to an LDO, not to the sensor directly, so maybe it needs more time to settle down after it's enabled. Increasing the delay after reset/power-down seemed to fix it for me, but then I couldn't get it to fail again without this change, so I'm not sure if it's really needed.

misc: Increase delay after reset/power-down.

---

src/omv/imlib/imlib.h
src/omv/imlib/rectangle.c
src/omv/modules/py_tf.c
src/omv/modules/py_tf.h

Replaces: https://github.com/openmv/openmv/pull/2134
...
This PR adds support for a new method called invoke() which takes and input image in, runs tensorflow, and outputs a a 1d arrary of the results of on the micropython heap organized in h/w/c order. This is the default behavior, though its not very efficent when used with large models.
Invoke() can additionally take in a callback method though that can access the model output while it's still in the frame buffer stack for much more efficent operation. The callback is passed a new "model_output" object which has a subscr [] method which can get any value from the output sensor that's organized in h/w/c order. You can get individual values or slices. The "model_output" class also provides all the necessary dimension information for you …

modules/py_tf: Add generic CNN processing support.

---

scripts/examples/03-Machine-Learning/00-TensorFlow/tf_object_detection.py
src/omv/modules/py_image.c

This PR gives Image() the ability to build an image from a list/tuple of values (which can be integers or floats).
Image has 3 new arguments to support this feature:
shape - This is just a tuple of 3 values of the `(height, width, channels)`. height/width are self-explanatory. channels is the color depth which is either 1 or 3 for grayscale or rgb565 support.
strides - This a 2 valued tuple. The first value is the start position in the list/tuple to cast. Generally, this is a small offset value `start`.  For 3 channels it is then a 3 valued tuple `(start_r, start_g, start_b)`. The second value is the `step` between valid pixels to grab. Pixels are grabbed, starting a `start` and incrementing by `step`.
_The reason for a start per color channel in the RGB case is so that you can handle BGR …

modules/py_image: Add support for turning lists/tuples into Images.

---

README.md

Fixes a typo of "TensorFlow" in the README.md.

docs: fix misspelling of tensorflow

---

src/omv/common/usbdbg.c
src/omv/common/usbdbg.h
tools/pyopenmv.py
tools/pyopenmv_fb.py

The GET_STATE command is a command that returns flags, frame width, height, size, and the text buffer (up to 40 bytes), in a single 64 bytes packet to reduce the bandwidth/overhead of the protocol.
The packet format is:
```
word    word    word    word    2 words     40 bytes
<flags> <width> <height> <size> <reserved>  <null-terminated text>
```
The flags are mostly reserved, only the following bits are defined:
0x001 script running
0x010 text buffer valid.
0x100 JPEG frame buffer ready.

misc/usbdbg: Implement USB debug GET_STATE command.

---

src/omv/modules/py_ml.c

The bytearray size is the tensor shape times the dtype size.

modules/py_ml: Fix the size of the input bytearray.

---

src/omv/modules/py_image.c

Realized when reading the preprocessing.py code that there was no sanity check on the buffer length.

modules/py_image: Add buffer length sanity check.

---

src/lib/tflm/tflm_backend.cc
src/omv/modules/py_ml.c
src/omv/modules/py_ml.h

Fully vectorizes the scaling, zero-point, and datatype values. We should do this now so that if it does become the case in the future that a model has differently scaled tensor heads we have support already complete and don't have to break the API again. Given that the backend can change and we may not necessarily always be running tensorflow models, our code should handle each tensor differently.

modules/py_ml: Fully vectorize all input and output scaling/datatypes.

---

scripts/examples/50-OpenMV-Boards/60-Shields/61-Servo-Shield/main.py

Use SoftI2C to support OpenMV RT.

examples/ServoShield: Change to SoftI2c for RT.

---

src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h
src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/sensors/hm0360.c
src/omv/sensors/hm0360.h

Fixes: https://github.com/openmv/openmv/issues/2226
The Arducam module doesn't configure the sensor to use it's internal clock.

sensors/hm0360: Enable HM0360 to work on GIGA.

---

src/lib/tflm/tflm_backend.cc
src/omv/modules/py_ml.c
src/omv/modules/py_ml.h

It helps to know where the arena ended up going, for debugging performance in the future. Fixes #2273

modules/py_ml: Add tensor area memory address to model object.

---

src/drivers/mlx90640/src/MLX90640_I2C_Driver.c
src/drivers/mlx90641/src/MLX90641_I2C_Driver.c
src/omv/ports/mimxrt/omv_portconfig.h
src/omv/ports/nrf/omv_portconfig.h
src/omv/ports/stm32/omv_portconfig.h

Fixes: https://github.com/openmv/openmv/issues/2229
The maximum I2C read size on the RT1062 is 1024 bytes. This PR causes the higher-level code to split up the bread into chunks for the MLX90640 and MLX90641.
I looked into trying to make omv_i2c_read_bytes handler larger reads than 1024 bytes but there's no way to stop it from NACKing the last byte in a 1024 transfer even if you get it not to stop the bus and start a new transfer without doing I2C start/stop.

ports/mimxrt: Fix I2C for the MLX90640 driver.

---

src/drivers/display/LICENSE
src/drivers/display/include/cec.h
src/drivers/display/src/cec.c
src/omv/common/ini.c
src/omv/common/ini.h
src/omv/imlib/apriltag.c
src/omv/imlib/clahe.c
src/omv/imlib/dmtx.c
src/omv/imlib/jpegd.c
src/omv/imlib/lsd.c
src/omv/imlib/qrcode.c
src/omv/imlib/zbar.c
src/omv/modules/py_image.c

Need to add no GPL macro. Agast, LSD, and zbar are GPL code.
Fixes: https://github.com/openmv/openmv/issues/1887

misc: Add back original licenses.

---

scripts/libraries/rpc.py

Tested:
Fixes: https://github.com/openmv/openmv/issues/2265
SPI (STM32 Master, using machine module <-> STM32 Slave, using pyb module)
I2C (STM32 Master, using machine module <-> STM32 Slave, using pyb module)
SPI (RT1062 Master, using machine module <-> STM32 Slave, using pyb module)
I2C (RT1062 Master, using machine module <-> Arduino Uno, using C++ library)
I2C (RT1062 Master, using machine module <-> STM32 Slave, using pyb module) doesn't work. The STM32 holds the SDA line low, preventing comms. Not sure what the issue is exactly as this works between STM32 devices. Whatever the case, this issue is unrelated to the PR and verified RT1062 I2C master functionality working with an Arduino Uno Slave I2C device.

scripts/libraries: Update rpc_spi_master to use the machine module.

---

src/README.md

I tested the build process on a new machine and needed to add `sudo` - without it there were permission errors.

misc/README: Update builld instructions.

---

src/omv/modules/py_sensor.c

Realized it was missing when writing the documentation.

modules/py_sensor: Add missing PAG7920 enum.

---

src/omv/boards/ARDUINO_GIGA/imlib_config.h
src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h
src/omv/boards/ARDUINO_NANO_33_BLE_SENSE/imlib_config.h
src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/imlib_config.h
src/omv/boards/ARDUINO_NICLA_VISION/imlib_config.h
src/omv/boards/ARDUINO_NICLA_VISION/omv_boardconfig.h
src/omv/boards/ARDUINO_PORTENTA_H7/imlib_config.h
src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMV4_PRO/imlib_config.h
src/omv/boards/OPENMV4_PRO/omv_boardconfig.h
src/omv/boards/OPENMVPT/imlib_config.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PICO/imlib_config.h
src/omv/common/omv_gpu.h
src/omv/imlib/draw.c
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/ports/stm32/omv_gpu.c
src/omv/ports/stm32/omv_portconfig.mk

Fixes: https://github.com/openmv/openmv/issues/2269
I removed all the ping-pong buffer stuff going on in draw_image. This simplified a lot of code. It probably wasn't really even helping really. Also, DMA2D is used in it's fastest mode when it can offload a whole image copy. So, this likely speeds things up.
The GPU accelerated method is invoked if draw_image thinks it can use it. All checks for dealing with scaling, boundaries, centering, etc. are all handled already. The GPU is just given what it needs to do. Then, if it cannot support the operation, it should return false, and the software code will do it.
...
Regarding accelerating drawing methods like draw_lines and etc. New GPU stuff can accelerate these, too. However, this should be tackled later in another PR. This PR sets up our …

imlib/draw: Refactor draw_image to support gpu offload.

---

src/omv/modules/py_ml.c

Thought we should add it as I was writing the docs.

modules/py_ml: print model address location too.

---

scripts/libraries/ml/ml/apps.py

I realized it was missing when writing the documentation and noticing the infinite loop.

scripts/libraries: Add missing return in microspeech.listen().

---

src/lib/tflm/tflm_backend.cc
src/omv/modules/py_ml.c

ndarrays currently support uint8/int8/uint16/int16/float32. The ML module is just missing uint16 support to match it.

modules/py_ml: Add uint16 support to match ndarrays.

---

src/omv/common/omv_common.h
src/omv/imlib/draw.c
src/omv/imlib/jpegd.c
src/omv/imlib/jpege.c
src/omv/imlib/png.c
src/omv/ports/stm32/jpeg.c
src/omv/ports/stm32/omv_gpu.c

This way it can be called multiple times in the same function.

misc/common: Add arg to profile macro.

---

src/omv/alloc/fb_alloc.c
src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h
src/omv/boards/ARDUINO_NANO_33_BLE_SENSE/omv_boardconfig.h
src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/omv_boardconfig.h
src/omv/boards/ARDUINO_NICLA_VISION/omv_boardconfig.h
src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMV4_PRO/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/boards/PICO/omv_boardconfig.h
src/omv/common/common.ld.S
src/omv/imlib/framebuffer.c
src/omv/ports/rp2/rp2.ld.S

* Add start/end to JPEG buffer. This allows board config files to define them using linker script syntax (K, M etc..).
* Rename variables more consistently.
@kwagyeman FYI I replaced `JPEG_BUF_SIZE - 64` with `JPEG_BUF_SIZE - sizeof(jpegbuffer_t)`. I think the encoder ensures that will not overflow, but if the header size changes in the future, and gets bigger than 64, this could lead to a very hard to find bug.

misc/linker: Update linker script variables.

---

src/omv/imlib/framebuffer.c

This allows boards that don't have a hardware JPEG encoder, but do have fast scaling, to bypass JPEG encoding and send down-scaled raw frames. The raw preview frames are capped at a configurable max, but should not exceed ~60KBs.

imlib: Add support for sending raw preview frames.

---

src/omv/common/usbdbg.c
src/omv/imlib/draw.c
src/omv/imlib/framebuffer.c

draw_image() was not being invoked correctly to cause it to scale. This has been fixed. Also, the offset for the bilinear scaler has been moved to affect only the software code. Finally, I switched the empty flag for jpeg streaming to -1 from 0 which fixes binary image support.

boards/OPENMV_RT1060: Add support for RAW streaming.

---

src/omv/boards/OPENMV4P/omv_boardconfig.h

This should have been enabled in 51e6fd2912b5285993141774051b79507e0eebe9.

boards/OPENMV4P: Set HW crop flag.

---

src/omv/common/sensor_utils.c
src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h

Before this patch, a 1.5MB framebuffer used a single vbuffer for VGA and smaller resolutions, causing the sensor driver to restart with every snapshot. With this patch, a 1.5MB frame buffer uses 2 vbuffers for VGA/RGB and 3 vbuffers for VGA/grayscale **by default**. In the case of 2 vbuffers, it should leave the rest for `fb_alloc` (not tested), so `fb_alloc` still gets some extra space, but only if there's any left. If you need more space for `fb_alloc`, reserve more if possible.
Additionally, `set_buffers` is now more efficient with buffer sizes. For example, if the source is 1bpp (Bayer) and the destination is 1bpp (grayscale or Bayer), the vbuffer size will be `w*h`, instead of assuming that everything is 2bpp, which allows for more vbuffers.
`set_buffers` now replaces `auto_adjust`. …

imlib: Fix automatic vbuffer count.

---

src/omv/sensors/ov5640.c

MIPI bit mode division forgot that the camera has 2 MIPI lanes hence before dividing the PCLK with the bit mode the bit mode value should be divided by two. Secondly, the pll-predivider value extraction was done wrong, leading to wrong division of pll-predivider.

sensors/ov5640: Fix PCLK calculation for setting correct exposure time.

---

src/boot/src/common/mpu.c

If the first partition has a valid leave region, leave it as executable as it's typically used for the bootloader itself.

bootloader: Set first partition's region as executable.

---

src/omv/imlib/bayer.c

Fixes debayer_awb() on the non-vectorized processors... https://github.com/openmv/openmv/issues/2425
I don't see the issue using the OV7725 with the AE3. Need to duplicate the error test setup.

imlib/bayer: Fix debayer bound predication.

---

src/omv/ports/stm32/dma_utils.c

Only the bottom 8-bits of the dma_channel for the F4/F7/H7 can be masked.

ports/stm32: Fix DMA base calculation for F4/F7/H7.

---

src/omv/ports/stm32/jpeg.c
src/omv/ports/stm32/stm32_hal_msp.c

Allows using IT mode instead of DMA mode for jpeg compression. It mode is faster than non-IT mode since the processor can prepare the next MCU while the jpeg compressor is working.
Compression Performance on H7 Plus:
MDMA - VGA GRAYSCALE: 3.78ms - IT mode: 9ms
MDMA - VGA RGB565: 18.65ms - IT mode: 34.5ms
Decompression Performance on H7 Plus:
MDMA - VGA GRAYSCALE: 2.7ms - IT mode: 10.7ms
MDMA - VGA RGB565: 11.45ms - IT mode: 36ms

ports/stm32: Make usage of MDMA for jpeg compression conditional.

---

src/omv/modules/py_image.c

Maybe fixes: https://github.com/openmv/openmv/issues/2469
This would corrupt the trailing 1-3 bytes of an allocation. However, allocations are multiples of 4 bytes. So, while this is a fix, I am not sure if it fixes the user error as the corrupted bytes would be at the tail of a heap block not in use.

py_image: Fix corruption using to_ndarray() on grayscale images.

---

scripts/libraries/ml/ml/postprocessing.py

Cleanup of PR: https://github.com/openmv/openmv/pull/2511
Post-processing is now fully vectorized except for adding the boxes to nms.
TODO (FUTURE): NMS needs to be updated to be fully vectorized by numpy. The initial push for this was here: https://github.com/openmv/openmv/pull/2255#issuecomment-221307457.

scripts/libraries: Fully vectorize and cleanup yolo_v2 post-processing.

---

src/omv/imlib/draw.c

When the omv_gpu driver was added for the STM32 it allocates a CLUT using fb_alloc. However, during transpose we allocate all RAM. So, the GPU driver call fails to allocate the RAM it needs for loading it's CLUT.
On SDRAM boards this error doesn't happen the fb_alloc_all call will only exhaust onchip SRAM.

imlib/draw: Fixed transpose on SDRAM-less boards.

---

src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/common/vospi.c
src/omv/modules/py_fir_lepton.c
src/omv/ports/mimxrt/omv_portconfig.h
src/omv/ports/mimxrt/omv_spi.c

Fixes: https://github.com/openmv/openmv/issues/2485
1. Fixes swapped clock polarity names for the RT1062.
2.  The FLIR Lepton needs:
```
spi_config.clk_pol = OMV_SPI_CPOL_HIGH;
spi_config.clk_pha = OMV_SPI_CPHA_2EDGE;
```
On the STM32... we've been running for years with:
```
config->clk_pol = OMV_SPI_CPOL_LOW;
config->clk_pha = OMV_SPI_CPHA_1EDGE;
```
However, things work with the new settings, too... weirdly enough on the STM32.
...
Need to test VOSPI/FIR  thoroughly on both boards and all SPI IMXRT devices before this is ready.

common/vospi: Set vospi bus CPOL=1 and CPHA=1.

---

src/boot/src/ports/stm32/stm32_usb.h

Fixes: https://github.com/openmv/openmv/issues/2531
1. Disables turning the clock off when switching from the bootloader to firmware for the M4/M7.
2. M4 needs code to enable VBUS sense.
Tested on M4, M7, and H7.

boot: Fix m4 and m7 dfu bootloader.

---

src/omv/imlib/draw.c
src/omv/ports/stm32/omv_gpu.c

Tested on the STM32H7. In-place image cropping performance with RGB565 (only operation in-place DMA2D supports) sees a massive boost going from 21ms to 2ms as the copy on the image is removed.
Tested on Alif, all instances of scaling down and/or cropping at the same time work. The copy overhead has been removed.
Scaling up on Alif seems to have issues. Without this PR with and with out-of-place buffers you get a corrupted image.

imlib/draw: Enable GPU in-place cut-through.

---

src/omv/imlib/draw.c

Tested with scaling for for various network input sizes and it produces a clean result.

imlib/draw: Simplify GPU source rect calculation.

---

src/omv/imlib/bmp.c
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/imlib/jpege.c
src/omv/imlib/png.c
src/omv/imlib/ppm.c
src/omv/modules/py_image.c
src/omv/modules/py_imageio.c
src/omv/modules/py_tof.c

Ensures all xalloc calls to allocate image data are cache aligned and rounded up to the nearest size of a cache line. Both of these conditions are required to ensure the allocated image data doesn't interact with any other cache lines outside of it's allocation.

imlib/imlib: xalloc image to be cache aligned.

---

src/omv/ports/stm32/omv_gpu.c

Found when helping to test GPU scaling.

ports/stm32/omv_gpu: Fix cache line clean size.

---

scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
src/omv/common/omv_csi.h
src/omv/modules/py_csi.c
src/omv/sensors/genx320.c

Adding functions for tuning the sensor settings/biases for particular application/conditions 
* LED or active marker
* low-light
* default 2.0.0 biases 
Adding example for LED tracking

sensors/GenX320: Add IOCTL for biases settings.

---

src/omv/ports/mimxrt/mimxrt_hal.c
src/omv/ports/mimxrt/mimxrt_hal.h
src/omv/ports/mimxrt/omv_portconfig.h
src/omv/ports/mimxrt/omv_spi.c
src/omv/ports/stm32/stm32_hal_msp.c

Fixes: https://forums.openmv.io/t/when-the-display-library-of-the-lcd-expansion-board-is-used-the-p1-pin-cannot-be-used-normally/10519
Tested the LCD shield and FLIR Lepton on the H7 Plus and RT1062 and both devices work normally on each camera.

ports/all: Fix MISO/MOSI pins being used in TX/RX only mode.

---

scripts/libraries/ml/ml/postprocessing.py
src/omv/ports/mimxrt/omv_portconfig.mk
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/omv_portconfig.mk

Update to ULAB 6.7.3.
Tested using YOLOV2 and YOLOV5 models.
The new scipy integrate code in ulab takes quite a bit of space though...
Fixes: https://github.com/openmv/openmv/issues/2547

scripts/libraries: Simplify YOLO post-processing using keepdims.

---

scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/80-Low-Power/deep_sleep.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/80-Low-Power/stop_mode.py

Wrong API calls were used.
Tested fixes on RT1062.

scripts/examples: Fix IMXRT deepsleep and stop examples.

---

scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_set_afk.py
src/drivers/genx320/include/psee_genx320.h
src/drivers/genx320/src/psee_genx320.c
src/omv/common/omv_csi.h
src/omv/modules/py_csi.c
src/omv/sensors/genx320.c

This PR adds IOCTL for AFK (GenX320 AntiFlicker filter) allowing
* enable AFK with a new range of frequencies (useful for frequency filtering)
* disable AFK (as it is enabled by default and some users needs those filtered out frequencies)
* fixing typos and small cleaning
Tested on a LED (on top of https://github.com/openmv/openmv/pull/2614 ) and works well for filtering out given frequencies.

sensors/GenX320: Adding IOCTL to control Anti-Flicker filter (AFK).

---

src/drivers/genx320/src/genx320_issd_cpi_evt.c
src/drivers/genx320/src/genx320_issd_cpi_histo.c
src/omv/sensors/genx320.c

Changes (from Prophesee):
* New ISSD Sequence increases 24MHz PCLK to 48MHz
* Time base is now setup on the sensor so you can pass arguments in 1MHz units versus needing to be scaled by the clock.
Changes (from OpenMV):
* Fixed the CPI Output control register setup so that defining HSYNC/VSYNC times work.
This PR is needed to increase the RT1062 frame rate: https://github.com/openmv/openmv/pull/2142. While debugging I noticed that the RT1062 drops 1-2 lines randomly every couple of frames leading to frame drops. As you decrease HSYNC lower than 240 the number of lines being dropped per frame starts to grow. By the time you get down to an HSYNC of 32, it's pretty much every other frame is missing lines, resulting in the frame rate being cut in half as our driver drops corrupt frames.
That …

sensors/genx320: Update ISSD sequence to increase frame rate.

---

src/drivers/genx320/src/psee_genx320.c

'0' was written as EHC_INTEGRATION_PERIOD

psee_ehc_activate_override: use the correct accumulation time

---

src/omv/sensors/boson.c

It's possible to load settings into the FLIR BOSON via the desktop GUI which prevent it from outputting the expected image after reset. Always restore the factory default settings and apply all recomended steps to set the video output mode.

sensors/boson: Restore FLIR BOSON Factory defaults on reset.

---

src/drivers/cyw4343/firmware/cyw4343_btfw.h

Update the CYW43 to work with the new CYW43 BTHCI UART backend.

drivers/cyw4343: Fix BT firmware file.

---

src/boot/src/ports/alif/alif_ospi.c

Now that alt flashes use 8-bit DFS.

boot/alif: Disable swap for alternate flashes.

---

src/omv/common/omv_csi.c

At the very least, sleep will abort the transfer on low-power entry or exit, even if it's not fully supported.

misc/csi: Don't fail if sleep is not implemented.

---

src/omv/common/omv_csi.h

While adding a new port, I found that my `OMV_CSI_CLK_SOURCE` was not effective.  This was due to the value being defined as an `enum`, which is undefined during the preprocessor run.  This means that `OMV_CSI_CLK_SOURCE == OMV_CSI_CLK_SOURCE_TIM` was evaluating to `UNDEFINED == UNDEFINED`, always true.
Changing the `enum` to `#define`s to resolve this.

csi: remove enum to support preprocessor directives

---

src/omv/ports/stm32/omv_i2c.c

Complements #2653. 
One more detail for #2652.

ports/stm32: assert i2c not SPEED_FAST if not supported

---

ports/alif/alif.mk
tools/vela.ini

The correct performance information should be reported now when compiling the HP ROMFS img.
Grabbed new ini file from here: https://github.com/alifsemi/alif_ml-embedded-evaluation-kit/blob/main/scripts/vela/ensemble_vela.ini.
...
This is a draft because I need to test the resulting firmware. However, this mirrors the updated files for the IDE.

ports/alif: Change HP U55 config to SRAM_OPSI.

---

boards/OPENMV_AE3/romfs.json
boot/include/port.h
boot/src/common/dfu.c

Allows setting a custom delay for DFU partition. This should be set to ensure control transfers don't timeout if erasing the partition takes too long. By default, this is 0 for all partition types.
I did not check every possible flash type (we have boards with QSPI, OSPI, NOR and MRAM), but I think a default of 0 might be okay, as the slowest would be NOR (at around 2.5 seconds). For all SPI flashes, we do block erases (not sector not full erase). The recovery type/process for Everspin may need a little longer, though I don't remember it timing out
@kwagyeman Please check the boards and let me know which partitions need to have more delay, or just send a follow-up PR.
For all ST chips we use Program/erase parallelism = x32
STM32F427xx/STM32F429xx
STM32F765xx STM32F767xx STM32F768Ax …

boot: Add DFU partition delay setting.

---

scripts/libraries/ml/ml/postprocessing.py

Adds support for yolov8 post-processing, yolo_lc which runs fast on the the AE3 and gets more than 1 FPS on the H7 Plus and RT1062. Leveraging YOLO networks based on ST's Model Zoo: https://github.com/STMicroelectronics/stm32ai-modelzoo/tree/main/object_detection
For YOLOV2, the anchors used apply the -st variants of the YOLOV2 network. The anchors to use for the non-ST ones are the anchors in the YOLO_LC class. Note that YOLO_LC is just a speed up variant of YOLOV2.
The SSD networks do not work with TFLite for Microcontrollers, they need the Tile operator which is not provided by libtflm.
YOLOX doesn't run on the AE3, you get an invoke error from the NPU. YOLOX does run on the H7P and RT1062, but, is slow. Mult-tensor output needs to be added for it to work on the N6. I tried to get …

scripts/libraries: Add support for more yolo post-processing.

---

common/omv_csi.c
common/omv_csi.h
drivers/sensors/genx320.c
drivers/sensors/mt9m114.c
drivers/sensors/mt9v0xx.c
drivers/sensors/ov5640.c
ports/alif/omv_csi.c
ports/mimxrt/omv_csi.c
ports/nrf/omv_csi.c
ports/rp2/omv_csi.c
ports/stm32/omv_csi.c

No functional changes, just moving functions and code around to make #2691 more readable.
Note that `omv_csi_get_clk_frequency` was overridden using the wrong name in alif port.

ports/all: Refactor CSI drivers.

---

boards/OPENMV3/omv_boardconfig.h
boards/OPENMV4/omv_boardconfig.h
boards/OPENMV4P/omv_boardconfig.h
drivers/sensors/lepton.c
drivers/sensors/paj6100.c
ports/stm32/omv_csi.c

M4:
* OV7725 -> Works
* OV2640 -> Works
M7:
* OV7725 -> Works
H7:
* OV7725 -> Works
* OV2640 -> Works
* OV5640 -> Works
* MT9M114 -> Works
* MT9V034 -> Works
* Lepton -> Works
* Boson -> Not enabled
* GENX320 -> Not enabled
* PAG7920 -> Works
* PAG6100 -> Working in v4.5.2, broken in v4.5.3
* (spent 3 hours on trying to figure it out will continue in another PR - unrelated to dual csi stuff).
H7 Plus:
* OV7725 -> Works
* OV2640 -> Works
* OV5640 -> Works
* MT9M114 -> Works
* MT9V034 -> Works
* Lepton -> Works
* Boson -> Works (but not generally enabled)
* GENX320 -> Works
* PAG7920 -> Works
* PAG6100 -> Working in v4.5.2, broken in v4.5.3
RT1062:
* OV7725 -> Works
* OV2640 -> Works
* OV5640 -> Works
* MT9M114 -> Works
* MT9V034 -> Works
* Lepton -> Works
* Boson -> Works
* GENX320 -> …

common/omv_csi: Fix all sensors working on all boards.

---

common/omv_csi.c
common/omv_csi.h
ports/alif/alif_hal.c
ports/alif/alif_hal.h
ports/alif/omv_csi.c
ports/mimxrt/mimxrt_hal.c
ports/mimxrt/omv_csi.c
ports/nrf/main.c
ports/nrf/omv_csi.c
ports/rp2/main.c
ports/rp2/omv_csi.c
ports/stm32/omv_csi.c
ports/stm32/stm32_hal_msp.c

* Removes duplicate CSI initialization code (almost identical in every port).
* Makes it easier to make changes in the future (e.g., decouple the clock).
* `omv_csi_init` is still completely replaceable.
Notes:
* One change from old code, made all control pins `PULL_NONE`, just doesn't make much sense to select one pull or the other.
* Some ports require the IP clock to generate the external clock, so those have to initialize CSI earlier.
* There was an extra `csi->detected=True` in alif port, probably due to duplicate code, copy&paste this is no longer needed, it's done in common code.
While at it, nrf and rp2 were missing `csi_init0` (still unknown though if they actually work). Tested the rest of the ports (imxrt, stm, alif).

ports/all: Refactor CSI port init.

---

boards/OPENMV_AE3/omv_boardconfig.h
boards/OPENMV_N6/omv_boardconfig.h
common/omv_csi.c
common/omv_csi.h
drivers/sensors/genx320.c
drivers/sensors/mt9m114.c
drivers/sensors/mt9v0xx.c
drivers/sensors/ov5640.c
ports/alif/omv_csi.c
ports/mimxrt/omv_csi.c
ports/nrf/omv_csi.c
ports/rp2/omv_csi.c
ports/stm32/omv_csi.c
ports/stm32/omv_portconfig.h

This patch decouples the clock from the main CSI state, further separating the CSI instance from the port's CSI driver. Additionally, it allows CSIs to use different clocks, in theory, though they must first be detected somehow in order to switch clocks.
As a side effect of sharing the clock, set_frequency will be called more frequently (the default call plus once per CSI). However, the frequency is now checked, and the clock is only reconfigured if the new frequency exceeds a configurable tolerance.
Finally, get_clk_frequency now accepts a boolean to return either the exact clock frequency, for sensors that require it, or the nominal frequency.
Note that sensor drivers should be checked to see which ones require the exact clock and which require the nominal clock. I best guessed them for …

common/csi: Decouple the clock from main CSI state.

---

boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
boards/OPENMV4/omv_boardconfig.h
boards/OPENMV4P/omv_boardconfig.h
boards/OPENMVPT/omv_boardconfig.h
boards/OPENMV_N6/omv_boardconfig.h
boards/OPENMV_RT1060/omv_boardconfig.h
common/omv_csi.c
drivers/sensors/ov5640.c
drivers/sensors/sensor_config.h

Tested on a Rev-Y board 400 MHz H7. It's not needed anymore. System works fine without it using OV5640.
I think this was added initially because the set_clk_freq code used to pick a higher freq than requested if it couldn't meet the target. However, after that bug was discovered and fixed this check is not necessary anymore.

drivers/sensors: Remove OV5640 REV_Y special case.

---

boards/OPENMV_RT1060/omv_boardconfig.h

* Update RT1062 USB ID from the FOSS one to our private VID:PID.
* Increase USB buffer sizes for faster CDC transfer.

lib/micropython: Update RT1062 USB ID and buffers.

---

ports/stm32/omv_csi.c

This macro was removed so FRAME_IT was not enabled.

ports/stm: Re-enable frame interrupt in JPEG mode.

---

boards/OPENMV2/omv_boardconfig.h
boards/OPENMV3/omv_boardconfig.h
boards/OPENMV_AE3/omv_boardconfig.h

Did the polarity audit. Here are the results:
```
{ OMV_CSI_ACTIVE_HIGH, OMV_CSI_ACTIVE_HIGH },
{ OMV_CSI_ACTIVE_HIGH, OMV_CSI_ACTIVE_LOW },
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_HIGH },
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_LOW },
```
-> Current,  all sensors work
```
{ OMV_CSI_ACTIVE_HIGH, OMV_CSI_ACTIVE_LOW },
{ OMV_CSI_ACTIVE_HIGH, OMV_CSI_ACTIVE_HIGH },
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_LOW },
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_HIGH },
```
Lepton1/Lepton3 work
MT9M114/MT9V034 works
PAG7920/PAJ6100 work
OV7725 works
OV2640/OV5640 work
GENX320 works
BOSON works
PAG7936 works
PS5520 works
all sensors work with this config too
```
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_LOW },
{ OMV_CSI_ACTIVE_LOW,  OMV_CSI_ACTIVE_HIGH },
{ OMV_CSI_ACTIVE_HIGH, OMV_CSI_ACTIVE_LOW },
{ …
```

boards: Add fixed sensor polarity configs.

---

common/common.mk
common/fb_alloc.c
common/fb_alloc.h
common/omv_common.h
common/omv_csi.c
common/omv_csi.h
common/queue.c
common/queue.h
common/vospi.c
common/vospi.h
drivers/sensors/lepton.c
drivers/sensors/softcsi.c
lib/imlib/framebuffer.c
lib/imlib/framebuffer.h
modules/py_csi.c
modules/py_csi_ng.c
modules/py_helper.c
ports/alif/alif.mk
ports/alif/omv_csi.c
ports/mimxrt/omv_csi.c
ports/mimxrt/omv_portconfig.mk
ports/nrf/omv_csi.c
ports/nrf/omv_portconfig.mk
ports/rp2/omv_csi.c
ports/rp2/omv_portconfig.cmake
ports/rp2/omv_portconfig.mk
ports/stm32/omv_csi.c

The main motivation for this work is to fix the FB double buffer issue, and possible race condition in triple buffer mode. However, as an added bonus, this also offers some optimization, code safety, new features and major cleanups.
---
* The frame buffer now uses two queues to manage the buffers: a free queue and a read queue. It juggles buffers between queues based on the operation and flags. The frame buffer code has been simplified a lot, since much of the complexity has been pushed out to the new queue component. It is also much more flexible now. For example, we could add a third queue if needed, or check the queue sizes and so on.
* The new SPSC lock-free queue component uses standard atomics and acquire and release semantics to ensure there are no issues with reordering by either …

imlib: Rework frame buffer management.

---

common/omv_gpu.h
drivers/sensors/lepton.c
lib/imlib/apriltag.c
lib/imlib/binary.c
lib/imlib/dmtx.c
lib/imlib/draw.c
lib/imlib/framebuffer.c
lib/imlib/imlib.h
lib/imlib/lsd.c
lib/imlib/mjpeg.c
lib/imlib/qrcode.c
lib/imlib/stats.c
lib/imlib/zbar.c
modules/py_csi_ng.c
modules/py_fir.c
modules/py_helper.c
modules/py_helper.h
modules/py_image.c
modules/py_spi_display.c
modules/py_tof.c
modules/py_tv.c
ports/alif/omv_csi.c
ports/alif/omv_gpu.c
ports/stm32/modules/py_display.c
ports/stm32/omv_gpu.c

This PR adds initial matrix transformation support to draw image which can be used anywhere in the code.
Right now it just supports 2x3 affline matrices and 3x3 perspective transform matrices. However, I plan to expand support in the future for general purpose image remap transformation matrices which can be used for lens correction in the future (the CPU would handle this).
The code is written so that if the GPU can handle the operation it will. Otherwise, things fallback to the CPU based renderer. Note that I did not implement any of the CPU fallback path, so, draw_image will just ignore the `mat` argument if the GPU doesn't support it (and only the N6 has a GPU that can do this right now).
https://github.com/user-attachments/assets/b3e9a9f7-0fee-4401-a9f8-3ac22a19ef98
```
import sensor …
```

ports: Add GPU matrix support.

---

boards/OPENMV_N6/omv_boardconfig.h
ports/stm32/omv_portconfig.h

 boards/OPENMV_N6: Enable triple buffering for the N6.

---

common/omv_csi.c
drivers/sensors/hm01b0.c
modules/py_csi_ng.c

When the `sensor` module is removed eventually, all of the `Bx` resolutions will be removed as well.

modules/py_csi_ng: Support custom frame size.

---

ports/mimxrt/mimxrt_hal.c
ports/mimxrt/omv_csi.c
ports/mimxrt/omv_portconfig.h

Full DMA offload on the RT1062 increases the max frame rate with the GENX320 sensor in histogram mode to match the H7 Plus.
See https://github.com/openmv/openmv/pull/2805#issuecomment-3189726152 for the test results.

ports/mimxrt: Enable full DMA offload for RT1062. 

---

lib/cmsis/include/cmsis_extension.h

Copied what to do from: https://github.com/openmv/openmv/blob/master/lib/cmsis/include/cmsis_gcc.h#L1989
Tested a few functions that depend on these and didn't notice any issues.

lib/cmsis: Fix cmsis compile time constant folding.

---

common/omv_common.h
common/tinyusb_debug.c
common/tinyusb_debug.h
common/usbdbg.c
common/usbdbg.h

This commit refactors the TinyUSB debug interface with the following changes:
- Replace global variables with centralized state.
- Add timeout, recovery and validation for more robust transfers (as much as possible given the protocol limits).
- Handle disabled IRQs.

common: Refactor TinyUSB debug interface implementation.

---

common/usbdbg.c

The removal of unused USB commands that are still sent by the IDE causes tinyusb boards to crash on connect currently. Flushing the excess received bytes for unknown commands solves this issue.
The unused commands will still be removed in the IDE with an IDE release coming soon. But, this fix prevents breaking customer boards who are trying to use the Tools->Install Latest Development Firmware currently, and also customers who may not migrate to the latest IDE immediately.

common/usbdbg: Flush data from unsupported commands.

---

common/mutex.c

This reverts commit bb5228856119585763905b13e2763173e49323bf.
Event though this fixes a deadlock in the new protocol, it actually breaks fair locking as one side could lock multiple times in a row.

Revert "common/mutex: Clear tid when releasing mutex"

---

tools/uncrustify.cfg

Set nl_brace_struct_var = remove to keep union/struct variable declarations on the same line as the closing brace.

tools: Fix uncrustify union variable formatting

---

drivers/boson/include/timeoutLogic.h

Fixes compile issue with https://github.com/openmv/openmv/pull/2870.

drivers/boson: Use timespec struct from header.
