usr/pydfu.py

This was a change done by @dpgeorge in the micropython tree and
I'm basically migrating back to openmv.

pydfu - minor improvement in list construction.

---

src/omv/array.c
src/omv/array.h
src/omv/img/imlib.h
src/omv/py/py_image.c

There were a lot of missing features in the array module. I added
quicksort based on the MP sort function and I expanded the array code so
you can do stuff like take() which lets you get an object from an array
and easily put it into another array (take will be used to make the rectangle merge function work a lot better).
I also fixed the "struct array" problems in the code. Anonymous structs
have to go.
* Note: I did find a bug in your code in the array erase function. Luckily the function was unused:
if (array->index >1 && idx < array->index){
Should have been:
if (array->index >1 && idx < array->index-1){
Because idx is always less than array->index. So, if you're checking for the edge you must check on less.
Anyway, I tried the changes with face tracking. So, they didn't obviously …

Fixed up array functions.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/point.c
src/omv/img/rectangle.c

Point didn't need many changes. However, for rect I made the merge
function alot better so it won't alloc while merging, just free.
Additionally, I added a function to get the intersecting rectangle of an
image. This will be used for all functions that accept a subimg
argument. This function allows the user to basically pass any wild and
crazy rect they want and the function will find the intersecting area (if
it exists) and return just that to operate on. This is good for "do what
I mean" functionality versus "do what I say".
Note: There's no need to check alloc's return value. If it fails it will jump elsewhere.

Fixed up point and rect.

---

src/omv/py/py_image.c

Added new image querying functions.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
usr/examples/drawing.py
usr/examples/eye_detection.py
usr/examples/face_eye_detection.py
usr/examples/face_tracking.py
usr/examples/keypoints.py
usr/tests/test_drawing_1.py
usr/tests/test_drawing_2.py

All the drawing functions have been updated to handle automatic clipping
when drawing offscreen and work with both grayscale and RGB565.
Additionally, all functions now accept color arguments.
I've also updated the example scripts with the new functions and tested
them out to make sure they work.
Additionally, I wrote a test suite for the drawing functions to make
sure they work.

New drawing functions.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c

Pixels, centroid, orientation, along with the basic binary tool kit
functions like and/or/xor.

Added binary image functions.

---

src/omv/img/imlib.c
src/omv/py/py_image.c
usr/tests/test_binary_1.py
usr/tests/test_binary_2.py
usr/tests/test_drawing_1.py

Things are working.
All the updates you've done are starting to really pay off. The system is very stable now and does what you want. Great job! I'm starting to feel comfortable with the system.

Tested draw_keypoints and some of the binary code.

---

src/omv/img/bmp.c
src/omv/img/ppm.c

RGB565 reading and writing is going to be slow. But, grayscale is going
to be going as fast as the system can go.
If Omnivision has just reversed the byte order of data sent to the
camera we wouldn't have this problem for RGB565.

Made grayscale read/writing fast.

---

src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/jpeg.c

Fimrware will now automatically detect the appropriate file type and read
in that file type correctly.
Working on tying on of this stuff together next. It's getting a little
bit too complicated to deal with error cases. Need to add error message
function layer.

Add top level file open function.

---

src/omv/py/py_image.c

The code clearly did not swap mins and maxes.

Fix swap bug.

---

src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
usr/examples/motion_detection.py

Woot, all the effort to make it so you can manipulate the image buffer
with an image off disk works!
Try out the motion_detection script.

Background Subtraction is working!!!

---

src/Makefile
src/omv/Makefile
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/morph.c
src/omv/py/py_image.c
usr/examples/edge_detection.py

The morph function lets you convolve the image with a kernel. It's
decently fast right now. But, in the future we'll have to optimize it by
a lot (unrolling loops, using SIMD instructions, etc.).
Anyway, along with morph I added an edge detection test script showing
how you can use a high pass filter on an image to get all the edges in
it. This is not as good as canny edge detection... but, it's about the
same and fast enough.
We'll need a Hough Transform system in the future to make edge detection
useful. Not sure how that will be implemented... so, that's going to be
far away for now.

Add new morph function.

---

src/Makefile
src/omv/Makefile
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/stats.c
src/omv/py/py_image.c

You can now get the color stats for an area in the image. The stats
function returns the mean, median, mode, min, max, st_dev,
lower_quartile, and upper_quartile.
This function allows you to automate binary and threshold functions
based on what's in the image.

Add statistics function.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/stats.c
src/omv/py/py_image.c

Now you can convert from rgb to lab/grayscale and vice-versa. Without
this functionality it would be hard to deal with moving between RGB and
LAB.

Add color functions.

---

src/omv/img/gif.c
src/omv/img/imlib.h
src/omv/py/py_gif.c
usr/examples/gif.py

Color gifs look very good for how bad you'd expect them to be with just
7 bits of color (rgb232) - quite amazing. Also, I  hardened the gif
module to make it "user ready".
I was going to try to make color gifs using the LAB color space... and that doesn't make sense to do given how many calculations that have to be performed to scale pixel values and etc. Just using the RGB color space seems to work fine.

Add support for color gif.

---

src/omv/img/gif.c
src/omv/py/py_gif.c
usr/examples/gif.py
usr/examples/mjpeg.py

And tested it along with mjpeg to make sure all this stuff is good. I
also see the issue with QQVGA now. That just appeared.

Update Gif to use fb_alloc_all.

---

src/Makefile
src/omv/Makefile
src/omv/main.c
src/omv/py/py_lcd.c
src/omv/py/py_lcd.h
usr/examples/Example1-LCD-Shield-Demo.py

It's now ultra fast, safe and friendly. I tested everything too and added an example script (very simple).

Move LCD code into module.

---

usr/openmv-ide.glade
usr/openmv-ide.py

The copy color function now works. It will automatically determine the
best thresholds to use to track a particular color blob for you.

Add copy color.

---

src/omv/py/py_fir.c
usr/examples/fir.py
usr/examples/fir_lcd.py

And fixed type in blend. Per Ibrahim's suggestion.

Renamed Display to Draw

---

src/omv/img/blob.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
usr/examples/05-Snapshot/snapshot_on_movement.py
usr/examples/06-Video-Recording/gif_on_movement.py
usr/examples/06-Video-Recording/mjpeg_on_movement.py
usr/examples/10-Color-Tracking/blob_detection.py

Removed micropython code from the image libary. Also, blobs are now 10
tuple values by default now. The multilist thing has been removed from
blobs and it will return just a list of blobs instead of a tree of
lists.
Filter functions still work too.

Fixed blob code.

---

src/omv/ff_wrapper.c
src/omv/ff_wrapper.h
src/omv/main.c

This wasn't getting reinited breaking the system.

Fixed file buffer bug.

---

src/omv/img/imlib.c

This was bugged. Tested and now works.

Fixed dilate.

---

src/omv/img/imlib.c
src/omv/img/imlib.h

Added YUV to RGB565 conversion to make this happen.

Made histeq work for RGB565.

---

src/omv/img/fft.c
src/omv/img/fft.h
src/omv/img/phasecorrelation.c

There were some mistakes, they are fixed now. FFT 1D and 2D work
flawlessly. No problems with that code anymore.
As for phase correlation I need to study how to interpret the output
better. The function generates noisy results once you move the image too
far and I'm not quite sure if I have the code right for detecting
positive and negative displacements.
For testing, just compare the previous image against the current. Its very accurate then. Size must be 64x64 pixels or less.

Fixed FFT and Phase Correlation!

---

src/omv/py/py_fir.c

Changes fir_init() (file py_fir.c) to take three arguments:
fir_init(*[refresh,resolution, type=1]*)
where:
refresh: refresh rate in Hz, between 1 and 64 Hz (64 Hz default)
resolution: ADC resolution in bits, between 15 and 18 (18-bits default)
following the rational in [#147](https://github.com/openmv/openmv/issues/147)
The existing *type=1* argument was placed last, as I believe that dictionary arguments (`*kw_args`) must follow scalar args (`*args`)
I'm unpracticed with writing C for Python, especially within a large calling framework -please make suggestions!

changes fir_init() to take specified refresh rate and ADC resolution

---

src/Makefile
src/omv/Makefile
src/omv/img/collections.c
src/omv/img/collections.h
src/omv/img/imlib.h

Add collections

---

src/omv/img/blob.c
src/omv/img/collections.c
src/omv/img/collections.h
src/omv/img/imlib.h
src/omv/img/qrcode.c
src/omv/img/stats.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

Minor Speed Improvements to Blob, QRCode, and Stats

---

src/omv/fb_alloc.c

Needs to be linked into MP too.
fb_alloc_free_till_mark() must be called by nlr_jump().
This way fb_allocs clean themselves up when an exception happens. mark just has to be called first before any fb_allocs. If mark is not called then the entire fb_alloc stack is cleaned up. As of right now we don't have any image lib functions which are re-entrant (i.e. multiple marks) so all memory will be free'd by an exception anyway.

Add fb_alloc stack unwinding code.

---

src/omv/py/py_sensor.c
usr/examples/09-Feature-Detection/qrcodes_with_lens_zoom.py

Tested with updated qr code example script.

Made set_windowing simpler.

---

usr/examples/02-Board-Control/arduino_i2c_slave.py
usr/examples/02-Board-Control/arduino_spi_slave.py

Arduino Interfacing Code

---

usr/examples/10-Color-Tracking/automatic_grayscale_color_tracking.py
usr/examples/10-Color-Tracking/automatic_rgb565_color_tracking.py

Added a box to put the object to track in.

Make how to use these scripts more obvious.

---

src/omv/main.c

It can now check if the self-test passed.

Add flag for SWD programmer.

---

usr/examples/17-Pixy-Emulation/apriltags_pixy_i2c_emulation.py
usr/examples/17-Pixy-Emulation/apriltags_pixy_spi_emulation.py
usr/examples/17-Pixy-Emulation/apriltags_pixy_uart_emulation.py
usr/examples/17-Pixy-Emulation/pixy_i2c_emulation.py
usr/examples/17-Pixy-Emulation/pixy_spi_emulation.py
usr/examples/17-Pixy-Emulation/pixy_uart_emulation.py

UART/I2C work really good. SPI works as best as it can. I put a note in the script about issues with SPI interfacing.
These scripts are goo reference for how to do UART/I2C/SPI I/O.

Add pixy emulation scripts

---

usr/examples/17-Pixy-Emulation/apriltags_pixy_uart_emulation.py

Fix uart receiving code

---

src/omv/img/apriltag.c
src/omv/py/py_image.c
usr/examples/16-Codes/find_apriltags_3d_pose.py
usr/examples/18-MAVLink/mavlink_apriltags_landing_target.py

Fixed apriltags z translation.

---

src/omv/img/zbar.c

Main ZBar code, breaking the commit up because the main file is big.
I will refeactor UMM alloc out of apriltag.c and zbar.c once I'm
finished with this commit stream.
ZBar integration gives us support for basically all 1D linear barcodes.

ZBar Integration Part 1/2.

---

src/omv/img/qrcode.c

Keeping code up to date with quirc library commits. (No functional change difference in code execution, but, want to make sure I'm tracking the upstream on every change).

Pull in upstream quirc fixes from github.

---

src/Makefile
src/omv/Makefile
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/img/dmtx.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/16-Codes/find_datamatrices.py
usr/examples/16-Codes/find_datamatrices_w_lens_zoom.py

Add support for decoding data matrices and example scripts.

Add data matrix support.

---

src/omv/img/hough.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/09-Feature-Detection/find_line_segments.py

The OpenMV Cam can now find infinite lines and line segments from those
infinite lines. find_lines had to be re-worked to allow all this to work.

Add find_line_segments

---

src/omv/py/py_sensor.c

Should have added this a long time ago.
Now we can update all the scripts which have this stuff hard coded.

Add sensor width and height.

---

src/omv/py/py_image.c

All chunks are multiples of 16 bytes. Don't want to run into issues with
long alignment now or in the future.

Improve stream file format.

---

src/omv/py/py_image.c

It now updates the jpeg buffer and will error out if loading an image that is too large.
We should also add a method to flush the jpeg buffer since the example script still requires a call to do that...

Improve image load.

---

src/omv/img/blob.c
src/omv/py/py_image.c

* Angle averaging done correctly using sin/cos now.
* Unspecfied color bounds default to least restrictive instead of most
restrictive.

Fixed blob issues.

---

src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/img/apriltag.c
src/omv/img/hough.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/09-Feature-Detection/find_rects.py

Add find_rects() using AprilTag's quad detector.

---

usr/openmv-fb.py

Make this script work as a standalone program, and update to latest openmv API

Update to latest openmv API

---

src/omv/img/stats.c

No more memcpys all over the place. Not sure why I was doing that.
... code must have been written by an idiot before :) (me).
It can handle 5X more pixels than before (that said, the N^2 nature means you still need to keep the number of points low).

Improved the performance of the get_regression() robust linear regression code for racing.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/stats.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/20-Frame-Differencing/structural-similarity.py

Squash the two commits if you like. The first one was needed for the SSIM code. Yes, I tested previous code to make sure it still works.

Compare methods

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/qstrdefsomv.h

Just updating the code with the same style as other methods. I have
another new sister method for histeq() coming up next which I'll push
as soon as this PR is done. Didn't want to merge the two into one PR.
Code's been tested and there is no performance change.

Refactor histeq()

---

src/omv/img/imlib.h
src/omv/img/mean.c
src/omv/img/median.c
src/omv/img/midpoint.c
src/omv/img/mode.c
src/omv/py/py_image.c
usr/examples/04-Image-Filters/mean_adaptive_threshold_filter.py
usr/examples/04-Image-Filters/median_adaptive_threshold_filter.py
usr/examples/04-Image-Filters/midpoint_adaptive_threshold_filter.py
usr/examples/04-Image-Filters/mode_adaptive_threshold_filter.py

I still need to go back and optimizing and cleanup the code. I just
wanted to get the feature in first.
Adaptive thresholding lets you see things like dirty on a white piece of paper that's unevenly lit. There was a question on the forums about this about a week or two ago. This algorithm makes their life easy.

Add adaptive thresholding to filters.

---

src/omv/img/phasecorrelation.c
src/omv/py/py_sensor.c
usr/examples/04-Image-Filters/linear_polar.py
usr/examples/04-Image-Filters/log_polar.py
usr/examples/22-Optical-Flow/image-patches-absolute-rotation-scale.py
usr/examples/22-Optical-Flow/image-patches-absolute-translation.py
usr/examples/22-Optical-Flow/image-patches-differential-rotation-scale.py
usr/examples/22-Optical-Flow/image-patches-differential-translation.py

Someone asked me about doing a field of receptors before. These scripts
show how to do that. Also, added example scripts for calling the linear
polar and log polar methods added previously which power
find_rotscale().
Bug fixes are included which make the scripts work.

Add Advanced Optical Flow scripts

---

src/omv/img/phasecorrelation.c
src/omv/py/py_image.c

Fixed bugs with logpolar/linpolar.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

These have cool ghost image like affects and are useful for frame
differencing.

Add min()/max() for frame differencing.

---

usr/examples/08-Eye-Tracking/iris_detection.py

typo correction

---

src/omv/img/binary.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/mathop.c
src/omv/img/shadow_removal.c
src/omv/img/stats.c
src/omv/py/py_helper.c
src/omv/py/py_image.c

All our basic ops now support "color" scalars. This brings our basic ups to other image library specs.

Add scalar support

---

src/omv/py/py_image.c

Fix bug with sharpen.

---

src/omv/img/binary.c
src/omv/img/filter.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/04-Image-Filters/color_bilateral_filter.py
usr/examples/04-Image-Filters/grayscale_bilateral_filter.py

Just need to add a mean shift like filter and we'll have a pretty solid lib of all major filtering algorithms.
I think I can use the find_blob algorithm to do something mean shift like that will flatten similar colored areas and remove texture.

More image filtering stuff

---

src/Makefile
src/omv/Makefile
src/omv/img/binary.c
src/omv/img/clahe.c
src/omv/img/edge.c
src/omv/img/filter.c
src/omv/img/imlib.h
src/omv/img/mathop.c
src/omv/img/shadow_removal.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/04-Image-Filters/adaptive_histogram_equalization.py
usr/examples/04-Image-Filters/color_bilateral_filter.py
usr/examples/04-Image-Filters/grayscale_bilateral_filter.py
usr/examples/04-Image-Filters/histogram_equalization.py

The big win is CLAHE. Works super nice. Bilateral filtering is nice too.
...
I also started working on the code for a fast mean_shift like filter. However, it's very buggy still.

Random Library Fixes

---

src/omv/img/blob.c
src/omv/img/draw.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/03-Drawing/flood_fill.py

The algorithm itself is setup to be used for future filters.
Those will come in some PRs next.

Add flood fill

---

src/omv/img/draw.c
src/omv/img/imlib.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h
usr/examples/03-Drawing/text_drawing.py

Non monospace text drawing. Looks way better.

Add better text drawing.

---

src/Makefile
src/omv/Makefile
src/omv/py/py_omv.c
src/omv/py/qstrdefsomv.h

Lets you print out and access a few key strings.

Add openmv version info module.

---

src/omv/mt9v034.c
src/omv/ov2640.c
src/omv/ov7725.c
src/omv/ov9650.c

Fix gain_db control

---

src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/img/draw.c
src/omv/img/filter.c
src/omv/img/hog.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

Just a quick test run now before release.

Last fixes before release

---

scripts/examples/25-Machine-Learning/nn_cifar10_search_just_center.py
scripts/examples/25-Machine-Learning/nn_cifar10_search_whole_window.py
scripts/examples/25-Machine-Learning/nn_lenet_search_just_center.py
scripts/examples/25-Machine-Learning/nn_lenet_search_whole_window.py
src/cmsis/include/arm_nnfunctions.h
src/cmsis/src/nn/ActivationFunctions/arm_nn_activations_q7.c
src/cmsis/src/nn/ConvolutionFunctions/arm_convolve_HWC_q15_fast_nonsquare.c
src/omv/nn/nn.c
src/omv/nn/nn.h
src/omv/py/py_nn.c
src/omv/py/qstrdefsomv.h

The first few commits do some cleanup.
The next few commits bring in changes from the ARM NN library.
The commits afterward add ROI support to the NN runner.
Finally, I add the multi-scale code and examples.
Everything is tested and nothing has been broken.

Nn upgrade

---

scripts/examples/25-Machine-Learning/nn_cifar10.py
scripts/examples/25-Machine-Learning/nn_haar_smile_detection.py
scripts/examples/25-Machine-Learning/nn_lenet.py
src/omv/py/py_nn.c

Both CIFAR and LENET work still.
The smile network... I couldn't really get to work before or afterwards.
I noticed the Haar Cascade one has trouble finding my face. Maybe fix via using
the contrast settings of the previous Haar scripts?
Also, does the smile network need the whole face? Because the bounding rect on my face is missing my forehead.
...
Note, I want to get this fix in before the release otherwise we're stuck with the unscaled values for life. Since the scaling is done with floats this mod is reversible in python if the user needs to undo it.

Make both networks output the same value types.

---

src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/py/py_image.c

Fix OMV2 build.

---

src/omv/nn/nn.c

* This is a workaround until a proper fix is found.

NN: fix col buffer size.

---

src/omv/lepton.c

Tested and works for flir 1/3 in gs and rgb565 with multiple resolutions and resolutions that causes cropping.

Lepton driver working great for flir 1/3 with scaling now.

---

src/uvc/src/main.c

* All sensors support streaming callback now.

Remove streaming callback workaround.

---

scripts/examples/23-Motor-Shield/motor.py
scripts/examples/23-Motor-Shield/stepper.py
scripts/libraries/tb6612.py

I rename the file, shorter.
motor.py example is easier to understand.

add tb6612 library, DC motors and stepper example

---

src/Makefile
src/omv/Makefile
src/omv/py/py_tv.c
src/omv/py/py_tv.h
src/omv/py/qstrdefsomv.h

I don't know if the name tv is good enough.
If you have a good name, I can change it.

Add tv module for `video output SHIELD`

---

src/omv/img/jpeg.c
src/omv/img/mathop.c
src/omv/img/pool.c
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

Making essential image manipulation easier...

Basic method updates

---

src/omv/img/imlib.c
src/omv/img/imlib.h

Cleanup color methods

---

scripts/libraries/vl53l1x.py

fixed class name

---

src/omv/main.c

Allow ctrl-C to work with UARTs put on REPL.

---

src/omv/py/py_nn.c

Add break statement in switch-case in py_net_search function.
Reference issue #516

fixed missing break statement in py_net_search.

---

src/omv/lepton.h

* Set Lepton clock to 24MHz to work with the new clock speed.

Fix Lepton clock.

---

src/omv/main.c

* Update extint from upstream to fix EXTI number.
* Fix EXTI numbers in rtc.c
* Disable wakeup timer when initializing RTC.
* Call RTC init in soft reset.

Fix RTC issues on H7.

---

src/omv/img/apriltag.c

A little bit more decoder overhead but not really that much.

Allow apriltag detection on vflip and hmirrored images.

---

src/omv/py/py_image.c

User pointed this out a while back

Fix Quote Location

---

src/omv/img/imlib.c

Fix binary ops bug.

---

src/omv/img/bmp.c
src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/ppm.c

* line_start is not used in these functions.

Remove line_start from read_pixels functions.

---

src/Makefile
src/omv/main.c

Add FDCAN support.

---

src/omv/img/bmp.c

Fix reading RGB 24-bit images

---

src/cmsis/src/st/system_stm32fxxx.c

* Use PLL2 for FMC and PLL3 for SPI123.

Update H7 PLLs.

---

scripts/examples/33-Light-Shield/light.py

light example for light shield

---

src/omv/py/py_image.c

* Allow iterating over image objects.
* This is mainly to support creating ulab ndarrays from images.

Make images iterable.

---

src/omv/py/py_helper.c

Changed "Image format is not supported" to more specific errors for easier troubleshooting.

More specific image format errors.

---

src/omv/img/imlib.c

Fix sepconv3 boundaries.

---

src/bootloader/include/qspif.h
src/bootloader/src/main.c
src/bootloader/src/qspif.c
src/bootloader/src/stm32fxxx_hal_msp.c
src/bootloader/src/usbd_cdc_interface.c
src/omv/boards/OPENMV4R/omv_boardconfig.h
src/sthal/h7/Makefile

NOTE: The new bootloader will Not work until the IDE is updated.

Add boootloader QSPI flash support.

---

src/omv/img/apriltag.c
src/winc1500/src/winc.c

The apriltag linked list search and image thresholding are significantly faster with this set of changes. It doesn't appear to have broken anything. Measuring the effect on the frame rate is harder. With an image full of apriltags, the minimum speed seems to have been accelerated from 7.7fps to 10.6fps.

first round of optimizations

---

src/omv/img/apriltag.c

I saved a few more % by removing boundary checks which were applied to every pixel of the reduced resolution thresholded image (for a blur filter). I also improved a line fitting function by eliminating a divide in the inner loop.

additional optimizations for thresholding and line search

---

src/omv/img/jpeg.c

Converted the RGB->YUV code to use integer math. No precision is lost because the output is 8-bit unsigned values. New max framerates I see in the IDE are 34 fps for QVGA RGB565 and 15 fps for VGA (bayer). This is generic C code. The Cortex-M4/M7 SIMD instructions don't really get us any benefit in this case because time would be lost moving 16-bit values around to make use of the multiply-accumulate instruction.

sped up JPEG capture with integer math

---

src/omv/img/apriltag.c
src/omv/img/lsd.c

This PR includes a major rewrite of find_line_segments() which nets a 4-5x speedup over the original code. I also found an easy improvement to apriltags which speeds it up 10-15%.

find_line_segment and apriltags speedup

---

src/omv/img/jpeg.c

Optimized the software path of JPEG compression and removed the last vestiges of dependency on a YUV LUT.

Software JPEG compressor optimization

---

src/Makefile
src/omv/Makefile
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/py/py_imu.c
src/omv/py/py_imu.h
src/omv/py/qstrdefsomv.h
src/omv/stm32fxxx_hal_msp.c
src/st/Makefile
src/st/include/lsm6ds3_reg.h
src/st/include/lsm6ds3tr_c_reg.h
src/st/src/lsm6ds3_reg.c
src/st/src/lsm6ds3tr_c_reg.c

Add IMU driver

---

src/omv/boards/OPENMV1/imlib_config.h
src/omv/boards/OPENMV2/imlib_config.h
src/omv/boards/OPENMV3/imlib_config.h
src/omv/boards/OPENMV4/imlib_config.h
src/omv/boards/OPENMV4P/imlib_config.h
src/omv/boards/PORTENTA/imlib_config.h
src/omv/img/imlib.c
src/omv/py/py_image.c

* Added imlib control macro.
* Fixed cross issues in the image using round()
* Speed code up by removing -> and unnecessary checks.
* Test for image width/height validity.

Lens correction cleanup

---

src/omv/stm32fxxx_hal_msp.c

* Disable and clean caches only if they're enabled.

Fix hardfault on disable D cache.

---

scripts/examples/04-Image-Filters/perspective_and_rotation_correction.py
scripts/examples/04-Image-Filters/perspective_correction.py
src/omv/img/apriltag.c
src/omv/img/imlib.h
src/omv/img/phasecorrelation.c
src/omv/py/py_helper.c
src/omv/py/py_helper.h
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

* Optimized code to make it run slightly faster.
* Added fov argument to control the zoom effect better.
* Added perspective correction through 4 point correspondence.

Improve rotation_correction()

---

src/omv/img/phasecorrelation.c
src/omv/py/py_image.c

* Fixed image quality issues too.

Improved the speed of logpolar and linpolar transforms.

---

src/omv/img/filter.c

Optimized the median and mode image filters for binary, grayscale and rgb565 images.

optimized median and mode filters

---

src/omv/img/filter.c

The remaining filter algorithms in filter.c got "the treatment"

optimized more image filters

---

src/winc1500/src/winc.c

Both methods can move megabytes of data now without issues.
Also, fixed an uninitialized value returning from recv_from when you poll
for data and there's nothing to get.

Fix send/sendto

---

src/omv/framebuffer.c
src/omv/py/py_omv.c
src/omv/sensor.c

Fix disable FB

---

src/omv/py/py_image.c

No longer will calling compress() on a jpeg image blow up on you. Now handled intelligently.
(Need this for for the jpeg streamer I just made. So you can pass sensor.PIXFORMAT_JPEG and it works fine).

Modify compression methods to allow jpeg images

---

tools/rpc/README.md
tools/rpc/rpc.py
tools/rpc/rpc_image_transfer_jpg_as_the_controller_device.py
tools/rpc/rpc_image_transfer_jpg_streaming_as_the_controller_device.py
tools/rpc/rpc_popular_features_as_the_controller_device_example.py

Fix Python2/3 Errors

---

src/omv/img/apriltag.c

Fix rotation correction failing on the H7 Plus.
Add affine speed up to reduce work.
Change homography method to INVERSE versus SVD which seems to breakdown at extreme angles.

Fix and speedup rotation correction

---

src/omv/img/imlib.h
src/omv/img/shadow_removal.c
src/omv/img/stats.c
src/omv/py/py_image.c

It will do an image diff without requiring another buffer now.

Add image diff ability to get_histogram

---

src/omv/ov5640.c
src/omv/sensor.c

* Grayscale/RGB565/Bayer/JPEG works perfectly on all reses.
* Increased maximum JPEG image transfer size.
* Improved line buffer transfer rate.

Fixed OV5640 Imaging Modes

---

src/omv/img/jpeg.c

The bayer_to_ycbcr method was reading 1 pixel past the right edge when converting the rightmost pixels since the bayer to RGB algorithm averages the values of neighboring pixels. The new code re-uses the current pixel values to not read past the right edge.

Fixed right edge bayer conversion error

---

src/omv/sensor.c

* Simply the abort method.
* Improve comment clarity.

Modified sensor.c per Ibrahim's requests

---

src/omv/ov5640.c

The OV5640 now achieves the maximum frame rate possible for the DCMI bus in all modes. Resolutions not supported are properly caught now too.
The basics of the OV5640 at this point are now done. There is work to be done on improving the image quality and also working on some of the sensor control methods. However, the most important features are now done.

OV5640 readout speed doubled for high res BAYER/GRAYSCALE/JPEG

---

src/omv/py/py_image.c

https://forums.openmv.io/viewtopic.php?p=11338&sid=71b25798a86aa1f68cc19b0b4e7c9289#p11338

Get pixel now does debayering for bayer rgbtuple mode

---

src/omv/ov7690.c
src/omv/ov7725.c

Fix the bayer issue on the OV7690 and OV7725.

Fix bayer vflip on OV7725 and OV7690

---

src/omv/py/py_sensor.c

Triggers on reset now so that the rotation is set immediately. Matters if the camera started upside down, etc.

Update auto rotation to trigger on reset

---

src/omv/py/py_time.c

* Resetting the counter makes the FPS count jump up.

FPS clock fix.

---

src/omv/img/imlib.c

Return 0 if bbp is less than 0

Return 0 if bbp is less than 0

---

src/omv/cambus.c
src/winc1500/src/nm_bus_wrapper.c

Don't disable interrupts anymore for this HAL code. It's not required.

Remove disabling interrupts

---

scripts/examples/35-Readout-Control/apriltag_tracking.py

Add readout control for apriltag tracking

---

src/omv/ov5640.c

Fixes image quality at lower resolutions

---

src/omv/sensor.c

Reset sensor state in init0.

---

src/omv/sensor.c

Use dest_fb when copying line for OV5640/JPEG4

---

src/omv/fb_alloc.c
src/omv/framebuffer.c
src/omv/framebuffer.h
src/omv/py/py_helper.c

* Return the size of the available memory after the frame.
* Fixes #858

Fix fb_get_size.

---

src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

Move OpenMV3 stack to ITCM.

---

src/omv/usbdbg.c
src/omv/usbdbg.h

Revert "added system reset to bootloader command for portenta"

---

src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h

Fix FSYNC pin.

---

src/omv/img/draw.c
src/omv/img/imlib.h

Add inline functions declarations in header.

---

src/omv/img/imlib.c
src/omv/img/imlib.h
src/omv/img/jpeg.c

* Add missing JPEG read settings.
* Fix the JPEG loading code.
* NOTE: This only loads the image, it doesn't support decompression.

Support loading JPEG images

---

src/omv/sensor.c

* Fixes issue #883
* Allow the sensor to be reset if the regulator was shutdown.

Do hard-reset in sensor.reset().

---

src/omv/boards/PORTENTA/omv_boardconfig.h

* Generate 50MHz for SDMMC1 and SDMMC2.

Portenta: Fix PLL1.

---

src/omv/usbdbg.c

* Use the right IRQ number for USB HS.

Fix USBDBG IRQn bug.

---

scripts/examples/06-Video-Recording/image_reader.py
src/omv/py/py_image.c
src/omv/py/qstrdefsomv.h

In order to speed up access to the SD card when reading back video for other non vision purposes like network playback.

Added pause parameter to Image_Reader

---

src/omv/boards/PORTENTA/omv_boardconfig.h

* Remove DCMI_PWDN pin define.

Update Portenta board config.

---

src/omv/main.c

* Will be replaced by co-routines soon.

Disable threading.

---

src/omv/main.c

* Early __fatal_error calls may try to log an error to file,
before any storage is initialized which may cause a hardfault.

Make sure storage is initialized before logging error.

---

src/bootloader/stm32fxxx.ld.S
src/omv/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

* Remove legacy bss symbols.
* Make sure _sidata is where it should be.

Cleanup linker scripts.

---

src/cmsis/include/core_cm7.h

Primarily fixes the cache maintenance macros.

Update the cmsis cm7 header

---

src/omv/py/py_fir.c

* Fixes occasional failure on F7 on soft-reset.

Retry AMG8833 init a few times.

---

src/omv/py/py_fir.c

* If the FIR I2C bus is interrupted during a read/write the I2C device misbehaves and gets stuck pulling SDA low and the next time the device is re-initialized the I2C controller detects an arbitration lost condition.
* The most affected sensor seems to be the AMG8833 on the F4, F7 and H7 micros and the MLX90640 on the F4 mirco.
* Add a function to switch SCL to GPIO and pulse SCL 10000 times to attempt to unstuck the I2C device, it will attempt this 1 time before giving up.
* This seems to work very well on all the tested micro-controllers.

Fix FIR I2C bus arbitration lost error.

---

src/omv/imlib/imlib.h
src/omv/modules/py_gif.c
src/omv/modules/py_image.c
src/omv/modules/py_mjpeg.c
src/omv/ports/stm32/sensor.h

* Remove dependency on sensor.h

Move pixel format to imlib.

---

src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_lcd_cec.c
src/omv/ports/stm32/modules/py_lcd_touch.c

Fix OPENMVPT build.

---

src/Makefile
src/drivers/mlx90621/LICENSE
src/drivers/mlx90621/Makefile
src/drivers/mlx90621/include/MLX90621_API.h
src/drivers/mlx90621/include/MLX90621_I2C_Driver.h
src/drivers/mlx90621/src/MLX90621_API.c
src/drivers/mlx90621/src/MLX90621_I2C_Driver.c
src/omv/ports/stm32/cambus.c
src/omv/ports/stm32/cambus.h
src/omv/ports/stm32/modules/py_fir.c
src/omv/ports/stm32/omv_portconfig.mk

* Remove all the old MLX90621 code and use the official MLX90621 driver.
* Add I2C functions to handle no stop and repeated start.
* Switch all FIR sensors to use HW I2C.
* Note1: May need to handle POR/brown-out conditions.
* Note2: There's a temporary workaround to FIR I2C handles and hard-coded I2C IRQs that will be fixed later.

Update MLX and FIR drivers.

---

src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/ports/nrf/main.c
src/omv/ports/stm32/main.c
src/omv/ports/stm32/sensor.c
src/uvc/src/main.c

* This decouples the framebuffer from the sensor.

Move framebuffer initialization to framebuffer.c

---

src/drivers/mlx90621/src/MLX90621_I2C_Driver.c
src/drivers/mlx90640/src/MLX90640_I2C_Driver.c
src/omv/common/cambus.h
src/omv/modules/py_fir.c
src/omv/ports/nrf/cambus.c
src/omv/ports/stm32/cambus.c

* Remove all the older functions
* New functions can be used to support any I2C sensor.
* Support controlling stop condition, repeated start and combining transfers.
* Tested MLX and AMG on stm32 and nrf ports.

Add new and updated read/write bytes functions.

---

src/hal/nrfx/src/nrfx_twi.c
src/omv/ports/nrf/cambus.c

* Deinit once before recovery.
* Reduce TWI timeout.

NRF Twi fixes.

---

src/omv/modules/py_fir.c

* Retry scan at least once before giving up. The bus can be stuck from the last run.

Fix cambus scan.

---

src/omv/alloc/xalloc.c

* Add the number of bytes to the exception message, could be very helpful to the user in debugging stuff.

Make xalloc exception more useful.

---

src/omv/modules/py_fir.c

Improve size calculation to account for extra space in the frame buffer.

Make copy_to_fb smarter about resources

---

src/omv/sensors/hm01b0.c

* Fix framerate for QVGA and QQVGA.
* Fix set_exposure calculations.
* Implement set_framerate

Update HM01B0 driver.

---

src/omv/ports/stm32/modules/py_lcd.c

* SPI CS was triggering too close to data movement.
* Transmit IT is not safe to use on data in a byte struct that is not statically allocated.
The LCD driver with triple buffering is now stable on the F7.

Fix issues with F7 LCD triple buffering

---

src/omv/imlib/jpeg.c

Fix JPEG Binary Image Compression, handles issues when the image width is not a multiple of 8.

Fix JPEG Binary Image Compression

---

scripts/examples/Arduino/Portenta-H7/19-Low-Power/himax_wakeup_on_motion_detection.py
src/omv/common/sensor.h
src/omv/modules/py_sensor.c
src/omv/sensors/hm01b0.c

* Add ioctl to switch to internal OSC for MD.
* Add example to show how to wake up from low-power on MD events.

Add Himax ioctl to control internal osc.

---

src/omv/ports/stm32/modules/py_lcd.c

Tested on:
M4
M7
H7
All work.
This PR uses a 4 beat AHB burst for reading 4 words of data to output to the LCD in 1 beat of a halfword write on the M4/M7.
For the H7 this uses a 4 beat AHB burst for reading 4 words of data to output to the SPI TX FIFO which will accept 16-bytes of data in a 4 beat AHB word write and then output that data to the LCD in 1 halfword chunks.

Massively reduces bus usage for SPI LCD

---

src/omv/ports/stm32/modules/py_tv.c

Uses WORD AHB 4 beat bursts for memory access with DMA and:
For the H7 -> 4 Beat WORD Peripheral Writes
For the F7/F4 -> Single Byte Peripheral Writes

Use the most efficient data transfers for TV DMA

---

src/omv/alloc/fb_alloc.c

Makes fb_alloc() provide 32-byte alignment on the M4 without a cache to ensure DMA memory access alignment rules for not crossing 1KB boundaries. The number could be 16 below but I wanted it to match the F7/H7.

Add alignment for the M4

---

src/hal/cmsis/include/cmsis_gcc.h
src/omv/ports/stm32/modules/py_tv.c

I discovered a faster way of doing this with JPEG and just want to make sure it's used in this code too.

TV driver SIMD update

---

src/omv/sensors/ov5640.c

Fix autofocus logic

---

src/omv/ports/stm32/modules/py_fir_lepton.c

Were are transferring 328 bytes which is not a multiple of 16 so we cannot use INC4 modes with WORDS. So, this just tries to be a little bit more efficient with DMA FIFOs. But, doesn't have any burst size improvements.
Also fixes to the clock being too slow on the H7 for the FLIR LEPTON 3.

Improve FLIR module DMA efficiency

---

src/omv/alloc/fb_alloc.c
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/ports/stm32/stm32fxxx.ld.S
src/uvc/stm32fxxx.ld.S

Cleanup FB_ALLOC_OVERLAY pointers

---

src/omv/boards/OPENMVPT/omv_boardconfig.h

* Remove unused softqspi protocol.
* Move QSPI flash to data memory, to free the DTCM.

Cleanup QSPI flash config.

---

src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h

Reduce DMA buffer size

---

src/omv/imlib/jpeg.c

I changed the bayer_to_ycbcr code for jpeg encode to separate the boundary checking part into a separate path and made use of unaligned reads to speed up the data gathering.

Sped up jpeg bayer_to_ycbcr for encode

---

src/omv/imlib/jpeg.c

Brings JPEG debayering down to:
VGA -> 19-20ms
QVGA -> 5-6ms
QQVGA -> 0-1ms
So, this is above 50 Hz FPS. Woot!
...
The code also implements quite correct boundary checking. I tested with different resolutions of bayer using set_windowing() down to 8x8 from 640x480 and it has no problems.
The fast speed is achieved by two loops for the inner parts of the image and the outer parts of the image.
...
Larry's improved code works for the M4/M7 still. The H7 is maxed out with my new code.

Speed debayering to 19.5ms for VGA

---

src/omv/ports/stm32/main.c

Causes compile error if disabled.

Ifdef out lcd/tv init0

---

src/cm4/Makefile
src/cm4/src/main.c
src/cm4/src/stm32h7xx_it.c
src/hal/stm32/h7/Makefile
src/omv/ports/stm32/omv_portconfig.mk

* Enable HSEM driver.
* Use HSEM to sync standby mode.

Update CM4 firmware.

---

src/omv/imlib/imlib.h
src/omv/modules/py_helper.c
src/omv/modules/py_helper.h
src/omv/modules/py_image.c

You can now use .copy() to copy jpegs.

Add jpeg copying support

---

src/omv/common/sensor.h
src/omv/modules/py_sensor.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c
src/omv/sensors/lepton.c
src/omv/sensors/mt9v034.c
src/uvc/src/main.c

* Will be replaced by double buffering soon.

Remove streaming mode.

---

src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/modules/py_fir.c
src/omv/modules/py_image.c
src/omv/modules/py_imageio.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c
src/omv/sensors/lepton.c

* Will be used to swap buffers later.

Change update_jpeg_buffer arg to bool.

---

src/omv/ports/nrf/main.c
src/omv/ports/stm32/main.c

* make sure framebuffer and fb_alloc are initialized before sensor_init0

Fix init order.

---

src/omv/ports/stm32/stm32fxxx_hal_msp.c

Remove PC2/3_C as we only have PC2/3_C on the original H7

---

src/omv/ports/stm32/modules/py_fir_lepton.c
src/omv/ports/stm32/modules/py_lcd.c

Tail is the front of the queue. Head is back.

Rename head/tail per convention

---

src/omv/modules/py_helper.c

Fix mp_const_none comparison

---

src/omv/modules/py_imageio.c

Fix ImageIO pause arg.

---

src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_lcd_touch.c

MP API changed. Functionality is the same though.

Use new software I2C

---

src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c

Add no change checks

---

src/omv/boards/BORMIO/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/boards/PORTENTA/omv_boardconfig.h
src/omv/ports/stm32/sensor.c

Adds support for MDMA data movement of lines from the DMA line buffer to the image buffer for CPU offload.

MDMA Offload for camera data capture.

---

src/omv/modules/py_sensor.c
src/omv/ports/nrf/sensor.c
src/omv/ports/stm32/sensor.c

* Handles no change situations
* Improves ability to pass the window
* Auto handles intersections.
* Generally much more friendly.

Make set_windowing much more flexible

---

src/drivers/winc1500/src/winc.c

* Allow functions to continue to wait for async event if send ACK is received.

WINC1500: Handle out of band ACKs.

---

src/omv/imlib/framebuffer.c

Fix mutex init

---

src/omv/common/usbdbg.c

* Set RTC magic only for boards that need it.

Fix reset to bootloader command.

---

src/hal/cmsis/include/cmsis_gcc.h

Add missing macros for hardware that doesn't have them.

Add signed and unsigned saturate

---

src/bootloader/Makefile
src/uvc/Makefile

* Fixes issue with built-in string functions after gcc update.

Add special Makefile rule for string functions.

---

src/omv/modules/py_sensor.c

Found error when writing docs.

Fix name typo

---

src/omv/ports/stm32/ulpi.c

ULPI low power mode fixes.

---

src/omv/ports/stm32/sensor.c

Enables 100% MDMA offload where the processor only receives 2 interrupts per image (DMA Complete User and DCMI Frame Interrupt). With this feature you completely unload the processor from being interrupted per line of the image significantly reducing system loading and leading to big FPS improvements across the board for all algorithms (the memory bandwidth load of the capture data capture remains of-course).
Code works with all cameras. With this PR there is no more performance to pick from the tree of MDMA. Things are now maxed out.
...
I tested this code on all cameras with different resolutions, pixformats, and transpose. The new code works on all systems.

Enable 100% MDMA offload for all sensors

---

src/omv/modules/py_sensor.c

Make error messages for snapshot more human readable.

Improve snapshot error messages

---

src/omv/modules/py_sensor.c

Check if framesize is invalid first here.

Add missing framesize init check

---

src/omv/ports/rp2/main.c

* Fix inquiry_cb bug.
* Align with upstream PR.

RP2: Update MSC mode.

---

docker/README.md

README includes:
- Section about how to use docker build to build the firmware with various TARGETs
- Section about testing post/get requests using a nginx web server via docker

Add docker README

---

src/hal/cmsis/include/cmsis_gcc.h
src/omv/Makefile
src/omv/imlib/draw.c
src/omv/imlib/imlib.h
src/omv/imlib/jpegd.c
src/omv/modules/py_image.c
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_tv.c
src/omv/ports/stm32/omv_portconfig.mk

Add preliminary software jpeg decoding support. Grayscale/Binary -> RGB565 conversion doesn't work yet. Everything else does. Larry will fix.

Add jpeg decoding support

---

src/omv/boards/PORTENTA/omv_boardconfig.h

* Add support for the breakout board.
* Enable extra sensor drivers.

Portenta: Add alternate I2C and PWM for breakout board.

---

src/drivers/ninaw10/src/nina.c
src/omv/ports/rp2/main.c
src/omv/ports/rp2/modules/py_nina.c
src/omv/ports/rp2/nina_bsp.c
src/omv/ports/rp2/omv_portconfig.cmake

* Fix BSP.
* Fix rp2 networking modules.
* Fix network module init.
* Fix timeouts.
* Fix TCP sockets.
* Fix UDP sockets.
* Add auto-binding for UDP sockets.

RP2: Nina WiFi fixes.

---

src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/ports/stm32/omv_portconfig.mk
src/omv/sensors/ov7670.c

OpenMV4 support OV7670
i also make a issue about it

OpenMV4 support OV7670

---

src/drivers/ninaw10/include/nina_bsp.h
src/drivers/ninaw10/src/nina.c
src/omv/ports/rp2/modules/py_nina.c
src/omv/ports/rp2/nina_bsp.c

* Fix accept and close.
* Check socket status before send/recv/accept etc..
* Fix auto-bind.
* Add BSP read_irq.

RP2: WiFi Nina fixes.

---

src/omv/ports/stm32/ulpi.c

Fix ULPI low power mode entry with USB disconnected.

---

src/omv/ports/rp2/main.c

* Update USB config macros.
* Increase Flash FS size.
* Add missing openmv_disk file.
* Enable MSC in bootloader.

RP2: Updates.

---

src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/ports/nrf/sensor.c
src/omv/ports/rp2/sensor.c
src/omv/ports/stm32/sensor.c
src/omv/sensors/gc2145.c
src/omv/sensors/hm01b0.c
src/omv/sensors/lepton.c
src/omv/sensors/mt9m114.c
src/omv/sensors/mt9v034.c
src/omv/sensors/ov2640.c
src/omv/sensors/ov5640.c
src/omv/sensors/ov7670.c
src/omv/sensors/ov7690.c
src/omv/sensors/ov7725.c
src/omv/sensors/ov9650.c
src/omv/sensors/paj6100.c

* Much easier to manipulate and saves some memory.
* Add field for bayer, set bayer format for mt9m.

Replace sensor flags with bit fields.

---

src/omv/imlib/lsd.c
src/omv/modules/py_image.c

Now accepts any image type too.

Move find_line_segments to draw image

---

scripts/examples/OpenMV/37-Event-Cameras/frogeye2020.py
scripts/examples/OpenMV/37-Event-Cameras/frogeye2020_with_tracking.py
src/omv/Makefile
src/omv/boards/NANO33/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/common/sensor.h
src/omv/common/sensor_utils.c
src/omv/imlib/binary.c
src/omv/ports/stm32/omv_portconfig.mk
src/omv/sensors/frogeye2020.c
src/omv/sensors/frogeye2020.h

Adds an event sensor driver for the frogeye2020 with examples.

Add basic frogeye2020 driver

---

src/omv/imlib/imlib.c
src/omv/imlib/jpeg.c

Fixes user bug on forums: https://forums.openmv.io/t/run-tflite-models-on-jpegs-in-post/6672/7

Fix jpeg loading

---

scripts/examples/Arduino/Portenta-H7/34-Remote-Control/popular_features_as_the_remote_device.py
scripts/examples/OpenMV/34-Remote-Control/popular_features_as_the_remote_device.py

Fix person detector model labels

---

src/drivers/ninaw10/src/nina.c
src/omv/ports/rp2/modules/py_nina.c

* Return -1 on timeout error from recv(), recvfrom(), send() and sendto().
* Disable active connections before connecting/reconnecting.
* Fix manual DNS bug.
* Set secondary DNS server

Nina WiFi driver fixes.

---

src/omv/modules/py_fir.c
src/omv/modules/py_image.c

Fixes the breaking changes to copy_to_fb when targeting another image as the buffer because of the previous pixformat updates and the addition of "size" which wasn't captured previously.

Fix copy_to_fb when targeting an image

---

src/omv/imlib/framebuffer.c
src/omv/ports/stm32/sensor.c

@kwagyeman 
* Should fix #1407

Make sure cached CPU writes are flushed before returning the buffer

---

scripts/examples/Arduino/Portenta-H7/02-Board-Control/can.py
scripts/examples/Arduino/Portenta-H7/34-Remote-Control/image_transfer_raw_as_the_controller_device.py
scripts/examples/Arduino/Portenta-H7/34-Remote-Control/image_transfer_raw_as_the_remote_device.py
scripts/examples/Arduino/Portenta-H7/34-Remote-Control/popular_features_as_the_controller_device.py
scripts/examples/Arduino/Portenta-H7/34-Remote-Control/popular_features_as_the_remote_device.py
scripts/examples/OpenMV/02-Board-Control/can.py
scripts/examples/OpenMV/34-Remote-Control/image_transfer_raw_as_the_controller_device.py
scripts/examples/OpenMV/34-Remote-Control/image_transfer_raw_as_the_remote_device.py
scripts/examples/OpenMV/34-Remote-Control/popular_features_as_the_controller_device.py
scripts/examples/OpenMV/34-Remote-Control/popular_features_as_the_remote_device.py
scripts/libraries/rpc.py

* sampling_point was renamed to sample_point in upstream.

Fix CAN keyword arg.

---

src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/omv_boardconfig.h

NANO-RP2040: Fix raw buffer size.

---

.github/workflows/firmware.yml

* Add action to update development release tag before re-releasing.
* Update actions messages.

github: Update workflow.

---

.github/workflows/firmware.yml

* Fix non-release tag creating release draft.

github: Update workflows.

---

scripts/examples/OpenMV/14-WiFi-Shield/mjpeg_streamer.py
scripts/examples/OpenMV/14-WiFi-Shield/mjpeg_streamer_ap.py
scripts/examples/OpenMV/14-WiFi-Shield/mjpeg_streamer_fir.py

Update mjpeg scripts.

---

src/omv/boards/PORTENTA/imlib_config.h
src/omv/boards/PORTENTA/ulab_config.h
src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/omv_portconfig.mk

ulab: Update to v4.0.0

---

src/lib/libtf/models/person_detection.txt
src/omv/modules/py_tf.c

py_tf.c: Fix output scaling for uint8/int8.

---

scripts/examples/OpenMV/27-Lepton/lepton_get_object_high_temp.py
src/omv/sensors/lepton.c

Add a high temp example and use reasonable default temps in C.

High temp cleanup

---

.github/workflows/firmware.yml
tools/ci.sh

* Use cache for GNU Arm Embedded Toolchain.

github: Enable caching workflow dependencies.

---

src/omv/sensors/gc2145.c

sensors: Fix GC2145 window subsampling ratio.

---

src/omv/ports/stm32/main.c

stm32: Fix openmv disk file.

---

src/drivers/winc1500/src/winc.c
src/omv/ports/stm32/modules/py_winc.c

* Change timeout meaning to match modusocket timeout.

drivers/winc1500: Fix timeout handling.

---

src/omv/modules/py_fir.c

sensors/FIR: Support buses with multiple devices.

---

src/omv/modules/py_fir.c

* Fix frame glitches when reading speed is slower than framerate.

sensors/MLX9064x: Sync frame reading.

---

src/omv/imlib/jpegd.c

imlib: Fix SIMD YCbCr to RGB conversion.

---

src/omv/ports/stm32/main.c

The change below looks complex but I just moved everything under "else".
When you stop main, it doesn't run all the deinit methods before USBDBG starts. This puts the camera into a weird state. We never saw any issues with this before because our main.py was simple. However, for the OpenMVPT main.py this results in the driver state being off as quite alot more stuff was going on than blinking an LED.

stm32: Fix module deinit between main.py to USBDBG.

---

.github/workflows/firmware.yml

github: Fix firmware workflow permissions.

---

src/omv/common/usbdbg.c
src/omv/common/usbdbg.h

* Fixes  #1634.
* Fixes  #1635.

ports/all: Add placeholders for new USBDBG commands.

---

src/omv/imlib/fmath.c

imlib: Optimize fmath ceilf and floorf functions.

---

src/omv/sensors/gc2145.c

sensors/GC2145: Implement sleep/low-power function.

---

docker/Dockerfile

tools/docker: Install Python3.

---

src/bootloader/src/usbd_conf.c
src/omv/ports/stm32/omv_portconfig.mk

* Enable VBUS sensing.
* Disable USB OTG ID pin configuration.

bootloader: Fix bootloader FS mode.

---

src/omv/sensors/lepton.c

* Sharing the VOSPI packet DMA buffer with line buffer does not work for OpenMV 4 PRO, because the packet buffer needs to be in D3.
* This will automatically allocate a DMA buffer for VOSPI packet in the same domain as the DMA peripheral.

sensors/LEPTON: Use dma_alloc for packet buffer.

---

scripts/examples/02-Image-Processing/00-Drawing/image_drawing_advanced.py

Fixes: https://github.com/openmv/openmv/issues/1688

examples: Fix image drawing advanced script.

---

src/omv/ports/nrf/omv_portconfig.mk
src/omv/ports/rp2/omv_portconfig.cmake
src/omv/ports/stm32/omv_portconfig.mk

micropython: Update ulab to 5.1.1.

---

src/omv/ports/stm32/cambus.c
src/omv/sensors/lepton.c

misc: Fix debug_printf.

---

src/omv/imlib/draw.c

Makes area scaling work for scaling from 0.99 -> 0.01. Tried all 100 scale factors.
I noticed this bug while fixing image roi scaling.

imlib: Fix Draw Image Area Scaling.

---

src/omv/imlib/agast.c
src/omv/imlib/blob.c
src/omv/imlib/clahe.c
src/omv/imlib/fast.c
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_tv.c

imlib: Fix possible signed/unsigned comparisons issues.

---

src/omv/ports/stm32/modules/py_lcd.c

Fixes issue: https://github.com/openmv/openmv/issues/1766

ports/stm32: Add byte reversal support to lcd screen.

---

src/omv/modules/py_image.c

Passing an argument to compress like 90 was causing the camera to scale the image by 90x horizontally versus setting the compression amount.
This change fixes the API to maintain the old code.

imlib/jpeg: Fix compression argument order.

---

scripts/libraries/rpc.py
scripts/libraries/rtsp.py

Code formatting, no functional changes.

scripts/libraries: Format RPC/RTSP libraries.

---

src/omv/common/usbdbg.c

* Switch to statically allocated exception.
* Refactor common code.
* Misc fixes to harden the exec/stop commands.

misc/usbdbg: Refactor USB debugger code.

---

src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/omv_boardconfig.h
src/omv/boards/NANO33/omv_boardconfig.h
src/omv/common/tinyusb_debug.c

* Fix CDC task scheduling.
* Define tinyusb debug packet size.

misc/tinyusb_debug: Misc fixes.

---

src/omv/imlib/apriltag.c
src/omv/imlib/imlib.h
src/omv/modules/py_image.c

Adding per: https://forums.openmv.io/t/accuracy-of-april-tags-position/6572/19

imlib/apriltag: Add floating point centroid.

---

src/omv/boards/arduino_nano_33_ble_sense/omv_boardconfig.h
src/omv/ports/nrf/sensor.c
src/omv/sensors/ov7670.c

ports/nrf: Fix OV767x on ML kit.

---

src/omv/boards/ARDUINO_NICLA_VISION/imlib_config.h
src/omv/ports/stm32/omv_portconfig.mk

* The default/weak bthci was used.

ports/stm32: Link CYW43 BTHCI.

---

src/omv/ports/stm32/main.c

* Move GC before any deinitializing any drivers as some of them still need IRQs to clean up.

ports/stm32: Call gc_sweep before deinitializing networking drivers.

---

scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/connect.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/dns.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/http_client.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/http_client_ssl.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/mjpeg_streamer.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/mqtt_pub.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/mqtt_sub.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/ntp.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/scan.py
scripts/examples/10-Arduino-Boards/Nicla-Vision/03-WiFi/static_ip.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/connect.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/dns.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/http_client.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/http_client_ssl.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/mjpeg_streamer.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/mqtt_pub.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/mqtt_sub.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/ntp.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/scan.py
scripts/examples/10-Arduino-Boards/Portenta-H7/02-WiFi/static_ip.py

* Remove non-standard timeout arg and use isconnected.

examples: Update all networking scripts.

---

scripts/examples/10-Arduino-Boards/Nicla-Vision/05-Low-Power/extint_wakeup.py

examples: Fix Nicla Vision extint example.

---

scripts/libraries/rtsp.py

lib: Update the rtsp library to use the machine module.

---

src/omv/ports/mimxrt/main.c

mp_obj_t bdev = MP_OBJ_TYPE_GET_SLOT(&machine_sdcard_type, make_new) (&machine_sdcard_type, 1, 0, args);
Initializes the SD Card pins, clocks, checks CD, and etc. sdcard_detect() should not be called before. sdcard_init_pins() doesn't need to be called directly.
...
SD card is now reliably detected on power on and resets.

boards/OPENMV_RT1060: Fix SD Card Detection on power-on.

---

src/omv/modules/py_fir.c
src/omv/modules/py_image.c
src/omv/modules/py_tof.c
src/omv/ports/stm32/modules/py_lcd.c
src/omv/ports/stm32/modules/py_tv.c

py_helper_keyword_int_maybe if passed a value like `100 * 1.5` will return false because the value is `150.0`.
As you can imagine, this causes very confusing behavior.

imlib: Fix int maybe breaking.

---

src/omv/imlib/fmath.c

vcvtm and vcvtp are invalid instructions on the Cortex-M4. It crashes immediately when it executes them.
__ARM_FP is 4 on the cortex-m4 and should be 14 on the cortex-m7
... that said, in practice, something is overriding this output in our make files causing __ARM_FP to always be 4. It appears that passing the argument of the fp unit to GCC causes it to generate the wrong output.
```
kwagyeman@DESKTOP-EF0ULG9:~/GitHub/openmv2/src$ arm-none-eabi-gcc -mcpu=cortex-m7 -mabi=aapcs-linux -mthumb -mfloat-abi=hard -E -dM - < /dev/null | egrep -i 'thumb|arm|cortex|fp[^-]|version|abi' | sort | grep __ARM_FP
#define __ARM_FP 14
```
```
kwagyeman@DESKTOP-EF0ULG9:~/GitHub/openmv2/src$ arm-none-eabi-gcc -mcpu=cortex-m4 -mabi=aapcs-linux -mthumb -mfloat-abi=hard -E -dM - < /dev/null | egrep -i …
```

imlib/fmath: Fix invalid fp instruction usage on cortex-m4.

---

tools/uncrustify.cfg

* Disable PP define alignment.

tools: Update code formatting.

---

tools/uncrustify.cfg

misc: Update code formatting.

---

src/omv/ports/stm32/omv_portconfig.mk
src/omv/ports/stm32/omv_spi.c

- Link user switch module.
- Add missing string header for debug builds.

ports/stm32: Misc fixes.

---

scripts/examples/10-Arduino-Boards/Nicla-Vision/02-Audio/micro_speech.py
scripts/examples/10-Arduino-Boards/Portenta-H7/01-Audio/micro_speech.py
src/omv/ports/stm32/modules/py_micro_speech.c

- Need to poll events to schedule the audio callback after switching from pendsv.
- Fixes #1904

ports/stm32: Fix microspeech demo.

---

src/omv/imlib/draw.c

Previous code left open the door for corruption to happen in rare cases.

imlib: Fix DMA2D cache line access.

---

src/omv/imlib/filter.c

This PR is sponsored by OpenMV contracting services.
The client needed morph to run faster. This PR speeds up morph on grayscale and binary images by 2.5X or more for 3x3 convolution kernels (which are the most common).
The code is so fast now that there is almost 0 performance impact on QQVGA images.

imlib: Improve morph grayscale/rgb565 performance by 2.5x.

---

src/omv/modules/py_image.c

- Updates load image to use parse all.
- Adds new feature where you can now pass a bytearray in when making an image object to make a deep copy image from that byte array.

imlib: Support creating images from bytearrays.

---

scripts/examples/01-Camera/01-Video-Recording/imageio_read.py
scripts/examples/01-Camera/01-Video-Recording/imageio_write.py
scripts/examples/02-Image-Processing/00-Drawing/copy2fb.py

Remove sensor code that's not needed in some scripts.

scripts/examples: Update examples.

---

scripts/examples/09-OpenMV-Boards/01-WiFi-Shield/mjpeg_streamer.py
scripts/examples/09-OpenMV-Boards/01-WiFi-Shield/mjpeg_streamer_ap.py
scripts/examples/09-OpenMV-Boards/01-WiFi-Shield/mjpeg_streamer_fir.py

Improve these scripts to match the quality of the Arduino Board ones.

scripts: Improve OpenMV Boards MJPEG Examples.

---

src/omv/imlib/apriltag.c
src/omv/imlib/dmtx.c
src/omv/imlib/draw.c
src/omv/imlib/imlib.h
src/omv/imlib/lsd.c
src/omv/imlib/mjpeg.c
src/omv/imlib/qrcode.c
src/omv/imlib/zbar.c
src/omv/modules/py_fir.c
src/omv/modules/py_image.c
src/omv/modules/py_spi_display.c
src/omv/modules/py_tf.c
src/omv/modules/py_tof.c
src/omv/modules/py_tv.c
src/omv/ports/stm32/modules/py_display.c

Resolves https://github.com/openmv/openmv/issues/1933.

imlib: Move draw_image arguments to struct.

---

src/omv/modules/py_display.c
src/omv/modules/py_helper.c
src/omv/modules/py_helper.h
src/omv/modules/py_image.c

Targeted now to just two methods.

modules: Allow arg_to_image to load images from paths.

---

scripts/examples/07-Interface-Library/00-Arduino/arduino_uart.py
scripts/examples/50-Arduino-Boards/Nicla-Vision/50-Board-Control/uart_control.py
scripts/examples/50-Arduino-Boards/Portenta-H7/50-Board-Control/uart_control.py
scripts/examples/50-OpenMV-Boards/50-Board-Control/uart_control.py

Fixes: https://github.com/openmv/openmv/issues/1838

scripts/examples: Add timeout_char to uart examples.

---

scripts/examples/08-RPC-Library/34-Remote-Control/popular_features_as_the_controller_device.py
scripts/examples/08-RPC-Library/34-Remote-Control/popular_features_as_the_remote_device.py
scripts/libraries/rpc.py
tools/rpc/rpc_popular_features_as_the_controller_device_example.py

Updates the interface library UART Master/Slave to work with Machine UART. Also, removed the person detection code from the library. Tested comms between the RT1062 and H7 Plus.

scripts/libraries: Change the RPC Interface Library UART Master.

---

scripts/examples/02-Image-Processing/00-Drawing/image_drawing_advanced.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_blending_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_blending_with_color_table_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_table_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_table_with_color_table_test.py

Fixes: https://github.com/openmv/openmv/issues/2062

scripts/examples: Remove old CENTER argument usage.

---

src/omv/modules/py_tf.c

Addresses everything but the two invoke issues here (https://github.com/openmv/openmv/issues/2024). I'll send a PR to fix that next with a libtf update.

modules/py_tf: Cleanup segment, detect, and callback data.

---

src/hal/cmsis/include/cmsis_extension.h
src/hal/cmsis/include/cmsis_gcc.h
src/omv/imlib/imlib.h

Moves our cmsis gcc extensions to a new file as requested.

hal/cmsis: Move cmsis gcc extensions to new file.

---

src/omv/ports/stm32/jpeg.c

Would have saved hours of debugging.

ports/stm32: Error on jpeg geometry mismatch.

---

src/omv/boards/OPENMV_RT1060/imlib_config.h
src/omv/ports/mimxrt/omv_portconfig.mk

board/OPENMV_RT1060: Enable ISP Ops.

---

src/omv/imlib/jpegd.c

This fix corrects the software JPEG decoder when decoding 4:4:4 images and the image size is not a multiple of 8. Previously it would overwrite pixels on the next line or below the last row.

imlib/jpegd: Fix jpeg decode for non-multiple of 8.

---

src/omv/imlib/bayer.c
src/omv/imlib/imlib.h
src/omv/modules/py_image.c
src/omv/ports/mimxrt/sensor.c
src/omv/ports/stm32/omv_portconfig.mk
src/omv/ports/stm32/sensor.c

Fixes: https://github.com/openmv/openmv/issues/2083

ports: Fix sensor bayer image with cropping and transpose.

---

src/omv/imlib/draw.c

Hi, I add anti aliasing feature in draw_line method. I tested Binary, Grayscale and RGB565 format.
Reference code: https://gist.github.com/randvoorhies/807ce6e20840ab5314eb7c547899de68
test code in OpenMV Cam:
```
import sensor
import time
sensor.reset()  # Reset and initialize the sensor.
sensor.set_pixformat(sensor.RGB565)# Set pixel format to RGB565 (or GRAYSCALE)
#sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.QVGA)  # Set frame size to QVGA (320x240)
sensor.skip_frames(time=2000)  # Wait for settings take effect.
while True:
clock.tick()  # Update the FPS clock.
img = sensor.snapshot()  # Take a picture and return the image.
img.draw_line(10,10,100,200, (255,0,0),5)
```
Results:
after_anti_aliasing:
no_anti_aliasing:

imlib/draw: Add anti aliasing in draw_line.

---

src/omv/common/sensor_utils.c
src/omv/imlib/imlib.h
src/omv/imlib/yuv.c
src/omv/modules/py_image.c
src/omv/ports/mimxrt/sensor.c
src/omv/ports/stm32/omv_portconfig.mk
src/omv/ports/stm32/sensor.c

Fixes: https://github.com/openmv/openmv/issues/2084

ports: Add yuv shift to match bayer shift.

---

src/omv/boards/ARDUINO_NICLA_VISION/manifest.py
src/omv/boards/ARDUINO_NICLA_VISION/ulab_config.h

boards/NICLA_VISION: Reduce flash usage.

---

src/omv/imlib/binary.c
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/modules/py_helper.c
src/omv/modules/py_helper.h
src/omv/modules/py_image.c

Move this method out of py_helper.c

imlib: Add ksize helper.

---

src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h

boards/ARDUINO_GIGA: Enable GC2145 driver.

---

scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/adc.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/can.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/i2c_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/led_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/led_control_pwm.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/motor_control_dir_pwm.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/motor_control_hbridge.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/pin_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/power_good_pin.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/pwm_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/rtc.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/servo_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/spi_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/switch_pin.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/timer_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/uart_control.py
scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/watchdog.py

Fixes: https://github.com/openmv/openmv/issues/2071

scripts/examples: Add imxrt board control examples.

---

src/omv/sensors/gc2145.c

Fixes: https://github.com/openmv/openmv/issues/2165

sensors/gc2145: Fix hmirror and vflip.

---

src/omv/imlib/binary.c
src/omv/imlib/blob.c
src/omv/imlib/filter.c
src/omv/imlib/imlib.c
src/omv/imlib/imlib.h
src/omv/imlib/isp.c
src/omv/imlib/stereo.c
src/omv/imlib/yuv.c
src/omv/modules/py_helper.c
src/omv/sensors/gc2145.c
src/omv/sensors/hm01b0.c
src/omv/sensors/hm0360.c
src/omv/sensors/lepton.c
src/omv/sensors/mt9m114.c
src/omv/sensors/mt9v0xx.c
src/omv/sensors/ov2640.c
src/omv/sensors/ov5640.c
src/omv/sensors/ov7690.c
src/omv/sensors/ov7725.c
src/omv/sensors/ov9650.c
src/omv/sensors/paj6100.c

Fixes: https://github.com/openmv/openmv/issues/2159

imlib: Update min/max usage to clamp and sat.

---

scripts/libraries/pid.py

change pyb.millis to time.tick_ms, for supporting imx.rt

library/pid.py: change millis to ticks_ms

---

src/omv/ports/stm32/stm32fxxx_hal_msp.c

Fixes: https://github.com/openmv/openmv/issues/2173

ports/stm32: Don't control CS pin in slave mode.

---

src/omv/imlib/draw.c

The previous code did not bounds check before reading. This can cause the system to crash.

imlib/draw: Fix out of bound crash issue with set_pixel_aa.

---

src/omv/modules/py_image.c

modules/py_image: Fix morph spelling.

---

src/omv/imlib/draw.c

Refactored out of other commits.

imlib/draw: Cleanup drawline code.

---

src/omv/ports/mimxrt/sensor.c

Retry to submit the transfer a few times if the DMA is busy, before dropping the frame.

ports/mimxrt: Retry transfer if the DMA is still busy.

---

src/omv/modules/py_image.c

py_helper_arg_to_ksize() checks that ksize is greater than or equal to 0. So, using it again.

modules/py_image: Move ksize to be pos_arg.

---

src/omv/modules/py_tf.c

modules/py_tf: Fix log buffer free-order.

---

src/omv/imlib/framebuffer.c
src/omv/imlib/framebuffer.h
src/omv/ports/mimxrt/sensor.c
src/omv/ports/stm32/sensor.c

Fixes: https://forums.openmv.io/t/openmv-cam-h7-screen-tearing/9686/7

ports: Fix accidental CPU cache invalidation.

---

src/omv/ports/stm32/modules/py_audio.c

Gain support works now. It doesn't seem to really improve the ability of the mic to listen. I still have to say "Yes" and "No" at the Nicla with a commanding voice. I do not need to be right next to it, though.

ports/stm32: Add mic gain support to py_audio when using dfsdm.

---

src/omv/imlib/draw.c

Looks nice. Works in all cases.

imlib/draw: Add AA support for draw_circle.

---

src/lib/tflm/tflm_backend.cc

Minor code cleanup in the backend.

lib/tflm: Code cleanup.

---

scripts/examples/03-Machine-Learning/00-TensorFlow/tf_object_detection.py
src/omv/modules/py_image.c

Scale should be a min and max range you are scaling from versus a raw fscale/fadd. Changing this now before the API is released.
Tested against FOMO.

modules/py_image: Change scale argument to (min,max) range.

---

src/omv/boards/ARDUINO_NANO_33_BLE_SENSE/omv_boardconfig.h
src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/omv_boardconfig.h
src/omv/boards/OPENMV_RT1060/omv_boardconfig.h
src/omv/common/tinyusb_debug.c
src/omv/common/usbdbg.c
tools/pyopenmv.py

msic: Update GET_STATE command.

---

scripts/libraries/ml/ml/preprocessing.py

scripts/libraries: Update normalization to handle 3D/4D image tensors.

---

src/omv/modules/py_image.c

morph()/gaussian()/laplacian() updated to use mp_arg_parse.

modules/py_image: Update morph() to use arg parse.

---

src/omv/common/common.ld.S

misc: Update common linker script.

---

src/omv/imlib/draw.c
src/omv/imlib/imlib.h
src/omv/modules/py_tv.c
src/omv/ports/stm32/jpeg.c

Fixes: https://github.com/openmv/openmv/issues/2219

imlib/draw: Add missing speculative read invalidates.

---

src/README.md

This resolves the issue encountered in https://github.com/openmv/openmv/issues/2301.

misc: Update GCC toolchain installation instructions.

---

src/lib/tflm/Makefile

lib/tflm: Fix Makefile rules to generate files once.

---

.github/workflows/code-size-report.yml

misc/github: Update workflow.

---

src/omv/imlib/jpegd.c

Fixes: https://github.com/openmv/openmv/issues/2295

imlib/jpegd: Fix for JPEG decoder boundary problem.

---

.github/workflows/code-size-report.yml

Update code size report comment instead of posting new ones.

misc/github: Update workflows.

---

src/omv/ports/stm32/stm32fxxx_hal_msp.c

common: Change linker variable to uint32.

---

src/Makefile
src/omv/common/omv_common.h
src/omv/imlib/draw.c
src/omv/imlib/imlib.h
src/omv/imlib/jpegd.c
src/omv/imlib/jpege.c
src/omv/imlib/png.c
src/omv/ports/stm32/jpeg.c
src/omv/ports/stm32/omv_gpu.c

Those can be used for timing functions. To enable build with PROFILE=1.

misc/common: Add timing macros.

---

src/omv/imlib/jpege.c

Remove STORECODE macro and just use write_bits. This has absolutely no effect on performance, but makes the code easier read.

imlib/jpeg: Minor clean-up.

---

tools/pyopenmv.py
tools/pyopenmv_fb.py

* Add scale arg.
* Fix RGB565 byte order.
* Use bilinear scaling.

tools/pyopenmv: Misc fixes.

---

src/omv/common/usbdbg.c
src/omv/imlib/framebuffer.c

This reverts commit afcd12cb6aff0d5d2897a1f0d15a3e08fe10151c.
This change was never needed.

common/usbdbg: Revert changes to usbdbg/framebuffer.

---

src/omv/common/omv_common.h
src/omv/imlib/draw.c
src/omv/imlib/jpegd.c
src/omv/imlib/jpege.c
src/omv/imlib/png.c
src/omv/modules/py_ml.c
src/omv/ports/stm32/jpeg.c
src/omv/ports/stm32/omv_gpu.c

Now it can be called multiple times in the same function and can be nested.

misc/common: Fix profiling macro.

---

.github/workflows/firmware.yml
tools/ci.sh

github: Add LLVM toolchain to CI.

---

tools/haar2c.py
tools/tflite2c.py

tools: Update converters.

---

src/lib/tflm/tflm_backend.cc

On some boards, FB memory can become less than the available GC memory for example with 3 frame buffers or a big frame. In this case the first pass allocation (the one used to get the tensor arena's actual size) can fail, even though GC has enough memory to allocate the arena. This patch uses GC's free memory in the first pass to get the arena size.

lib/tflm: Use GC's free memory for the temporary tensor arena.

---

src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/common/sensor.h
src/omv/common/sensor_utils.c

misc/common: Support overriding the resolution table.

---

src/omv/imlib/draw.c

Improved the blending math used to be more accurate. The previous version does the divide too early, which can result in artifacts.
Removed SIMD code from this. It's not going to make much of a difference here, as there's no loop.

imlib/draw: Optimize set_pixel_aa.

---

docker/README.md
scripts/examples/07-Interface-Library/00-Arduino/arduino_i2c_slave.py
scripts/examples/07-Interface-Library/00-Arduino/arduino_spi_slave.py
scripts/examples/09-WiFi/http_post.py
scripts/examples/10-Bluetooth/temp_sensor_aioble.py
scripts/examples/50-Arduino-Boards/Giga-H7/50-Board-Control/usb_vcp.py
scripts/examples/50-Arduino-Boards/Nicla-Vision/50-Board-Control/usb_vcp.py
scripts/examples/50-Arduino-Boards/Portenta-H7/50-Board-Control/usb_vcp.py
scripts/examples/50-Arduino-Boards/Portenta-H7/53-Ethernet/http_client.py
scripts/examples/50-Arduino-Boards/Portenta-H7/53-Ethernet/http_client_ssl.py
scripts/examples/50-OpenMV-Boards/50-STM32-Boards/50-Board-Control/usb_vcp.py
scripts/examples/50-OpenMV-Boards/60-Shields/61-Servo-Shield/pca9685.py
scripts/libraries/lora.py
scripts/libraries/mutex.py
scripts/libraries/requests.py
scripts/libraries/uftpd.py
scripts/libraries/uping.py
scripts/libraries/utelnet.py

scripts: Remove obsolete u-prefix from imports.

---

src/lib/tflm/tflm_backend.cc

* Fixes an issue with certain models.

lib/tflm: Add extra padding to arena size.

---

src/boot/src/common/desc.c
src/boot/src/common/main.c
src/boot/src/ports/stm32/stm32.ld.S
src/boot/src/ports/stm32/stm32_port.c
src/boot/src/ports/stm32/tusb_config.h

- Fix string descriptos.
- Allow board to override port/speed.
- Cleanup clock config.

bootloader: Misc fixes.

---

src/boot/include/flash.h
src/boot/include/port.h
src/boot/src/common/dfu.c
src/boot/src/common/main.c
src/boot/src/common/mpu.c
src/boot/src/ports/stm32/stm32_port.c
src/boot/src/ports/stm32/stm32_port.mk
src/boot/src/ports/stm32/stm32_usb.h
src/boot/src/ports/stm32/stm32_xspi.c

- Add XSPI driver.
- Add common MPU driver.
- Add basic N6 support.
- Add support for XIP partitions.

bootloader: Misc fixes and updates.

---

src/omv/ports/rp2/main.c

ports/rp2: Fix firmware.

---

scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_blending_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_blending_with_color_table_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_table_test.py
scripts/examples/02-Image-Processing/00-Drawing/image_drawing_alpha_table_with_color_table_test.py
scripts/examples/02-Image-Processing/03-Frame-Differencing/in_memory_advanced_frame_differencing.py
scripts/examples/02-Image-Processing/03-Frame-Differencing/on_disk_advanced_frame_differencing.py
scripts/examples/50-OpenMV-Boards/60-Shields/62-Thermopile-Shield/thermal_overlay.py
scripts/examples/50-OpenMV-Boards/60-Shields/62-Thermopile-Shield/thermal_overlay_lcd.py
src/omv/common/omv_gpu.h
src/omv/imlib/apriltag.c
src/omv/imlib/binary.c
src/omv/imlib/dmtx.c
src/omv/imlib/draw.c
src/omv/imlib/lsd.c
src/omv/imlib/mjpeg.c
src/omv/imlib/qrcode.c
src/omv/imlib/zbar.c
src/omv/modules/py_display.c
src/omv/modules/py_fir.c
src/omv/modules/py_image.c
src/omv/modules/py_mjpeg.c
src/omv/modules/py_tof.c
src/omv/modules/py_tv.c
src/omv/ports/stm32/modules/py_display.c
src/omv/ports/stm32/omv_gpu.c

Note that this is a breaking change. Anyone passing an alpha of 256 will get an error message.
Fixes: https://github.com/openmv/openmv/issues/2438

imlib: Update draw_image alpha to 0-255 from 0-256.

---

src/omv/boards/ARDUINO_NICLA_VISION/omv_boardconfig.h
src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
src/omv/boards/OPENMV2/omv_boardconfig.h
src/omv/boards/OPENMV3/omv_boardconfig.h
src/omv/boards/OPENMV4/omv_boardconfig.h
src/omv/boards/OPENMV4P/omv_boardconfig.h
src/omv/boards/OPENMVPT/omv_boardconfig.h
src/omv/ports/stm32/omv_spi.c

- Fix SPI6 ID.
- Define SPI request in board config files.

ports/stm32: Update SPI driver.

---

scripts/examples/01-Camera/05-FLIR-Lepton/lepton_get_object_high_temp.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_get_object_temp.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_get_object_temp_color.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_get_object_temp_color_lcd.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_get_object_temp_lcd.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_target_temp_hotspot_grayscale_color_tracking.py
scripts/examples/01-Camera/05-FLIR-Lepton/lepton_target_temp_hotspot_rgb565_color_tracking.py

Not sure when these were renamed. https://github.com/openmv/openmv/commit/62708eb38bd0aadc2851f1a3b51655ed612b24d1?

scripts/examples: Fix new refactored IOCTL names.

---

scripts/libraries/rpc.py
src/omv/modules/py_omv.c

Fixes: https://github.com/openmv/openmv/issues/2532

modules/omv: Move debug mode flag to omv module.

---

scripts/examples/03-Machine-Learning/00-TensorFlow/tf_image_classification.py

Fixes: https://github.com/openmv/openmv/issues/2462
Switches the image classification example to running the built-in person detection network on the RT1062. Hits 18FPS on that board.

scripts/examples: Update image classification example.

---

src/omv/modules/py_ml.c

- Call fb_alloc_free_till_mark only if memory was actually allocated.

modules/py_ml: Clean up fb_alloc path.

---

src/omv/ports/stm32/omv_csi.c

Fixes: https://github.com/openmv/openmv/issues/2551

ports/stm32: Fix MDMA initialization.

---

.github/workflows/code-size-report.yml
.github/workflows/codeformat.yml
.github/workflows/commit.yml
.github/workflows/firmware.yml
tools/ci.sh

- Switch to ubuntu-24.04.
- Install a more recent make.

github: Update CI workflows.

---

src/lib/tflm/models/index.csv
src/lib/tflm/models/yolo_v2_224_small.txt

- Could be useful for testing.

lib/tflm/models: Add YOLOv2 model.

---

src/omv/common/usbdbg.c

Updates get_state() return a packet equal to the EP size that the IDE knows. This significantly helps with text buffer transfer on HS cameras. With this fix, it's very hard to trivially overflow the text buffer and get chopped-up text unless you are printing very large data structures. Results show that 25ms get_state() polling is good and does not result in any dropped text on high-speed cameras.
Tested in IDE commits past v4.4.4 release.
I verified that the IDE works with cameras without this change, FS cameras with this change, and HS cameras with this change.
Fixes: https://github.com/openmv/openmv/issues/2357

misc: Update get_state() to work with a variable packet size.

---

docker/build.sh
src/README.md

Small change to update src/README.md and docker/build.sh to reflect new micropython location.

misc: Fix files still referencing old micropython location.

---

src/omv/ports/stm32/omv_gpu.c

Removes the need for fb_alloc in the GPU driver.

ports/stm32: Move CLUT to DMA memory section.

---

src/omv/modules/py_csi.c
src/omv/modules/py_display.c
src/omv/modules/py_display_data.c
src/omv/modules/py_fir.c
src/omv/modules/py_gif.c
src/omv/modules/py_helper.c
src/omv/modules/py_helper.h
src/omv/modules/py_image.c
src/omv/modules/py_imageio.c
src/omv/modules/py_mjpeg.c
src/omv/modules/py_ml.c
src/omv/modules/py_omv.c
src/omv/modules/py_tof.c
src/omv/modules/py_tv.c

Replace all `uint n_args` to `size_t n_args`. 
#2586

modules: Replace uint with size_t.

---

src/omv/sensors/boson.c

Older FLIR Boson Sensors (< IDD 4.x) take almost 10 seconds to boot compared to newer FLIR Boson Sensors.
This change tests if the FLIR BOSON sensors has booted once a second for up to 10 times before giving up.

sensors/boson: Try to initialize the FLIR BOSON in a loop.

---

src/omv/ports/stm32/omv_i2c.c

i2c: disable fastmode at compile

---

src/omv/ports/stm32/ulpi.c

- Add support for reset to recover ULPI.
- Clean up formatting, comments.

ports/stm32: Update ULPI code.

---

scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_get_object_temp.py
scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_get_object_temp_color.py
scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_get_object_temp_color_lcd.py
scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_get_object_temp_lcd.py
scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_target_temp_hotspot_grayscale_color_tracking.py
scripts/examples/01-Camera/05-Thermal-Cameras/01-FLIR-Lepton/lepton_target_temp_hotspot_rgb565_color_tracking.py

Change the temperature to make it easier to find people.

example: Change lepton max_temp.

---

boards/OPENMV2/imlib_config.h
boards/OPENMV2/omv_boardconfig.h

boards/OPENMV2: Fix flash size.

---

ports/mimxrt/omv_csi.c

Fixes: https://github.com/openmv/openmv/issues/2683

ports/mimxrt: Fix unitialized edma_config fb pointer.

---

ports/alif/main.c

Add support for Alif machine_pin IRQ.

micropython: Update submodule.

---

common/omv_csi.c
common/omv_csi.h
drivers/boson/src/serialPortAdapter.c
drivers/genx320/src/psee_genx320.c
drivers/sensors/gc2145.c
drivers/sensors/genx320.c
drivers/sensors/hm01b0.c
drivers/sensors/hm0360.c
drivers/sensors/lepton.c
drivers/sensors/mt9m114.c
drivers/sensors/mt9v0xx.c
drivers/sensors/ov2640.c
drivers/sensors/ov5640.c
drivers/sensors/ov7670.c
drivers/sensors/ov7690.c
drivers/sensors/ov7725.c
drivers/sensors/ov9650.c
drivers/sensors/pag7920.c
drivers/sensors/pag7936.c
drivers/sensors/ps5520.c
ports/alif/omv_csi.c
ports/mimxrt/omv_csi.c
ports/nrf/omv_csi.c
ports/rp2/omv_csi.c
ports/stm32/omv_csi.c

Make CSI I2C bus a pointer. No functional changes, just to make  #2691 more readable (25 files less to view in the other PR).

misc: Refactor CSI I2C bus.

---

drivers/boson/include/serialPortAdapter.h
drivers/boson/src/serialPortAdapter.c
drivers/genx320/include/psee_genx320.h
drivers/genx320/src/psee_genx320.c
drivers/sensors/boson.c
drivers/sensors/genx320.c

Tested both sensors. All good.

drivers/sensors: Update new sensors to use the csi pointer.

---

ports/stm32/omv_gpu.c
ports/stm32/stm32_nema.c

Implements the full draw_image api spec as best as possible. Everything works. Fast alpha blending unlocked.

ports/stm32: Fully implement N6 GPU driver for draw_image.

---

modules/py_helper.c

modules/py_helper: Fix error arg_to_image error message typo.

---

ports/stm32/omv_csi.c
ports/stm32/stm_isp.c
ports/stm32/stm_isp.h

Can add more args or split it for finer control, but for now this is the same basic config moved to new file.

ports/stm32: Refactor CSI ISP code.

---

modules/py_omv.c

ports/mimxrt: Fix omv module UID function.

---

lib/imlib/draw.c

Fixes: https://github.com/openmv/openmv/issues/2627

lib/imlib: Fix draw line glitch.

---

ports/stm32/stm_dma.c

Fix DMA security config for non-circular channels.

ports/stm32: Fix N6 DMA security config.

---

common/omv_csi.c
common/omv_csi.h

See https://github.com/openmv/openmv/pull/2747#discussion_r2262310045

common/csi: Add support for custom resolutions.

---

lib/imlib/simd.h

SIMD ops broken out of PR: https://github.com/openmv/openmv/pull/2722

lib/imlib: New SIMD ops for ML acceleration

---

drivers/sensors/boson.c
drivers/sensors/paj6100.c

Follow on to: https://github.com/openmv/openmv/pull/2803
Tested changes and they work.

drivers/sensors: Update to using post_process callback.

---

.github/workflows/firmware.yml
Makefile
common/common.mk
common/omv_common.h
common/omv_profiler.c
common/omv_profiler.h
common/usbdbg.c
common/usbdbg.h
lib/imlib/bayer.c
lib/imlib/draw.c
lib/imlib/imlib.h
lib/imlib/imlib.mk
lib/imlib/jpegd.c
lib/imlib/jpege.c
lib/imlib/png.c
lib/stai/stai.mk
lib/tflm/tflm.mk
lib/tflm/tflm_backend.cc
modules/micropython.mk
modules/py_image.c
modules/py_ml.c
ports/alif/omv_gpu.c
ports/ports.mk
ports/stm32/omv_gpu.c
ports/stm32/stm_jpeg.c
tools/ci.sh
tools/pyopenmv.py
tools/pyopenmv_fb.py

This PR adds a simple code profiler that leverages, SysTick, the Performance Monitoring Unit (PMU) available on Armv8.1-M cores and `-finstrument-functions`.
- SysTick provides a simple high-resolution timer source, for min, max and total ticks.
- The PMU provies a cycle counter and multiple configurable event counters that can track low-level performance metrics such as cache misses, pipeline stalls, etc... See the Armv8.1-M Performance Monitoring User Guide for additional details.
- Function-level instrumentation is enabled using -finstrument-functions on select files to automatically record statistics on entry/exit.
- `pyopenmv_fb.py` has been upgraded  to support reading and rendering profiling. Additionally, it now support loading symbol tables from elf to map addresses to symbols. …

common: Add code profiler.
